/* Valores: electrolitos y proteínas. */
SolMed.registry.addValues(
  { id: 'electrolitos', name: 'Electrolitos', desc: 'Sodio, potasio, cloro, magnesio, fósforo, calcio y albúmina.' },
  [
    {
      id: 'na',
      name: 'Sodio',
      abbr: 'Na⁺',
      unit: 'mEq/L',
      low: 135,
      high: 145,
      decimals: 0,
      ref: '135–145',
      units: 'mEq/L = mmol/L.',
      represents: 'El principal catión extracelular. Su concentración refleja sobre todo el balance de **agua**, no el contenido corporal total de sodio.',
      up: {
        meaning: 'Hipernatremia: déficit de agua libre relativo al sodio; siempre implica hipertonicidad.',
        causes: ['Pérdidas de agua sin reposición (sed alterada, ancianos, acceso limitado al agua)', 'Diuresis osmótica (glucosuria en el EHH)', 'Diabetes insípida', 'Aporte hipertónico'],
        action: 'Calcular el déficit de agua y corregir lentamente.',
      },
      down: {
        meaning: 'Hiponatremia: exceso relativo de agua. Primero comprobar si es hipotónica (osmolalidad baja).',
        causes: ['Hiperglucemia: hiponatremia **translocacional**, no hipotónica', 'SIADH (en la HSA, también el síndrome pierde sal cerebral)', 'Hipovolemia, diuréticos tiazídicos', 'Insuficiencia cardíaca, cirrosis', 'Hipotiroidismo grave e insuficiencia suprarrenal'],
        action: 'Con hiperglucemia, corregir el sodio antes de interpretarlo.',
      },
      importance: 'En las crisis hiperglucémicas, el sodio medido infraestima el déficit de agua: hay que calcular el **sodio corregido**.',
      changes: 'El sodio corregido orienta el tipo de líquido tras la reanimación inicial y ayuda a detectar hipernatremia oculta.',
      topics: ['cad', 'ehh', 'hsa', 'hipotiroidismo'],
      pearl: 'En la HSA, ante una hiponatremia no restrinjas líquidos de entrada: puede tratarse de un síndrome pierde sal cerebral, y la hipovolemia favorece la isquemia tardía.',
      thresholds: [
        { kind: 'normal', value: '135–145 mEq/L', note: '' },
        { kind: 'terapeutico', value: 'Descenso ≤10 mEq/L en 24 h', note: 'En el EHH se evita que el sodio baje más de ~10 mEq/L al día (JBDS). En hiponatremia crónica, la corrección tampoco debe superar ~8–10 mEq/L en 24 h.' },
        { kind: 'critico', value: '<120 o >160 mEq/L', note: 'Valores de aviso habituales; varían por institución.' },
      ],
      critical: {
        stem: 'Sodio de 118 mEq/L con glucosa normal en una paciente que convulsiona. ¿Qué es lo más adecuado?',
        options: [
          { t: 'Bolo de salino hipertónico al 3 % para elevar el sodio unos 4–6 mEq/L', why: 'Correcto: hiponatremia grave sintomática. El objetivo inmediato es un ascenso pequeño que detenga los síntomas, sin superar ~8–10 mEq/L en 24 h.' },
          { t: 'Restricción de líquidos y control en 24 h', why: 'Es insuficiente ante síntomas graves como convulsiones.' },
          { t: 'Corregir hasta 140 mEq/L en 6 horas', why: 'Una corrección rápida produce desmielinización osmótica.' },
          { t: 'Furosemida sola', why: 'No trata la urgencia neurológica.' },
        ],
        answer: 0,
        explain: ['Hiponatremia <120 con convulsiones = urgencia.', 'Salino hipertónico en bolo con objetivo de 4–6 mEq/L en las primeras horas.', 'Límite de corrección en 24 h para evitar desmielinización osmótica.'],
      },
      fill: [
        { ask: 'Límite inferior normal del sodio sérico (mEq/L).', answer: 135, tol: 0, unit: 'mEq/L', explain: 'Rango habitual 135–145 mEq/L.' },
        { ask: 'Límite superior normal del sodio sérico (mEq/L).', answer: 145, tol: 0, unit: 'mEq/L', explain: 'Rango habitual 135–145 mEq/L.' },
      ],
      gen: { min: 110, max: 175, step: 1 },
      sources: ['ada2024', 'jbds'],
    },
    {
      id: 'k',
      name: 'Potasio',
      abbr: 'K⁺',
      unit: 'mEq/L',
      low: 3.5,
      high: 5.0,
      decimals: 1,
      ref: '3,5–5,0',
      represents: 'El principal catión intracelular: solo ~2 % está en el líquido extracelular. El sérico depende de la distribución (insulina, pH, catecolaminas) y del balance renal.',
      up: {
        meaning: 'Hiperpotasemia: riesgo de arritmias (T picudas, QRS ancho).',
        causes: ['Déficit de insulina e hiperosmolalidad (CAD: salida de K⁺ de la célula)', 'Insuficiencia renal', 'IECA/ARA-II, espironolactona', 'Hemólisis de la muestra (pseudohiperpotasemia)', 'Insuficiencia suprarrenal'],
        action: 'ECG inmediato; calcio IV si hay cambios; desplazar K⁺ al interior celular y eliminarlo.',
      },
      down: {
        meaning: 'Hipopotasemia: debilidad, íleo y arritmias (ondas U).',
        causes: ['Insulina (lo introduce en la célula)', 'Diuresis osmótica, vómitos', 'Diuréticos', 'Hipomagnesemia (dificulta la corrección)', 'Tirotoxicosis (parálisis periódica hipopotasémica)'],
        action: 'Reponer; corregir también el magnesio.',
      },
      importance: 'En la CAD el potasio sérico suele ser normal o alto **aunque el déficit corporal total sea grande**; la insulina lo hará caer.',
      changes: 'Con K⁺ <3,5 mEq/L **no se inicia la insulina**: primero se repone potasio (ADA 2024). Con 3,5–5,0 se añade potasio a los líquidos; con >5,0 no se añade y se controla cada 2 h.',
      topics: ['cad', 'ehh', 'hipertiroidismo'],
      pearl: 'Un K⁺ «normal» en una CAD es en realidad una **depleción**: la acidosis y la falta de insulina lo sacan de la célula.',
      thresholds: [
        { kind: 'normal', value: '3,5–5,0 mEq/L', note: '' },
        { kind: 'terapeutico', value: '<3,5 mEq/L', note: 'En la CAD o el EHH: retrasar la insulina y reponer potasio primero.' },
        { kind: 'terapeutico', value: '>5,0 mEq/L', note: 'En la CAD: no añadir potasio; controlar cada 2 h.' },
        { kind: 'critico', value: '<2,5 o >6,5 mEq/L', note: 'Valores de aviso habituales; varían por institución.' },
      ],
      critical: {
        stem: 'CAD con glucosa de 520 mg/dL, pH 7,08 y K⁺ de 3,1 mEq/L. Ya está recibiendo suero salino. ¿Qué haces con la insulina?',
        options: [
          { t: 'Retrasarla y reponer potasio IV hasta que el K⁺ supere 3,5 mEq/L', why: 'Correcto: la insulina introduce potasio en la célula y podría causar una hipopotasemia mortal.' },
          { t: 'Iniciar la insulina a 0,1 U/kg/h ya, porque la acidosis es grave', why: 'Riesgo de arritmia por hipopotasemia grave.' },
          { t: 'Administrar bicarbonato antes de la insulina', why: 'El bicarbonato también baja el potasio y no está indicado con pH ≥7,0.' },
          { t: 'Iniciar insulina en bolo y reponer potasio vía oral', why: 'Sigue exponiendo al paciente a una caída rápida del potasio.' },
        ],
        answer: 0,
        explain: ['Los líquidos van primero.', 'Con K⁺ <3,5 mEq/L se retrasa la insulina y se repone potasio.', 'Con K⁺ >3,5 se inicia la insulina y se añade potasio a los líquidos para mantenerlo en 4–5.'],
      },
      fill: [
        { ask: 'En la CAD, ¿por debajo de qué potasio se retrasa la insulina? (mEq/L)', answer: 3.5, tol: 0, unit: 'mEq/L', explain: 'ADA 2024: si K⁺ <3,5, reponer potasio y posponer la insulina.' },
        { ask: 'Límite superior normal del potasio sérico (mEq/L).', answer: 5.0, tol: 0.1, unit: 'mEq/L', explain: 'Rango 3,5–5,0 mEq/L (algunos laboratorios aceptan hasta 5,1–5,3).' },
      ],
      gen: { min: 2.0, max: 7.5, step: 0.1 },
      sources: ['ada2024'],
    },
    {
      id: 'cl',
      name: 'Cloro',
      abbr: 'Cl⁻',
      unit: 'mEq/L',
      low: 98,
      high: 106,
      decimals: 0,
      ref: '98–106',
      represents: 'El principal anión extracelular. Se usa para calcular el anion gap y para entender la acidosis hiperclorémica.',
      up: {
        meaning: 'Hipercloremia: suele acompañar a una acidosis metabólica con anion gap normal.',
        causes: ['Reposición abundante con suero salino al 0,9 %', 'Diarrea', 'Acidosis tubular renal', 'Fase de recuperación de la CAD (se pierden cetoaniones y se retiene cloro)'],
      },
      down: {
        meaning: 'Hipocloremia: suele acompañar a una alcalosis metabólica.',
        causes: ['Vómitos o aspiración nasogástrica', 'Diuréticos de asa o tiazídicos'],
      },
      importance: 'Si durante el tratamiento de la CAD el anion gap se normaliza pero el HCO₃⁻ sigue bajo, suele deberse a una acidosis hiperclorémica por el suero salino.',
      changes: 'Por este motivo el consenso de 2024 acepta cristaloides balanceados (Ringer lactato, Plasma-Lyte) como alternativa al salino.',
      topics: ['cad'],
      pearl: 'Una acidosis persistente con anion gap ya normal no significa que la CAD no se haya resuelto: suele ser **hiperclorémica** y benigna.',
      fill: [{ ask: 'Límite superior normal del cloro sérico (mEq/L).', answer: 106, tol: 1, unit: 'mEq/L', explain: 'Rango habitual 98–106 mEq/L.' }],
      gen: { min: 85, max: 125, step: 1 },
      sources: ['ada2024'],
    },
    {
      id: 'mg',
      name: 'Magnesio',
      abbr: 'Mg²⁺',
      unit: 'mg/dL',
      low: 1.7,
      high: 2.2,
      decimals: 1,
      ref: '1,7–2,2',
      units: 'mmol/L = mg/dL × 0,41.',
      represents: 'Catión intracelular, cofactor de ATPasas. El sérico es solo una pequeña fracción del total.',
      up: { meaning: 'Hipermagnesemia: hiporreflexia, hipotensión, depresión respiratoria.', causes: ['Insuficiencia renal con aportes de magnesio', 'Tratamiento con sulfato de magnesio'] },
      down: {
        meaning: 'Hipomagnesemia: arritmias, tetania; causa hipopotasemia refractaria e hipocalcemia.',
        causes: ['Diuresis osmótica', 'Alcoholismo, malnutrición', 'Diarrea', 'Inhibidores de la bomba de protones, diuréticos'],
      },
      importance: 'Si el potasio no sube a pesar de reponerlo, revisa el magnesio.',
      changes: 'Reponer magnesio para poder corregir el potasio y el calcio.',
      topics: ['cad', 'ehh'],
      pearl: 'Hipopotasemia **refractaria** → pide magnesio.',
      fill: [{ ask: 'Límite inferior normal del magnesio (mg/dL).', answer: 1.7, tol: 0.1, unit: 'mg/dL', explain: 'Rango orientativo 1,7–2,2 mg/dL.' }],
      gen: { min: 0.6, max: 4.5, step: 0.1 },
      sources: [],
    },
    {
      id: 'phos',
      name: 'Fósforo',
      abbr: 'P',
      unit: 'mg/dL',
      low: 2.5,
      high: 4.5,
      decimals: 1,
      ref: '2,5–4,5',
      represents: 'El fosfato sérico. Participa en el ATP y en el 2,3-DPG (liberación de oxígeno a los tejidos).',
      up: { meaning: 'Hiperfosfatemia.', causes: ['Insuficiencia renal', 'CAD al ingreso (sale de las células)', 'Lisis celular'] },
      down: {
        meaning: 'Hipofosfatemia: debilidad muscular, insuficiencia respiratoria, hemólisis, rabdomiólisis.',
        causes: ['Tratamiento de la CAD con insulina (entra en las células)', 'Síndrome de realimentación', 'Alcoholismo'],
      },
      importance: 'En la CAD el fósforo puede ser normal o alto al ingreso a pesar de un déficit corporal total, y cae con la insulina.',
      changes: 'La reposición rutinaria no mejora el pronóstico en la CAD; se repone si es <1,0 mg/dL o si hay disfunción cardíaca, respiratoria o hemólisis.',
      topics: ['cad'],
      pearl: 'Reponer fosfato en exceso puede causar **hipocalcemia**.',
      thresholds: [
        { kind: 'normal', value: '2,5–4,5 mg/dL', note: '' },
        { kind: 'terapeutico', value: '<1,0 mg/dL', note: 'Reponer en la CAD, o con debilidad respiratoria, disfunción cardíaca o hemólisis.' },
      ],
      fill: [{ ask: 'En la CAD, ¿por debajo de qué fósforo se aconseja reponer? (mg/dL)', answer: 1.0, tol: 0, unit: 'mg/dL', explain: 'Fosfato <1,0 mg/dL o complicaciones (debilidad respiratoria, disfunción cardíaca, hemólisis).' }],
      gen: { min: 0.5, max: 8, step: 0.1 },
      sources: ['ada2024'],
    },
    {
      id: 'ca',
      name: 'Calcio total',
      abbr: 'Ca',
      unit: 'mg/dL',
      low: 8.5,
      high: 10.5,
      decimals: 1,
      ref: '8,5–10,5',
      represents: 'El calcio total (≈40 % unido a albúmina). Si la albúmina está baja, hay que corregirlo o medir el calcio iónico.',
      up: { meaning: 'Hipercalcemia.', causes: ['Hiperparatiroidismo primario', 'Neoplasias', 'Tirotoxicosis (aumento del recambio óseo)', 'Inmovilización, tiazidas'] },
      down: { meaning: 'Hipocalcemia (una vez corregida por albúmina).', causes: ['Hipoalbuminemia (seudohipocalcemia)', 'Hipomagnesemia', 'Reposición de fosfato', 'Hipoparatiroidismo (por ejemplo, tras una tiroidectomía)'] },
      importance: 'La hipocalcemia tras una tiroidectomía por Graves es una complicación clásica.',
      changes: 'Calcio corregido = Ca medido + 0,8 × (4,0 − albúmina).',
      topics: ['hipertiroidismo'],
      pearl: 'Tras una tiroidectomía total, las **parestesias peribucales** obligan a medir el calcio.',
      critical: {
        stem: 'Paciente operado ayer de tiroidectomía total por Graves: parestesias peribucales, signo de Trousseau positivo y Ca de 6,8 mg/dL (albúmina normal). ¿Qué haces?',
        options: [
          { t: 'Gluconato cálcico IV y monitorizar el ECG', why: 'Correcto: hipocalcemia sintomática por hipoparatiroidismo tras la cirugía.' },
          { t: 'Calcio oral y control en una semana', why: 'Insuficiente con tetania.' },
          { t: 'Levotiroxina IV', why: 'No corrige la hipocalcemia.' },
          { t: 'Restricción de fósforo como única medida', why: 'No trata la urgencia.' },
        ],
        answer: 0,
        explain: ['Hipocalcemia con tetania → calcio IV.', 'La causa es el daño o la extirpación inadvertida de las paratiroides.', 'Después: calcio oral y calcitriol según la PTH.'],
      },
      gen: { min: 6, max: 14, step: 0.1 },
      sources: [],
    },
    {
      id: 'albumina',
      name: 'Albúmina',
      abbr: 'Albúmina',
      unit: 'g/dL',
      low: 3.5,
      high: 5.0,
      decimals: 1,
      ref: '3,5–5,0',
      represents: 'La principal proteína plasmática: aporta presión oncótica y cargas negativas (es un anión no medido).',
      up: { meaning: 'Casi siempre por hemoconcentración.', causes: ['Deshidratación'] },
      down: { meaning: 'Hipoalbuminemia.', causes: ['Inflamación aguda o crónica', 'Malnutrición', 'Cirrosis', 'Síndrome nefrótico'] },
      importance: 'Cada 1 g/dL que baja la albúmina, el anion gap baja ~2,5 mEq/L: una acidosis con AG alto puede pasar inadvertida.',
      changes: 'Corrige el anion gap y el calcio cuando la albúmina está baja.',
      topics: ['cad'],
      pearl: 'AG corregido = AG + 2,5 × (4,0 − albúmina).',
      fill: [{ ask: '¿Cuántos mEq/L baja el anion gap por cada 1 g/dL que baja la albúmina?', answer: 2.5, tol: 0, unit: 'mEq/L', explain: 'Corrección habitual: 2,5 mEq/L por cada g/dL (algunos textos usan 2,3–2,5).' }],
      gen: { min: 1.5, max: 5.8, step: 0.1 },
      sources: ['acidbase'],
    },
  ],
);
