/* Valores: gasometría y equilibrio ácido-base. */
SolMed.registry.addValues(
  { id: 'gasometria', name: 'Gasometría y ácido-base', desc: 'pH, PaCO₂, HCO₃⁻, PaO₂, anion gap y lactato.' },
  [
    {
      id: 'ph',
      name: 'pH',
      abbr: 'pH',
      unit: '',
      low: 7.35,
      high: 7.45,
      decimals: 2,
      ref: '7,35–7,45',
      represents: 'La acidez de la sangre (−log [H⁺]). Resulta del cociente HCO₃⁻/PaCO₂ (Henderson-Hasselbalch).',
      up: { meaning: 'Alcalemia.', causes: ['Alcalosis respiratoria (hiperventilación)', 'Alcalosis metabólica (vómitos, diuréticos)'] },
      down: {
        meaning: 'Acidemia.',
        causes: ['Acidosis metabólica: CAD, acidosis láctica, insuficiencia renal, tóxicos, diarrea', 'Acidosis respiratoria: hipoventilación'],
      },
      importance: 'En la CAD, un pH <7,3 (o un HCO₃⁻ <18) es criterio diagnóstico, y su valor gradúa la gravedad.',
      changes: 'Bicarbonato solo si pH <7,0 (ADA 2024; el consenso de 2009 usaba <6,9). La resolución exige pH ≥7,3 o HCO₃⁻ ≥18, con β-OHB <0,6.',
      topics: ['cad', 'ehh'],
      pearl: 'En la CAD basta el **pH venoso**: difiere del arterial en ~0,02–0,03 y evita punciones arteriales repetidas.',
      thresholds: [
        { kind: 'normal', value: '7,35–7,45', note: '' },
        { kind: 'diagnostico', value: '<7,30', note: 'Criterio de acidosis de la CAD (ADA 2024), o HCO₃⁻ <18.' },
        { kind: 'terapeutico', value: '<7,00', note: 'Considerar bicarbonato en la CAD (ADA 2024).' },
        { kind: 'meta', value: '≥7,30', note: 'Criterio de resolución de la CAD (con β-OHB <0,6).' },
        { kind: 'critico', value: '<7,20 o >7,60', note: 'Valores de aviso habituales; varían por institución.' },
      ],
      critical: {
        stem: 'CAD con pH 6,92, HCO₃⁻ 4 mEq/L y K⁺ 4,6 mEq/L tras la primera hora de líquidos. ¿Qué indica el consenso de 2024 sobre el bicarbonato?',
        options: [
          { t: 'Puede considerarse porque el pH es <7,0', why: 'Correcto: el consenso de 2024 limita el bicarbonato a la acidosis grave con pH <7,0, vigilando el potasio.' },
          { t: 'Está contraindicado en cualquier CAD', why: 'Con pH <7,0 puede considerarse.' },
          { t: 'Debe darse siempre que el pH sea <7,2', why: 'Por encima de 7,0 no aporta beneficio y tiene riesgos (hipopotasemia, alcalosis de rebote).' },
          { t: 'Sustituye a la insulina en la acidosis grave', why: 'La insulina es la que detiene la cetogénesis.' },
        ],
        answer: 0,
        explain: ['Umbral actual: pH <7,0 (2024).', 'El bicarbonato favorece la hipopotasemia: vigila y repón el K⁺.', 'Nunca sustituye a los líquidos ni a la insulina.'],
      },
      fill: [
        { ask: 'pH por debajo del cual el consenso de 2024 considera administrar bicarbonato en la CAD.', answer: 7.0, tol: 0, unit: '', explain: 'pH <7,0 (en 2009 era <6,9).' },
        { ask: 'Criterio de pH para el diagnóstico de CAD (menor que…).', answer: 7.3, tol: 0, unit: '', explain: 'pH <7,3 y/o HCO₃⁻ <18 mEq/L.' },
      ],
      gen: { min: 6.8, max: 7.7, step: 0.01 },
      sources: ['ada2024', 'ada2009'],
    },
    {
      id: 'paco2',
      name: 'Presión arterial de CO₂',
      abbr: 'PaCO₂',
      unit: 'mmHg',
      low: 35,
      high: 45,
      decimals: 0,
      ref: '35–45',
      represents: 'El componente respiratorio del equilibrio ácido-base: depende de la ventilación alveolar.',
      up: { meaning: 'Hipercapnia: hipoventilación (acidosis respiratoria) o compensación de una alcalosis metabólica.', causes: ['Depresión respiratoria, EPOC', 'Coma mixedematoso (hipoventilación)', 'Compensación de la alcalosis metabólica'] },
      down: { meaning: 'Hipocapnia: hiperventilación.', causes: ['Compensación de una acidosis metabólica (respiración de Kussmaul)', 'Ansiedad, sepsis, embolia pulmonar, embarazo'] },
      importance: 'En la acidosis metabólica, compara la PaCO₂ con la esperada según la fórmula de Winter para detectar un trastorno respiratorio asociado.',
      changes: 'Si la PaCO₂ es mayor que la esperada, hay una acidosis respiratoria añadida (por ejemplo, fatiga, sedación o neumonía): valorar el soporte ventilatorio.',
      topics: ['cad', 'hipotiroidismo'],
      pearl: 'PaCO₂ esperada = 1,5 × HCO₃⁻ + 8 ± 2. Una PaCO₂ «normal» en una acidosis metabólica grave es **patológica**.',
      fill: [{ ask: 'Límite superior normal de la PaCO₂ (mmHg).', answer: 45, tol: 0, unit: 'mmHg', explain: 'Rango 35–45 mmHg.' }],
      gen: { min: 12, max: 80, step: 1 },
      sources: ['acidbase'],
    },
    {
      id: 'hco3',
      name: 'Bicarbonato',
      abbr: 'HCO₃⁻',
      unit: 'mEq/L',
      low: 22,
      high: 28,
      decimals: 0,
      ref: '22–28',
      units: 'En gasometría arterial suele informarse 22–26 mEq/L (calculado); en bioquímica, CO₂ total 22–29.',
      represents: 'El componente metabólico: el principal tampón extracelular.',
      up: { meaning: 'Alcalosis metabólica o compensación de una acidosis respiratoria crónica.', causes: ['Vómitos', 'Diuréticos', 'Hipercapnia crónica'] },
      down: {
        meaning: 'Acidosis metabólica (o compensación de una alcalosis respiratoria).',
        causes: ['CAD (consumo por cetoácidos)', 'Acidosis láctica', 'Insuficiencia renal', 'Diarrea (AG normal)', 'Acidosis tubular renal'],
      },
      importance: 'Criterio diagnóstico y de resolución de la CAD, y criterio del EHH (≥15 mEq/L en el EHH).',
      changes: 'CAD: HCO₃⁻ <18. Resolución: ≥18 (o pH ≥7,3) con β-OHB <0,6. EHH: HCO₃⁻ ≥15.',
      topics: ['cad', 'ehh'],
      pearl: 'El EHH puede tener un HCO₃⁻ algo bajo (15–18) por acidosis láctica o prerrenal **sin** ser una CAD: fíjate en el β-OHB.',
      thresholds: [
        { kind: 'normal', value: '22–28 mEq/L', note: '' },
        { kind: 'diagnostico', value: '<18 mEq/L', note: 'Criterio de CAD (ADA 2024), junto con el pH.' },
        { kind: 'diagnostico', value: '≥15 mEq/L', note: 'Criterio del EHH (ausencia de acidosis significativa).' },
        { kind: 'meta', value: '≥18 mEq/L', note: 'Criterio de resolución de la CAD (o pH ≥7,3).' },
      ],
      fill: [{ ask: 'HCO₃⁻ por debajo del cual se cumple el criterio de acidosis de la CAD (mEq/L).', answer: 18, tol: 0, unit: 'mEq/L', explain: 'HCO₃⁻ <18 y/o pH <7,3.' }],
      gen: { min: 3, max: 45, step: 1 },
      sources: ['ada2024'],
    },
    {
      id: 'pao2',
      name: 'Presión arterial de O₂',
      abbr: 'PaO₂',
      unit: 'mmHg',
      low: 80,
      high: 100,
      oneSided: 'low',
      decimals: 0,
      ref: '80–100 (aire ambiente, nivel del mar)',
      represents: 'La oxigenación arterial. Disminuye con la edad y la altitud.',
      down: { meaning: 'Hipoxemia.', causes: ['Neumonía, edema pulmonar (incluido el neurogénico en la HSA)', 'Hipoventilación (coma mixedematoso)', 'Embolia pulmonar'] },
      up: { meaning: 'Hiperoxemia por oxígeno suplementario.', causes: ['Oxigenoterapia'] },
      importance: 'Solo es pertinente cuando hay sospecha de alteración respiratoria. Para el pH y el HCO₃⁻ en la CAD basta una gasometría venosa.',
      changes: 'Si se necesita valorar la oxigenación o la ventilación, pide gasometría arterial.',
      topics: ['hsa', 'hipotiroidismo'],
      pearl: 'La gasometría venosa no informa de la oxigenación: para eso, pulsioximetría o gasometría arterial.',
      gen: { min: 40, max: 79, step: 1, nmin: 80, nmax: 100 },
      sources: [],
    },
    {
      id: 'ag',
      name: 'Anion gap',
      abbr: 'AG',
      unit: 'mEq/L',
      low: 8,
      high: 12,
      decimals: 0,
      ref: '8–12',
      units: 'Calculado sin potasio. Con analizadores de electrodo selectivo modernos el rango puede ser menor (≈3–11): usa el de tu laboratorio.',
      represents: 'La diferencia entre cationes y aniones medidos: Na⁺ − (Cl⁻ + HCO₃⁻). Representa aniones no medidos (sobre todo albúmina).',
      up: {
        meaning: 'Acidosis metabólica con anion gap elevado: se acumula un ácido con su anión.',
        causes: ['Cetoacidosis (diabética, alcohólica, de ayuno)', 'Acidosis láctica (shock, sepsis, metformina)', 'Insuficiencia renal avanzada', 'Tóxicos: metanol, etilenglicol, salicilatos'],
        action: 'Calcular el delta-delta para buscar trastornos mixtos.',
      },
      down: { meaning: 'Anion gap bajo.', causes: ['Hipoalbuminemia (la más frecuente)', 'Mieloma con IgG catiónica', 'Litio, bromuro'] },
      importance: 'Distingue la acidosis por cetoácidos (AG alto) de la hiperclorémica (AG normal), que aparece durante la recuperación de la CAD.',
      changes: 'El consenso de 2024 ya no usa el anion gap como criterio diagnóstico de la CAD (usa β-OHB, pH y HCO₃⁻), pero sigue siendo útil para interpretar la acidosis.',
      topics: ['cad', 'ehh'],
      pearl: 'Corrige por albúmina: con 2,0 g/dL de albúmina, un AG «normal» de 12 equivale a ~17.',
      thresholds: [
        { kind: 'normal', value: '8–12 mEq/L', note: 'Varía según el analizador.' },
        { kind: 'diagnostico', value: '>10–12 mEq/L', note: 'Criterio de CAD en el consenso de 2009 (ya no en 2024).' },
      ],
      fill: [{ ask: 'Límite superior normal clásico del anion gap (mEq/L).', answer: 12, tol: 0, unit: 'mEq/L', explain: 'Clásicamente 8–12 mEq/L (depende del laboratorio).' }],
      gen: { min: 2, max: 40, step: 1 },
      sources: ['acidbase', 'ada2024', 'ada2009'],
    },
    {
      id: 'lactato',
      name: 'Lactato',
      abbr: 'Lactato',
      unit: 'mmol/L',
      low: 0.5,
      high: 2.0,
      oneSided: 'high',
      decimals: 1,
      ref: '0,5–2,0',
      represents: 'Producto del metabolismo anaerobio de la glucosa y marcador de hipoperfusión tisular.',
      up: {
        meaning: 'Hiperlactatemia: hipoperfusión (tipo A) o causas sin hipoxia (tipo B).',
        causes: ['Shock, sepsis', 'Hipovolemia grave (CAD, EHH)', 'Metformina, alcohol, insuficiencia hepática', 'Convulsiones'],
      },
      importance: 'En la CAD, un lactato alto sugiere hipoperfusión o sepsis asociada. En el EHH explica un HCO₃⁻ algo bajo sin cetosis.',
      changes: 'Busca y trata la causa de la hipoperfusión (infección, isquemia mesentérica).',
      topics: ['cad', 'ehh'],
      pearl: 'Un anion gap alto con β-OHB bajo en un paciente hiperglucémico orienta a **acidosis láctica**, no a CAD.',
      gen: { min: 0.3, max: 12, step: 0.1, nmin: 0.5, nmax: 1.9 },
      sources: [],
    },
  ],
);
