/* Valores: metabolismo, glucosa y cetonas.
 * Rangos orientativos para adultos. Varían según laboratorio, método,
 * unidades y población. */
SolMed.registry.addValues(
  { id: 'metabolismo', name: 'Metabolismo y cetonas', desc: 'Glucosa, cetonas y osmolalidad: el núcleo de las crisis hiperglucémicas.' },
  [
    {
      id: 'glucosa',
      name: 'Glucosa plasmática',
      abbr: 'Glucosa',
      unit: 'mg/dL',
      low: 70,
      high: 99,
      decimals: 0,
      ref: '70–99 (ayunas)',
      units: 'mmol/L = mg/dL ÷ 18. Una glucosa al azar hasta ~140 mg/dL puede ser normal fuera del ayuno.',
      represents: 'La concentración de glucosa en plasma: resultado del balance entre ingesta, producción hepática (glucogenólisis y gluconeogénesis) y captación periférica dependiente de insulina.',
      up: {
        meaning: 'Hiperglucemia: déficit absoluto o relativo de insulina, o exceso de hormonas contrarreguladoras.',
        causes: ['Diabetes mellitus (tipo 1, tipo 2, otras)', 'Estrés agudo: infección, infarto, cirugía', 'Glucocorticoides, tiazidas, antipsicóticos atípicos', 'Crisis hiperglucémicas: CAD y EHH', 'Pancreatitis, Cushing, feocromocitoma, acromegalia'],
        action: 'Confirmar en plasma; buscar cetonas y calcular osmolalidad si es muy alta o hay síntomas.',
      },
      down: {
        meaning: 'Hipoglucemia (<70 mg/dL): exceso de insulina o de secretagogos, falta de sustrato o fallo de la contrarregulación.',
        causes: ['Insulina o sulfonilureas (la más frecuente)', 'Alcohol con ayuno', 'Insuficiencia hepática o renal, sepsis', 'Insuficiencia suprarrenal', 'Insulinoma (raro)'],
        action: 'Tratar de inmediato: 15–20 g de glucosa oral si puede tragar; si no, dextrosa IV (o glucagón).',
      },
      importance: 'Es el primer dato de las crisis hiperglucémicas, pero **su magnitud no define la gravedad**: una CAD puede cursar con glucosa casi normal (CAD euglucémica con iSGLT2).',
      changes: 'En la CAD, cuando baja de 250 mg/dL se añade dextrosa y se mantiene la insulina hasta cerrar la cetosis; en el EHH la dextrosa se añade con glucosa <300 mg/dL.',
      topics: ['cad', 'ehh'],
      pearl: 'En la CAD la insulina se mantiene para **eliminar las cetonas**, no para normalizar la glucosa: si la glucosa baja, se añade dextrosa en lugar de suspender la insulina.',
      thresholds: [
        { kind: 'normal', value: '70–99 mg/dL', note: 'En ayunas.' },
        { kind: 'diagnostico', value: '≥126 mg/dL', note: 'Ayunas: criterio de diabetes (repetido o con otro criterio). 100–125: glucosa alterada en ayunas.' },
        { kind: 'diagnostico', value: '≥200 mg/dL', note: 'Al azar con síntomas, o a las 2 h de la SOG: diabetes. También es el umbral de glucosa de la CAD (ADA 2024), que además se cumple con diabetes conocida aunque la glucosa sea menor.' },
        { kind: 'diagnostico', value: '≥600 mg/dL', note: 'Criterio de glucosa del EHH (ADA 2024).' },
        { kind: 'terapeutico', value: '<250 mg/dL (CAD) · <300 mg/dL (EHH)', note: 'Añadir dextrosa a los líquidos sin suspender la insulina.' },
        { kind: 'critico', value: '<54 mg/dL', note: 'Hipoglucemia de nivel 2 (clínicamente significativa). Muchos laboratorios avisan por debajo de 40–50 o por encima de 450–500 mg/dL.' },
      ],
      critical: {
        stem: 'Glucemia capilar de 42 mg/dL en un paciente con insulina, sudoroso y somnoliento, que no puede tragar con seguridad. ¿Qué haces primero?',
        options: [
          { t: 'Dextrosa IV (por ejemplo, 25 g) y nueva glucemia en 15 minutos', why: 'Correcto: hipoglucemia de nivel 2 con alteración de conciencia. Si no hay acceso IV, glucagón IM/SC o intranasal.' },
          { t: 'Repetir la glucemia en una hora', why: 'Retrasa el tratamiento de una urgencia que puede causar convulsiones o daño neurológico.' },
          { t: 'Pedir HbA1c y ajustar la pauta de insulina', why: 'Es útil después, no en la fase aguda.' },
          { t: 'Zumo de fruta por boca', why: 'Contraindicado si no puede tragar con seguridad: riesgo de aspiración.' },
        ],
        answer: 0,
        explain: ['Glucosa <54 mg/dL = hipoglucemia de nivel 2; con alteración de conciencia es de nivel 3 (grave).', 'Si no puede tragar: dextrosa IV o glucagón.', 'Recontrolar a los 15 minutos y buscar la causa (dosis, ingesta, función renal, sulfonilureas de acción larga).'],
      },
      fill: [
        { ask: 'Umbral de glucosa en ayunas para el diagnóstico de diabetes (mg/dL).', answer: 126, tol: 0, unit: 'mg/dL', explain: 'Ayunas ≥126 mg/dL; 100–125 es glucosa alterada en ayunas.' },
        { ask: 'Criterio de glucosa del EHH según el consenso de 2024 (mg/dL).', answer: 600, tol: 0, unit: 'mg/dL', explain: 'EHH: glucosa ≥600 mg/dL, osmolalidad efectiva >300 (o total >320), β-OHB <3,0 y sin acidosis significativa.' },
        { ask: 'En la CAD, ¿por debajo de qué glucosa se añade dextrosa a los líquidos? (mg/dL)', answer: 250, tol: 0, unit: 'mg/dL', explain: 'Con glucosa <250 mg/dL se añade dextrosa (5–10 %) y se mantiene la insulina hasta que se resuelva la cetoacidosis.' },
      ],
      gen: { min: 30, max: 900, step: 1 },
      sources: ['ada2024'],
    },
    {
      id: 'hba1c',
      name: 'Hemoglobina glucosilada',
      abbr: 'HbA1c',
      unit: '%',
      low: 4.0,
      high: 5.6,
      decimals: 1,
      ref: '4,0–5,6',
      represents: 'La fracción de hemoglobina glucosilada: refleja la glucemia media de los ~2–3 meses previos (vida media del eritrocito).',
      up: {
        meaning: 'Hiperglucemia crónica.',
        causes: ['Diabetes (≥6,5 %)', 'Prediabetes (5,7–6,4 %)', 'Falsamente alta: ferropenia, asplenia'],
        action: 'Confirmar con una segunda prueba si no hay hiperglucemia inequívoca.',
      },
      down: {
        meaning: 'Rara vez importante; suele deberse a menor supervivencia de los eritrocitos.',
        causes: ['Hemólisis, hemorragia reciente', 'Transfusión reciente, embarazo', 'Tratamiento con eritropoyetina'],
      },
      importance: 'En una crisis hiperglucémica distingue una diabetes de larga evolución mal controlada de un debut.',
      changes: 'Una HbA1c alta en una primera crisis orienta a diabetes previa no diagnosticada; no cambia el tratamiento agudo.',
      topics: ['cad', 'ehh'],
      pearl: 'La HbA1c **no sirve** cuando la vida media eritrocitaria está alterada (hemólisis, transfusión, embarazo): ahí manda la glucosa.',
      thresholds: [
        { kind: 'normal', value: '<5,7 %', note: '' },
        { kind: 'diagnostico', value: '5,7–6,4 %', note: 'Prediabetes.' },
        { kind: 'diagnostico', value: '≥6,5 %', note: 'Diabetes (método certificado; confirmar si no hay hiperglucemia inequívoca).' },
      ],
      fill: [{ ask: 'HbA1c a partir de la cual se diagnostica diabetes (%).', answer: 6.5, tol: 0, unit: '%', explain: 'HbA1c ≥6,5 %; prediabetes 5,7–6,4 %.' }],
      gen: { min: 3.5, max: 14, step: 0.1, nmin: 4.2, nmax: 5.6 },
      sources: ['ada2024'],
    },
    {
      id: 'bohb',
      name: 'β-hidroxibutirato',
      abbr: 'β-OHB',
      unit: 'mmol/L',
      low: 0,
      high: 0.6,
      oneSided: 'high',
      decimals: 1,
      ref: '<0,6',
      represents: 'El principal cuerpo cetónico en sangre en la cetoacidosis (≈3:1 respecto al acetoacetato). Se forma por oxidación hepática de ácidos grasos cuando falta insulina y sobra glucagón.',
      up: {
        meaning: 'Cetosis; ≥3,0 mmol/L es el umbral de cetonemia de la CAD (2024).',
        causes: ['Cetoacidosis diabética (incluida la euglucémica por iSGLT2)', 'Cetoacidosis alcohólica', 'Ayuno prolongado y dieta cetogénica (cetosis leve)', 'Embarazo con vómitos, hiperémesis'],
        action: '0,6–1,5: vigilar; 1,5–3,0: riesgo de CAD; ≥3,0 con acidosis: CAD.',
      },
      importance: 'Es la prueba recomendada para diagnosticar la CAD, clasificar su gravedad y **decidir su resolución** (<0,6 mmol/L).',
      changes: 'Guía el final de la infusión de insulina: se mantiene hasta que el β-OHB es <0,6 y el pH ≥7,3 o el HCO₃⁻ ≥18.',
      topics: ['cad', 'ehh'],
      pearl: 'Las tiras de orina con nitroprusiato detectan acetoacetato, **no β-OHB**: al tratar la CAD el β-OHB pasa a acetoacetato y la cetonuria puede aumentar aunque el paciente mejore.',
      thresholds: [
        { kind: 'normal', value: '<0,6 mmol/L', note: 'También es la meta de resolución de la CAD.' },
        { kind: 'diagnostico', value: '≥3,0 mmol/L', note: 'Criterio de cetonemia de la CAD (ADA 2024). En el EHH el β-OHB debe ser <3,0.' },
        { kind: 'meta', value: '<0,6 mmol/L', note: 'Uno de los criterios de resolución de la CAD.' },
      ],
      fill: [
        { ask: 'Cetonemia (β-OHB) mínima para cumplir el criterio de CAD de 2024 (mmol/L).', answer: 3.0, tol: 0, unit: 'mmol/L', explain: 'β-OHB ≥3,0 mmol/L, o cetonuria ≥2+.' },
        { ask: 'β-OHB por debajo del cual se considera resuelta la cetosis de la CAD (mmol/L).', answer: 0.6, tol: 0, unit: 'mmol/L', explain: 'Resolución: β-OHB <0,6 mmol/L y pH ≥7,3 o HCO₃⁻ ≥18.' },
      ],
      gen: { max: 9, step: 0.1, nmin: 0, nmax: 0.5 },
      sources: ['ada2024'],
    },
    {
      id: 'cetonuria',
      name: 'Cetonas en orina',
      abbr: 'Cetonuria',
      unit: '',
      ref: 'Negativa',
      represents: 'Tira reactiva con nitroprusiato: detecta acetoacetato (y acetona), no β-hidroxibutirato.',
      up: {
        meaning: 'Cetosis. Cetonuria ≥2+ es alternativa al β-OHB en el criterio de CAD cuando no se dispone de cetonemia.',
        causes: ['CAD', 'Ayuno, vómitos, hiperémesis', 'Cetoacidosis alcohólica (puede infraestimarse por predominio de β-OHB)'],
      },
      importance: 'Es útil para el cribado, pero es poco fiable para seguir el tratamiento.',
      changes: 'No se usa para decidir el fin de la insulina: para eso sirve el β-OHB en sangre.',
      topics: ['cad', 'ehh'],
      pearl: 'Una cetonuria que **aumenta** durante el tratamiento puede significar mejoría (conversión de β-OHB en acetoacetato).',
      sources: ['ada2024'],
    },
    {
      id: 'osm',
      name: 'Osmolalidad sérica (medida)',
      abbr: 'Osm',
      unit: 'mOsm/kg',
      low: 275,
      high: 295,
      decimals: 0,
      ref: '275–295',
      represents: 'La concentración total de partículas osmóticamente activas en el suero, medida por osmómetro (descenso del punto de congelación).',
      up: {
        meaning: 'Hiperosmolalidad: exceso de solutos o déficit de agua.',
        causes: ['Hiperglucemia (EHH)', 'Hipernatremia', 'Urea elevada (no efectiva)', 'Alcoholes tóxicos: metanol, etilenglicol (gap osmolar)', 'Manitol'],
        action: 'Calcular la osmolalidad efectiva y el gap osmolar.',
      },
      down: {
        meaning: 'Hipoosmolalidad: casi siempre por hiponatremia hipotónica.',
        causes: ['SIADH', 'Hipovolemia con reposición hipotónica', 'Insuficiencia cardíaca, cirrosis', 'Polidipsia primaria'],
      },
      importance: 'La alteración de conciencia en las crisis hiperglucémicas se correlaciona con la osmolalidad efectiva, sobre todo por encima de ~320 mOsm/kg.',
      changes: 'Si un paciente con hiperglucemia está en coma con osmolalidad efectiva <320, busca otra causa del coma.',
      topics: ['ehh', 'cad'],
      pearl: 'Gap osmolar = medida − calculada; un gap >10 sugiere solutos no medidos (alcoholes tóxicos).',
      thresholds: [
        { kind: 'normal', value: '275–295 mOsm/kg', note: '' },
        { kind: 'diagnostico', value: '>320 mOsm/kg', note: 'Osmolalidad total que cumple el criterio de EHH de 2024 (alternativa a la efectiva >300).' },
      ],
      fill: [{ ask: 'Osmolalidad sérica total por encima de la cual se cumple el criterio de EHH de 2024 (mOsm/kg).', answer: 320, tol: 0, unit: 'mOsm/kg', explain: 'EHH 2024: efectiva >300 o total >320 mOsm/kg.' }],
      gen: { min: 240, max: 400, step: 1 },
      sources: ['ada2024'],
    },
    {
      id: 'osmef',
      name: 'Osmolalidad efectiva (calculada)',
      abbr: 'Osm efectiva',
      unit: 'mOsm/kg',
      low: 275,
      high: 295,
      decimals: 0,
      ref: '≈275–295',
      represents: 'La tonicidad: solutos que no cruzan libremente la membrana celular y desplazan agua (sodio y glucosa). Se calcula como 2 × Na⁺ + glucosa/18; la urea no cuenta.',
      up: {
        meaning: 'Hipertonicidad: el agua sale de las células, incluidas las neuronas.',
        causes: ['EHH', 'Hipernatremia por pérdida de agua libre', 'CAD con deshidratación marcada'],
      },
      down: { meaning: 'Hipotonicidad: el agua entra en las células.', causes: ['Hiponatremia hipotónica'] },
      importance: 'Es el criterio osmolar del EHH y se relaciona con el nivel de conciencia.',
      changes: 'Durante el tratamiento del EHH conviene que baje de forma gradual (≈3–8 mOsm/kg/h según JBDS) para reducir el riesgo de edema cerebral.',
      topics: ['ehh', 'cad'],
      pearl: 'La urea eleva la osmolalidad **total** pero no la **efectiva**: cruza las membranas y no provoca desplazamiento de agua.',
      thresholds: [
        { kind: 'diagnostico', value: '>300 mOsm/kg', note: 'Criterio de EHH de 2024 (en 2009 el umbral era >320).' },
        { kind: 'meta', value: 'Descenso ≈3–8 mOsm/kg/h', note: 'Meta de descenso durante el tratamiento del EHH (JBDS).' },
      ],
      fill: [{ ask: 'Osmolalidad efectiva por encima de la cual se cumple el criterio de EHH de 2024 (mOsm/kg).', answer: 300, tol: 0, unit: 'mOsm/kg', explain: 'Efectiva >300 (2024). El consenso de 2009 usaba >320.' }],
      gen: { min: 240, max: 400, step: 1 },
      sources: ['ada2024', 'jbds'],
    },
  ],
);
