/* Valores: neurología y hemorragia subaracnoidea. Solo parámetros que
 * cambian el diagnóstico o la conducta. */
SolMed.registry.addValues(
  { id: 'neuro', name: 'Neurología y HSA', desc: 'Líquido cefalorraquídeo, escalas y monitorización del vasoespasmo.' },
  [
    {
      id: 'gcs',
      name: 'Escala de coma de Glasgow',
      abbr: 'GCS',
      unit: 'puntos',
      low: 15,
      high: 15,
      oneSided: 'low',
      decimals: 0,
      ref: '15 (rango de la escala 3–15)',
      represents: 'La suma de apertura ocular (1–4), respuesta verbal (1–5) y respuesta motora (1–6).',
      down: {
        meaning: 'Alteración del nivel de conciencia; ≤8 suele implicar incapacidad para proteger la vía aérea.',
        causes: ['HSA de alto grado, hidrocefalia aguda, resangrado', 'Hiperosmolalidad (EHH)', 'Coma mixedematoso', 'Hipoglucemia'],
        action: 'Valorar la vía aérea; buscar causas reversibles (glucosa, hidrocefalia, convulsiones).',
      },
      importance: 'En la HSA, el GCS forma la escala WFNS, que junto a Hunt y Hess gradúa la gravedad y el pronóstico.',
      changes: 'Un **descenso** del GCS tras la HSA exige TC urgente para descartar resangrado o hidrocefalia, o valorar isquemia cerebral tardía.',
      topics: ['hsa', 'ehh', 'hipotiroidismo'],
      pearl: 'Un deterioro brusco en las primeras horas es resangrado o hidrocefalia; entre los días 3 y 14, piensa en isquemia cerebral tardía.',
      thresholds: [
        { kind: 'normal', value: '15', note: '' },
        { kind: 'critico', value: '≤8', note: 'Considerar intubación para proteger la vía aérea.' },
      ],
      critical: {
        stem: 'Día 1 de una HSA (Hunt y Hess II). El GCS baja de 14 a 9 en 30 minutos, con pupilas simétricas. ¿Qué es lo primero?',
        options: [
          { t: 'Asegurar la vía aérea si hace falta y TC craneal urgente (resangrado o hidrocefalia aguda)', why: 'Correcto: deterioro brusco precoz = resangrado o hidrocefalia hasta demostrar lo contrario.' },
          { t: 'Aumentar la dosis de nimodipino', why: 'No trata la causa probable y puede causar hipotensión.' },
          { t: 'Esperar al día 4 para un Doppler transcraneal', why: 'Retrasa el diagnóstico de una complicación que requiere actuar ya.' },
          { t: 'Restringir líquidos por posible SIADH', why: 'No explica un deterioro brusco y la hipovolemia es perjudicial en la HSA.' },
        ],
        answer: 0,
        explain: ['Primeras 24 h: máximo riesgo de resangrado.', 'La hidrocefalia aguda se trata con drenaje ventricular externo.', 'La isquemia tardía es más típica entre los días 3 y 14.'],
      },
      gen: { min: 3, max: 14, step: 1, nmin: 15, nmax: 15 },
      sources: ['aha2023'],
    },
    {
      id: 'xanto',
      name: 'Xantocromía del LCR',
      abbr: 'Xantocromía',
      unit: '',
      ref: 'Ausente',
      represents: 'Coloración amarillenta del sobrenadante del LCR por bilirrubina y oxihemoglobina de hematíes degradados en el espacio subaracnoideo.',
      up: {
        meaning: 'Presente: sangre en el LCR desde hace varias horas → apoya una HSA verdadera frente a una punción traumática.',
        causes: ['HSA (aparece a partir de ~2–12 h y persiste unas 2 semanas)', 'Hiperbilirrubinemia marcada, proteínas muy elevadas (falsos positivos)'],
      },
      importance: 'Es la prueba clave cuando la TC es negativa y persiste la sospecha de HSA.',
      changes: 'Presente → angio-TC o arteriografía para buscar el aneurisma.',
      topics: ['hsa'],
      pearl: 'La punción lumbar rinde más **≥12 h** después del inicio: antes puede no haber xantocromía todavía.',
      sources: ['perry', 'aha2023'],
    },
    {
      id: 'lcrhem',
      name: 'Hematíes en LCR',
      abbr: 'Hematíes LCR',
      unit: '/µL',
      low: 0,
      high: 5,
      oneSided: 'high',
      decimals: 0,
      ref: '0–5',
      represents: 'Recuento de eritrocitos en el LCR.',
      up: {
        meaning: 'Sangre en el LCR: HSA o punción traumática.',
        causes: ['HSA: recuento alto y constante del tubo 1 al 4', 'Punción traumática: el recuento **disminuye** del tubo 1 al 4 y no hay xantocromía'],
      },
      importance: 'El descenso entre tubos sugiere una punción traumática, pero no la confirma: la xantocromía es más fiable.',
      changes: 'Recuento persistente o xantocromía → estudio vascular.',
      topics: ['hsa'],
      pearl: 'Un recuento que no disminuye entre el primer y el último tubo es más sugestivo de HSA.',
      gen: { min: 0, max: 50000, step: 10, nmin: 0, nmax: 4 },
      sources: ['aha2023'],
    },
    {
      id: 'lcrpres',
      name: 'Presión de apertura del LCR',
      abbr: 'Presión de apertura',
      unit: 'cm H₂O',
      low: 10,
      high: 20,
      decimals: 0,
      ref: '10–20 (hasta ~25 en obesos)',
      represents: 'La presión del LCR medida con el paciente en decúbito lateral durante la punción lumbar.',
      up: { meaning: 'Hipertensión intracraneal.', causes: ['HSA, hidrocefalia', 'Trombosis venosa cerebral', 'Hipertensión intracraneal idiopática', 'Meningitis'] },
      down: { meaning: 'Hipotensión del LCR.', causes: ['Hipotensión intracraneal espontánea (fístula de LCR)', 'Punción lumbar reciente'] },
      importance: 'Una presión baja con cefalea ortostática orienta a hipotensión intracraneal, un diagnóstico diferencial de la cefalea aguda.',
      changes: 'Presión alta con TC normal: piensa también en trombosis venosa cerebral.',
      topics: ['hsa'],
      pearl: 'Cefalea que **mejora al acostarse** + presión baja = hipotensión intracraneal espontánea.',
      gen: { min: 3, max: 45, step: 1 },
      sources: [],
    },
    {
      id: 'dtc',
      name: 'Velocidad media en la arteria cerebral media (Doppler transcraneal)',
      abbr: 'Vm ACM (DTC)',
      unit: 'cm/s',
      low: 30,
      high: 120,
      oneSided: 'high',
      decimals: 0,
      ref: '<120 en contexto de HSA (normal ≈50–80)',
      represents: 'Velocidad del flujo en la ACM: aumenta cuando la luz arterial se estrecha (vasoespasmo) o cuando aumenta el flujo (hiperemia).',
      up: {
        meaning: '>120 cm/s sugiere vasoespasmo; >200 cm/s, vasoespasmo grave. El índice de Lindegaard (ACM/carótida interna extracraneal) >3 distingue el vasoespasmo de la hiperemia.',
        causes: ['Vasoespasmo tras la HSA (máximo entre los días 4 y 14)', 'Hiperemia, anemia, fiebre (índice de Lindegaard <3)'],
      },
      importance: 'Permite vigilar el vasoespasmo sin procedimientos invasivos, junto con la exploración neurológica seriada.',
      changes: 'El aumento de velocidades o un déficit nuevo llevan a angio-TC o TC de perfusión y a tratar la isquemia tardía (euvolemia, elevar la PA, terapia endovascular).',
      topics: ['hsa'],
      pearl: 'El **vasoespasmo angiográfico** es frecuente; la **isquemia cerebral tardía** (clínica) es lo que importa.',
      gen: { min: 30, max: 250, step: 1, nmin: 45, nmax: 110 },
      sources: ['aha2023'],
    },
  ],
);
