/* Valores: función renal. */
SolMed.registry.addValues(
  { id: 'renal', name: 'Función renal', desc: 'Creatinina, BUN/urea y filtrado glomerular.' },
  [
    {
      id: 'creat',
      name: 'Creatinina sérica',
      abbr: 'Creatinina',
      unit: 'mg/dL',
      low: 0.6,
      high: 1.2,
      decimals: 1,
      ref: '0,6–1,2',
      units: 'µmol/L = mg/dL × 88,4. Depende de la masa muscular, la edad y el sexo.',
      represents: 'Producto del metabolismo muscular que se filtra en el glomérulo. Aproxima el filtrado glomerular cuando está estable.',
      up: {
        meaning: 'Descenso del filtrado glomerular (agudo o crónico), o artefacto.',
        causes: ['Lesión renal aguda prerrenal por hipovolemia (CAD, EHH)', 'Enfermedad renal crónica', 'Rabdomiólisis', 'Artefacto: el acetoacetato interfiere en algunos métodos (Jaffé) y eleva falsamente la creatinina'],
      },
      down: { meaning: 'Poca masa muscular o hiperfiltración.', causes: ['Sarcopenia, desnutrición', 'Embarazo'] },
      importance: 'En las crisis hiperglucémicas la lesión renal aguda prerrenal es frecuente y condiciona la reposición de potasio y de líquidos.',
      changes: 'Si hay oliguria o creatinina muy alta, reponer potasio con más cautela y vigilar la sobrecarga de volumen.',
      topics: ['cad', 'ehh'],
      pearl: 'En la CAD la creatinina puede estar **falsamente elevada** por interferencia del acetoacetato en el método de Jaffé.',
      fill: [{ ask: 'Factor para convertir creatinina de mg/dL a µmol/L.', answer: 88.4, tol: 0.5, unit: '', explain: 'µmol/L = mg/dL × 88,4.' }],
      gen: { min: 0.3, max: 6, step: 0.1 },
      sources: [],
    },
    {
      id: 'bun',
      name: 'Nitrógeno ureico (BUN)',
      abbr: 'BUN',
      unit: 'mg/dL',
      low: 7,
      high: 20,
      decimals: 0,
      ref: '7–20',
      units: 'Urea (mg/dL) = BUN × 2,14. En muchos laboratorios hispanohablantes se informa la urea (≈15–43 mg/dL).',
      represents: 'El nitrógeno de la urea: producto del catabolismo proteico, eliminado por el riñón y reabsorbido en parte cuando hay hipovolemia.',
      up: {
        meaning: 'Hipovolemia (prerrenal), descenso del filtrado o aumento del catabolismo.',
        causes: ['Deshidratación: CAD, EHH', 'Hemorragia digestiva alta', 'Glucocorticoides, dieta hiperproteica', 'Enfermedad renal'],
      },
      down: { meaning: 'Baja producción.', causes: ['Hepatopatía grave', 'Malnutrición'] },
      importance: 'Un cociente BUN/creatinina >20 sugiere un componente prerrenal. El BUN entra en la osmolalidad total calculada.',
      changes: 'Orienta la reposición de volumen.',
      topics: ['ehh', 'cad'],
      pearl: 'El BUN suma osmolalidad total pero **no efectiva**: no desplaza agua fuera de las neuronas.',
      fill: [{ ask: 'Factor para pasar de BUN a urea (mg/dL).', answer: 2.14, tol: 0.02, unit: '', explain: 'Urea = BUN × 2,14 (BUN = urea × 0,467).' }],
      gen: { min: 3, max: 120, step: 1 },
      sources: [],
    },
    {
      id: 'tfg',
      name: 'Filtrado glomerular estimado',
      abbr: 'TFGe',
      unit: 'mL/min/1,73 m²',
      low: 90,
      high: 200,
      oneSided: 'low',
      decimals: 0,
      ref: '≥90',
      represents: 'Estimación del filtrado a partir de la creatinina (y la cistatina C), la edad y el sexo mediante ecuaciones como CKD-EPI 2021.',
      down: {
        meaning: 'Descenso del filtrado. En situación aguda (creatinina cambiante) las ecuaciones **no son válidas**.',
        causes: ['Enfermedad renal crónica', 'Lesión renal aguda (la estimación no es fiable)'],
        action: 'Ajustar las dosis de fármacos; en situación aguda, seguir la creatinina y la diuresis.',
      },
      importance: 'Sirve para ajustar fármacos y valorar enfermedad renal crónica, no para la fase aguda de una crisis.',
      changes: 'No uses la TFGe para dosificar en plena lesión renal aguda.',
      topics: ['cad', 'ehh'],
      pearl: 'La TFGe presupone una creatinina **estable**: en la lesión renal aguda sobrestima el filtrado real.',
      gen: { min: 10, max: 89, step: 1, nmin: 90, nmax: 125 },
      sources: [],
    },
  ],
);
