/* Valores: tiroides. */
SolMed.registry.addValues(
  { id: 'tiroides', name: 'Tiroides', desc: 'TSH, hormonas tiroideas, anticuerpos y pruebas de localización.' },
  [
    {
      id: 'tsh',
      name: 'Tirotropina',
      abbr: 'TSH',
      unit: 'mUI/L',
      low: 0.4,
      high: 4.0,
      decimals: 2,
      ref: '0,4–4,0',
      represents: 'La hormona hipofisaria que estimula la tiroides. Responde de forma logarítmica a pequeños cambios de T4 libre, por eso es la mejor prueba inicial en patología tiroidea **primaria**.',
      up: {
        meaning: 'Hipotiroidismo primario (con T4L baja) o subclínico (con T4L normal).',
        causes: ['Tiroiditis de Hashimoto', 'Tras radioyodo o tiroidectomía', 'Amiodarona, litio', 'Recuperación de una enfermedad grave (elevación transitoria)', 'Raro: adenoma productor de TSH o resistencia a hormonas tiroideas (T4L alta)'],
        action: 'Medir T4 libre; si la TSH es ≥10 mUI/L suele tratarse aunque la T4L sea normal.',
      },
      down: {
        meaning: 'Tirotoxicosis (con T4L o T3 altas) o hipotiroidismo **central** (con T4L baja).',
        causes: ['Enfermedad de Graves, bocio multinodular tóxico, adenoma tóxico', 'Tiroiditis (subaguda, silente, posparto)', 'Exceso de levotiroxina', 'Enfermedad no tiroidea grave, glucocorticoides, dopamina', 'Hipotiroidismo central (hipófisis o hipotálamo)'],
      },
      importance: 'En el hipotiroidismo central la TSH puede ser baja, normal o incluso algo alta (biológicamente inactiva): **no sirve para diagnosticarlo ni para ajustar la dosis**.',
      changes: 'En el hipotiroidismo primario se ajusta la levotiroxina por TSH (control a las 6–8 semanas); en el central, por T4 libre.',
      topics: ['hipotiroidismo', 'hipertiroidismo'],
      pearl: 'TSH baja + T4L baja = piensa en **hipófisis**, y descarta insuficiencia suprarrenal antes de dar levotiroxina.',
      thresholds: [
        { kind: 'normal', value: '0,4–4,0 mUI/L', note: 'El límite superior aumenta con la edad.' },
        { kind: 'terapeutico', value: '≥10 mUI/L', note: 'En el hipotiroidismo subclínico, umbral habitual para tratar.' },
      ],
      fill: [{ ask: 'TSH a partir de la cual se suele tratar un hipotiroidismo subclínico (mUI/L).', answer: 10, tol: 0, unit: 'mUI/L', explain: 'TSH ≥10 mUI/L; entre el límite superior y 10 se individualiza (síntomas, embarazo, anticuerpos).' }],
      gen: { min: 0.01, max: 60, step: 0.01, nmin: 0.5, nmax: 3.9 },
      sources: ['ata2014', 'ata2016'],
    },
    {
      id: 't4l',
      name: 'Tiroxina libre',
      abbr: 'T4L',
      unit: 'ng/dL',
      low: 0.8,
      high: 1.8,
      decimals: 1,
      ref: '0,8–1,8',
      units: 'pmol/L ≈ ng/dL × 12,9 (≈10–23 pmol/L).',
      represents: 'La fracción de T4 no unida a proteínas: la biológicamente disponible. Es independiente de los cambios de la TBG.',
      up: { meaning: 'Tirotoxicosis (con TSH suprimida).', causes: ['Graves, nódulos tóxicos', 'Tiroiditis', 'Exceso de levotiroxina', 'Amiodarona'] },
      down: { meaning: 'Hipotiroidismo: primario (TSH alta) o central (TSH baja o normal).', causes: ['Hashimoto', 'Hipopituitarismo', 'Enfermedad no tiroidea grave (síndrome del eutiroideo enfermo)'] },
      importance: 'Distingue el hipotiroidismo manifiesto (T4L baja) del subclínico (T4L normal).',
      changes: 'En el hipotiroidismo central es la prueba para ajustar la dosis (objetivo: mitad superior del rango).',
      topics: ['hipotiroidismo', 'hipertiroidismo'],
      pearl: 'Una tirotoxicosis con T4L normal y T3 alta = **tirotoxicosis por T3** (típica de nódulos tóxicos o Graves incipiente).',
      fill: [{ ask: 'Límite inferior normal de la T4 libre (ng/dL).', answer: 0.8, tol: 0.1, unit: 'ng/dL', explain: 'Rango orientativo 0,8–1,8 ng/dL (varía por método).' }],
      gen: { min: 0.1, max: 7, step: 0.1 },
      sources: ['ata2014'],
    },
    {
      id: 't4t',
      name: 'Tiroxina total',
      abbr: 'T4 total',
      unit: 'µg/dL',
      low: 5.0,
      high: 12.0,
      decimals: 1,
      ref: '5,0–12,0',
      represents: 'La T4 unida a proteínas más la libre. Depende de la TBG.',
      up: { meaning: 'Exceso de hormona o exceso de TBG.', causes: ['Tirotoxicosis', 'Embarazo y estrógenos (↑TBG) con T4L normal'] },
      down: { meaning: 'Déficit de hormona o de TBG.', causes: ['Hipotiroidismo', 'Andrógenos, síndrome nefrótico (↓TBG)'] },
      importance: 'Útil cuando la T4L no es fiable (por ejemplo, en el embarazo avanzado, donde se usa el rango total × 1,5).',
      changes: 'Si la T4 total no concuerda con la clínica, piensa en alteraciones de la TBG.',
      topics: ['hipotiroidismo', 'hipertiroidismo'],
      pearl: 'Los estrógenos elevan la TBG: la T4 **total** sube y la **libre** sigue normal.',
      gen: { min: 1, max: 25, step: 0.1 },
      sources: [],
    },
    {
      id: 't3',
      name: 'Triyodotironina total',
      abbr: 'T3',
      unit: 'ng/dL',
      low: 80,
      high: 180,
      decimals: 0,
      ref: '80–180',
      represents: 'La hormona activa; en su mayoría procede de la desyodación periférica de T4.',
      up: { meaning: 'Tirotoxicosis; en Graves y en los nódulos tóxicos la T3 sube de forma desproporcionada.', causes: ['Graves', 'Bocio multinodular tóxico, adenoma tóxico', 'Tirotoxicosis por T3'] },
      down: { meaning: 'Descenso de la conversión de T4 a T3.', causes: ['Enfermedad no tiroidea grave, ayuno', 'Glucocorticoides, propranolol a dosis altas, amiodarona', 'Hipotiroidismo avanzado'] },
      importance: 'Un cociente T3/T4 alto sugiere hiperproducción glandular (Graves, nódulos); en las tiroiditis predomina la T4 liberada.',
      changes: 'No se usa para diagnosticar ni seguir el hipotiroidismo.',
      topics: ['hipertiroidismo'],
      pearl: 'La T3 baja del paciente crítico (**síndrome del eutiroideo enfermo**) no se trata con hormona tiroidea.',
      gen: { min: 30, max: 600, step: 1 },
      sources: ['ata2016'],
    },
    {
      id: 'trab',
      name: 'Anticuerpos contra el receptor de TSH',
      abbr: 'TRAb / TSI',
      unit: '',
      ref: 'Negativos',
      represents: 'Autoanticuerpos que estimulan el receptor de TSH (TSI). Son la causa de la enfermedad de Graves.',
      up: {
        meaning: 'Positivos: enfermedad de Graves (alta sensibilidad y especificidad).',
        causes: ['Graves', 'Tirotoxicosis gestacional o neonatal por paso transplacentario (en madres con Graves)'],
      },
      importance: 'Confirman Graves sin gammagrafía cuando la clínica no es típica, y predicen el riesgo de tirotoxicosis fetal o neonatal.',
      changes: 'Positivos → Graves: tratar con antitiroideos, radioyodo o cirugía. Negativos con captación baja → tiroiditis: betabloqueo, **no** antitiroideos.',
      topics: ['hipertiroidismo'],
      pearl: 'En una embarazada con Graves (actual o tratado), unos TRAb elevados obligan a vigilar al feto.',
      sources: ['ata2016'],
    },
    {
      id: 'antitpo',
      name: 'Anticuerpos antiperoxidasa',
      abbr: 'Anti-TPO',
      unit: '',
      ref: 'Negativos',
      represents: 'Marcador de autoinmunidad tiroidea.',
      up: {
        meaning: 'Positivos: tiroiditis autoinmune (Hashimoto). También aparecen en muchos pacientes con Graves.',
        causes: ['Hashimoto', 'Graves', 'Tiroiditis posparto'],
      },
      importance: 'En el hipotiroidismo subclínico predicen mayor progresión a hipotiroidismo manifiesto.',
      changes: 'Apoyan tratar un hipotiroidismo subclínico limítrofe, sobre todo si se busca embarazo.',
      topics: ['hipotiroidismo'],
      pearl: 'Anti-TPO positivos **no distinguen** Hashimoto de Graves: para Graves pide TRAb.',
      sources: ['ata2014'],
    },
    {
      id: 'tg',
      name: 'Tiroglobulina sérica',
      abbr: 'Tg',
      unit: '',
      ref: 'Detectable (el rango varía por método)',
      represents: 'Proteína precursora de las hormonas; se libera cuando la tiroides produce o se destruye.',
      up: { meaning: 'Alta: producción o destrucción glandular.', causes: ['Graves, tiroiditis', 'Carcinoma diferenciado de tiroides (seguimiento)'] },
      down: { meaning: 'Baja o indetectable en una tirotoxicosis: hormona **exógena**.', causes: ['Tirotoxicosis facticia (ingesta de levotiroxina)'] },
      importance: 'Tirotoxicosis + captación baja + tiroglobulina baja = tirotoxicosis **facticia**.',
      changes: 'Distingue la tirotoxicosis facticia de la tiroiditis silente (ambas con captación baja).',
      topics: ['hipertiroidismo'],
      pearl: 'Captación baja: si la Tg está **alta** es tiroiditis; si está **baja**, hormona exógena.',
      sources: ['ata2016'],
    },
    {
      id: 'raiu',
      name: 'Captación de yodo radiactivo a las 24 h',
      abbr: 'RAIU 24 h',
      unit: '%',
      low: 10,
      high: 30,
      decimals: 0,
      ref: '10–30',
      units: 'Varía según la ingesta de yodo de la población.',
      represents: 'La avidez de la tiroides por el yodo: indica si la glándula está **sintetizando** hormona.',
      up: { meaning: 'Hiperproducción: hipertiroidismo verdadero.', causes: ['Graves (captación difusa)', 'Bocio multinodular tóxico (parcheada)', 'Adenoma tóxico (nódulo «caliente» con supresión del resto)'] },
      down: {
        meaning: 'Tirotoxicosis **sin** hiperproducción: destrucción, fuente exógena o exceso de yodo.',
        causes: ['Tiroiditis subaguda, silente o posparto', 'Tirotoxicosis facticia', 'Exceso de yodo (contraste, amiodarona)', 'Estruma ovárico (raro)'],
      },
      importance: 'Es la prueba que separa **hipertiroidismo** (captación alta) de **tirotoxicosis sin hipertiroidismo** (captación baja).',
      changes: 'Captación baja → los antitiroideos y el radioyodo no sirven; tratamiento sintomático.',
      topics: ['hipertiroidismo'],
      pearl: 'Contraindicada en el embarazo y la lactancia: ahí se usan TRAb y ecografía Doppler.',
      gen: { min: 0, max: 90, step: 1 },
      sources: ['ata2016'],
    },
    {
      id: 'vsg',
      name: 'Velocidad de sedimentación globular',
      abbr: 'VSG',
      unit: 'mm/h',
      low: 0,
      high: 20,
      oneSided: 'high',
      decimals: 0,
      ref: '<20 (aumenta con la edad; algo mayor en mujeres)',
      represents: 'Reactante de fase aguda inespecífico.',
      up: { meaning: 'Inflamación.', causes: ['Tiroiditis subaguda granulomatosa (de Quervain)', 'Infecciones, enfermedades autoinmunes, neoplasias'] },
      importance: 'Tiroides dolorosa + VSG alta + captación baja = tiroiditis subaguda.',
      changes: 'Apoya tratar con AINE o glucocorticoides y betabloqueo, no con antitiroideos.',
      topics: ['hipertiroidismo'],
      pearl: 'Dolor cervical anterior irradiado a la mandíbula tras un cuadro viral + VSG alta → de Quervain.',
      gen: { min: 0, max: 110, step: 1, nmin: 2, nmax: 19 },
      sources: [],
    },
  ],
);
