/* Tema: Estado hiperglucémico hiperosmolar (EHH). Revisión 2026-09-26.
 * Criterios ADA/EASD 2024; metas de corrección según JBDS. */
SolMed.registry.addTopic({
  id: 'ehh',
  name: 'Estado hiperglucémico hiperosmolar',
  short: 'EHH',
  specialty: 'medicina-interna',
  area: 'endocrinologia',
  group: 'Diabetes',
  reviewed: '2026-09-26',
  sources: ['ada2024', 'jbds', 'ada2009', 'harrison22'],
  summary: 'Hiperglucemia extrema con hiperosmolalidad y deshidratación profunda, sin cetoacidosis significativa. Típico de ancianos con DM2; la mortalidad es mayor que en la CAD.',
  subtopics: [
    { id: 'fisio', name: 'Fisiopatología y causas' },
    { id: 'dx', name: 'Clínica y diagnóstico' },
    { id: 'lab', name: 'Laboratorio' },
    { id: 'tx', name: 'Tratamiento' },
    { id: 'comp', name: 'Complicaciones' },
  ],
  concepts: [
    { id: 'fisiopato', name: 'Déficit relativo de insulina y diuresis osmótica', sub: 'fisio' },
    { id: 'precipitantes', name: 'Precipitantes y factores de riesgo', sub: 'fisio' },
    { id: 'clinica', name: 'Manifestaciones clínicas y neurológicas', sub: 'dx' },
    { id: 'criterios', name: 'Criterios diagnósticos (2024)', sub: 'dx' },
    { id: 'mixto', name: 'Cuadro mixto CAD-EHH', sub: 'dx' },
    { id: 'diferencial', name: 'Otras causas de alteración de conciencia', sub: 'dx' },
    { id: 'osmolalidad', name: 'Osmolalidad efectiva y conciencia', sub: 'lab' },
    { id: 'sodio', name: 'Sodio corregido e hipernatremia oculta', sub: 'lab' },
    { id: 'liquidos', name: 'Reposición de líquidos: prioridad', sub: 'tx' },
    { id: 'insulina', name: 'Insulina: cuándo y a qué dosis', sub: 'tx' },
    { id: 'metas', name: 'Metas de corrección (osmolalidad, sodio, glucosa)', sub: 'tx' },
    { id: 'resolucion', name: 'Criterios de resolución', sub: 'tx' },
    { id: 'trombosis', name: 'Trombosis y tromboprofilaxis', sub: 'comp' },
    { id: 'neuro_comp', name: 'Edema cerebral y desmielinización osmótica', sub: 'comp' },
    { id: 'otras_comp', name: 'Rabdomiólisis, lesión renal y úlceras', sub: 'comp' },
  ],
  sheet: [
    {
      title: 'Definición',
      body: [
        'Emergencia hiperglucémica con **glucosa muy alta, hiperosmolalidad y deshidratación profunda**, **sin** cetoacidosis significativa.',
        'Queda suficiente insulina para frenar la lipólisis y la cetogénesis, pero no para controlar la glucosa.',
      ],
    },
    {
      title: 'Epidemiología relevante',
      body: [
        [
          'Típico de adultos mayores con DM2, a menudo sin diagnóstico previo.',
          'Menos frecuente que la CAD, pero con **mayor mortalidad** (edad, comorbilidad, trombosis, precipitante grave).',
          'Hasta un tercio de las crisis hiperglucémicas tienen rasgos **mixtos** CAD-EHH.',
        ],
      ],
    },
    {
      title: 'Etiología, factores de riesgo y precipitantes',
      body: [
        [
          '**Infección** (neumonía, infección urinaria, sepsis): el precipitante más frecuente.',
          'Ictus, infarto, pancreatitis, cirugía.',
          'Fármacos: glucocorticoides, tiazidas, antipsicóticos atípicos, fenitoína, nutrición parenteral.',
          '**Acceso limitado al agua**: demencia, dependencia, residencias, sed alterada del anciano.',
          'Abandono del tratamiento o diabetes no diagnosticada.',
        ],
      ],
    },
    {
      title: 'Fisiopatología',
      body: [
        [
          'Déficit **relativo** de insulina + hormonas contrarreguladoras → hiperglucemia progresiva.',
          'La insulina residual (sensible en la vena porta) frena la lipólisis → no hay cetoacidosis relevante.',
          'Glucosuria → **diuresis osmótica** prolongada (días a semanas) → pérdida de agua mayor que de sodio → déficit de ≈9 L o más.',
          'Si no se bebe lo suficiente → hipernatremia real, **hiperosmolalidad** y deshidratación celular (neuronas).',
          'La caída del filtrado reduce la glucosuria y la glucosa sube aún más (círculo vicioso).',
        ],
      ],
    },
    {
      title: 'Manifestaciones clínicas',
      body: [
        [
          'Evolución **insidiosa**: días a semanas de poliuria, polidipsia, debilidad y pérdida de peso.',
          'Deshidratación grave: hipotensión, taquicardia, mucosas secas, oliguria.',
          'Alteración neurológica proporcional a la osmolalidad efectiva: letargia, confusión, **focalidad** (hemiparesia que puede simular un ictus), **convulsiones** focales, coma.',
          'Sin Kussmaul ni aliento cetósico (salvo cuadro mixto). El dolor abdominal es raro.',
        ],
      ],
    },
    {
      title: 'Criterios diagnósticos (consenso 2024)',
      body: [
        [
          'Glucosa **≥600 mg/dL**.',
          'Osmolalidad **efectiva >300 mOsm/kg** (o total >320).',
          'Sin cetonemia significativa: β-OHB <3,0 mmol/L (o cetonuria <2+).',
          'Sin acidosis: pH ≥7,3 y HCO₃⁻ ≥15 mEq/L.',
        ],
        '**Diferencia con 2009:** se exigía osmolalidad efectiva >320. Si cumple criterios de CAD y de EHH, es un **cuadro mixto** y se trata como ambos.',
      ],
    },
    {
      title: 'Diagnóstico diferencial',
      body: [
        [
          'CAD (β-OHB ≥3,0 con acidosis) o cuadro mixto.',
          'Otras causas de alteración de conciencia: ictus, hemorragia intracraneal, sepsis o meningitis, intoxicaciones, hipoglucemia previa, estado postictal.',
          '**Si el paciente está en coma con osmolalidad efectiva <320**, busca otra causa del coma.',
          'Hipernatremia sin hiperglucemia (diabetes insípida, pérdidas sin acceso al agua).',
        ],
      ],
    },
    {
      title: 'Laboratorio y estudios complementarios',
      body: [
        [
          'Glucosa, electrolitos, **osmolalidad** (medida y calculada), β-OHB, gasometría venosa, BUN y creatinina, fósforo y magnesio.',
          '**CK** (rabdomiólisis), hemograma, cultivos, radiografía de tórax, análisis de orina, ECG y troponina.',
          'TC craneal si hay focalidad que no mejora con la corrección o si la osmolalidad no explica el coma.',
        ],
      ],
    },
    {
      title: 'Interpretación de resultados',
      body: [
        [
          '**Sodio corregido**: casi siempre revela hipernatremia oculta (el medido parece normal o bajo).',
          'Un HCO₃⁻ de 15–18 puede deberse a acidosis láctica o prerrenal: si el β-OHB es <3,0, no es CAD.',
          'BUN/creatinina muy elevados por la hipovolemia (prerrenal).',
          'Osmolalidad efectiva >320 → la alteración de conciencia es esperable.',
        ],
      ],
    },
    {
      title: 'Tratamiento inicial y secuencia',
      body: [
        '**Prioridad: el volumen.** Muchas veces la glucosa baja solo con líquidos.',
        [
          '**Líquidos**: cristaloide isotónico a 500–1000 mL/h durante 2–4 h (ADA 2024), ajustado al riesgo cardíaco. JBDS busca un balance positivo de 3–6 L en las primeras 12 h.',
          'Si la osmolalidad **no baja** a pesar de un balance positivo adecuado, o el sodio corregido es alto con el paciente estable, pasar a salino al 0,45 %.',
          '**Potasio**: igual que en la CAD (reponer antes de la insulina si es <3,5).',
          '**Insulina**: JBDS recomienda empezarla cuando la glucosa **deja de bajar** con los líquidos solos, a dosis baja (0,05 U/kg/h), salvo que haya cetonemia significativa. El consenso de 2024 usa infusión IV con dextrosa cuando la glucosa baja de 300 mg/dL.',
          'Tratar el precipitante; **tromboprofilaxis** con heparina de bajo peso molecular salvo contraindicación; protección de talones.',
        ],
      ],
    },
    {
      title: 'Monitorización y metas terapéuticas',
      body: [
        [
          'Glucosa cada hora; electrolitos y osmolalidad cada 2–4 h; diuresis y nivel de conciencia.',
          'Descenso de la **osmolalidad**: ≈3–8 mOsm/kg/h (JBDS).',
          'Descenso del **sodio**: no más de ~10 mEq/L en 24 h.',
          'Glucosa: descenso gradual; mantener ≈250–300 mg/dL hasta que mejore la conciencia (dextrosa si baja de 300).',
          'Diuresis ≥0,5 mL/kg/h.',
        ],
      ],
    },
    {
      title: 'Resolución y tratamiento definitivo',
      body: [
        '**Resolución (2024)**: osmolalidad <300 mOsm/kg, glucosa <250 mg/dL, diuresis >0,5 mL/kg/h y mejora cognitiva.',
        'Transición a insulina SC con solapamiento. Muchos pacientes con DM2 necesitarán insulina al menos temporalmente; después, reevaluar.',
        'Prevención: hidratación y supervisión en personas dependientes, educación a cuidadores y control de fármacos hiperglucemiantes.',
      ],
    },
    {
      title: 'Complicaciones',
      body: [
        [
          '**Trombosis** venosa y arterial (hiperviscosidad, deshidratación, inmovilidad).',
          '**Edema cerebral** y **desmielinización osmótica** si la osmolalidad o el sodio bajan demasiado rápido.',
          '**Rabdomiólisis** y lesión renal aguda.',
          'Úlceras por presión en los talones, aspiración, hipoglucemia e hipopotasemia por el tratamiento.',
        ],
      ],
    },
    {
      title: 'Situaciones especiales',
      body: [
        [
          'Insuficiencia cardíaca o renal: líquidos en bolos pequeños y reevaluación frecuente.',
          'Cuadro mixto: seguir el algoritmo de la CAD para la insulina, con las metas osmolares del EHH.',
        ],
      ],
    },
    {
      title: 'Errores frecuentes',
      body: [
        [
          'Empezar con insulina a dosis alta antes de reponer el volumen: la glucosa y el agua entran en las células y cae la PA.',
          'Leer como «hiponatremia» un sodio de 132 sin corregirlo.',
          'Bajar la glucosa o el sodio demasiado rápido.',
          'Olvidar la tromboprofilaxis.',
          'Atribuir el coma al EHH con osmolalidad efectiva <320.',
        ],
      ],
    },
    {
      title: 'Pronóstico',
      body: ['Mortalidad mayor que la de la CAD; depende de la edad, el grado de hiperosmolalidad, el precipitante y las comorbilidades.'],
    },
    {
      title: 'Perlas clínicas de alto rendimiento',
      body: [
        [
          'En el EHH **el líquido es el tratamiento**: la insulina viene después.',
          'Focalidad + glucosa >600 → corrige y reevalúa antes de etiquetar un ictus (pero no retrases la imagen si hay dudas).',
          'Sodio medido que no sube mientras baja la glucosa = demasiada agua libre.',
          'Coma con osmolalidad efectiva <320 → busca otra causa.',
        ],
      ],
    },
  ],
  items: [
    {
      id: 'q01',
      type: 'mcq',
      sub: 'dx',
      concepts: ['criterios'],
      diff: 1,
      cat: 'diagnostico',
      stem: 'Según el consenso de 2024, ¿cuál de los siguientes pacientes cumple los criterios de EHH?',
      options: [
        { t: 'Glucosa 820 mg/dL, osmolalidad efectiva 334, β-OHB 0,9 mmol/L, pH 7,38, HCO₃⁻ 22', why: 'Cumple los 4 criterios: glucosa ≥600, efectiva >300, β-OHB <3,0, pH ≥7,3 y HCO₃⁻ ≥15.' },
        { t: 'Glucosa 560 mg/dL, osmolalidad efectiva 318, β-OHB 0,5, pH 7,40', why: 'La glucosa no llega a 600 mg/dL.' },
        { t: 'Glucosa 720 mg/dL, osmolalidad efectiva 326, β-OHB 4,8, pH 7,19', why: 'Hay cetoacidosis: es un cuadro mixto, no un EHH puro.', err: 'diferencial' },
        { t: 'Glucosa 650 mg/dL, osmolalidad efectiva 292, β-OHB 0,4, pH 7,37', why: 'La osmolalidad efectiva no supera 300.', err: 'calculo' },
      ],
      answer: 0,
      explain: ['Glucosa ≥600 mg/dL.', 'Osmolalidad efectiva >300 (o total >320).', 'β-OHB <3,0.', 'pH ≥7,3 y HCO₃⁻ ≥15.'],
      pearl: 'En 2024 el umbral de osmolalidad **efectiva** baja de 320 a **300** mOsm/kg.',
      remember: 'EHH = glucosa ≥600 + efectiva >300 + sin cetoacidosis.',
      compare: ['cad-ehh'],
    },
    {
      id: 'q02',
      type: 'mcq',
      sub: 'tx',
      concepts: ['liquidos', 'insulina'],
      diff: 2,
      cat: 'secuencia',
      stem: 'Mujer de 81 años con EHH (glucosa 980 mg/dL, K⁺ 4,4, PA 88/50). ¿Cuál es la medida inicial más importante?',
      options: [
        { t: 'Reposición de volumen con cristaloide isotónico', why: 'Correcto: el déficit de agua es enorme y la hipotensión es la amenaza inmediata; los líquidos bajan la glucosa por sí solos.' },
        { t: 'Bolo de insulina IV de 0,1 U/kg seguido de 0,1 U/kg/h', why: 'Antes de reponer el volumen, la insulina desplaza agua al interior celular y empeora la hipotensión.', err: 'secuencia' },
        { t: 'Salino al 0,45 % rápido para bajar el sodio', why: 'El primer objetivo es el volumen intravascular con cristaloide isotónico.', err: 'tratamiento' },
        { t: 'Bicarbonato', why: 'No hay acidosis significativa en el EHH.' },
      ],
      answer: 0,
      explain: ['Déficit de agua ≈9 L o más.', 'Cristaloide isotónico 500–1000 mL/h las primeras horas.', 'Muchas veces la glucosa cae solo con los líquidos (dilución y mejor filtrado).', 'La insulina, a dosis baja, cuando la glucosa deja de bajar (JBDS).'],
      trap: 'Pensar que la glucosa es el problema principal: en el EHH lo es la **deshidratación**.',
      pearl: 'En el EHH, la insulina antes del volumen puede provocar un colapso circulatorio.',
      remember: 'EHH: líquidos primero, insulina después y a dosis baja.',
    },
    {
      id: 'q03',
      type: 'mcq',
      sub: 'lab',
      concepts: ['sodio'],
      diff: 2,
      cat: 'calculo',
      stem: 'EHH con Na⁺ medido de 134 mEq/L y glucosa de 1100 mg/dL. ¿Qué indica el sodio corregido (factor 1,6)?',
      options: [
        { t: '≈150 mEq/L: hipernatremia real, con déficit de agua libre importante', why: 'Correcto: 134 + 1,6 × 10 = 150.' },
        { t: '134 mEq/L: natremia normal', why: 'Sin corregir, subestimas la hipertonicidad.', err: 'calculo' },
        { t: '≈118 mEq/L: hiponatremia grave', why: 'La corrección suma, no resta.', err: 'calculo' },
        { t: '≈142 mEq/L: normal', why: 'Error de cálculo: (1100 − 100)/100 = 10.', err: 'calculo' },
      ],
      answer: 0,
      explain: ['(1100 − 100)/100 = 10.', '10 × 1,6 = 16.', '134 + 16 = 150 mEq/L.'],
      pearl: 'En el EHH, un sodio «normal» casi siempre esconde una **hipernatremia**.',
      remember: 'Corrige siempre el sodio antes de interpretarlo.',
    },
    {
      id: 'q04',
      type: 'mcq',
      sub: 'tx',
      concepts: ['metas'],
      diff: 3,
      cat: 'tratamiento',
      stem: 'Durante el tratamiento de un EHH, ¿qué ritmo de corrección es más seguro según JBDS?',
      options: [
        { t: 'Osmolalidad −3 a −8 mOsm/kg/h y sodio sin bajar más de ~10 mEq/L en 24 h', why: 'Correcto: corrección gradual para evitar el edema cerebral y la desmielinización osmótica.' },
        { t: 'Normalizar la osmolalidad en 6 h', why: 'Una corrección tan rápida aumenta el riesgo neurológico.', err: 'complicaciones' },
        { t: 'Glucosa −200 mg/dL por hora', why: 'Demasiado rápido.', err: 'tratamiento' },
        { t: 'No hay límite si el paciente está consciente', why: 'El riesgo osmótico existe igualmente.' },
      ],
      answer: 0,
      explain: ['Las neuronas generan osmoles idiogénicos para adaptarse.', 'Si la osmolalidad cae deprisa, entra agua en las neuronas → edema.', 'Si el sodio cae deprisa → desmielinización osmótica.'],
      pearl: 'En el EHH **despacio es seguro**: corrige en 24–72 h.',
      remember: 'Osm −3 a −8/h · Na ≤10 mEq/L en 24 h.',
    },
    {
      id: 'q05',
      type: 'mcq',
      sub: 'dx',
      concepts: ['diferencial', 'osmolalidad'],
      diff: 3,
      cat: 'diferencial',
      stem: 'Varón de 70 años en coma (GCS 7) con glucosa de 540 mg/dL, Na⁺ 138 mEq/L y β-OHB 0,6 mmol/L. ¿Cuál es el paso más adecuado?',
      options: [
        { t: 'Calcular la osmolalidad efectiva (≈306) y, como es <320, buscar otra causa del coma (TC craneal, glucosa previa, tóxicos, sepsis)', why: 'Correcto: una osmolalidad efectiva de ≈306 no suele explicar un coma.' },
        { t: 'Atribuir el coma al EHH y esperar a que mejore con la hidratación', why: 'La osmolalidad no es lo bastante alta para explicar un coma.', err: 'diferencial' },
        { t: 'Diagnosticar una CAD grave', why: 'β-OHB 0,6: no hay cetoacidosis.', err: 'diferencial' },
        { t: 'Administrar insulina en bolo alto para bajar la glucosa rápidamente', why: 'No trata la causa del coma y es peligroso.' },
      ],
      answer: 0,
      explain: ['Osm efectiva = 2 × 138 + 540/18 = 276 + 30 = 306.', 'El coma se relaciona con osmolalidad efectiva >320–330.', 'Con 306, busca ictus, hemorragia, sepsis, tóxicos o un estado postictal.'],
      key: ['GCS 7', 'Osm efectiva ≈306'],
      trap: 'Explicar cualquier alteración de conciencia por la hiperglucemia.',
      pearl: 'Coma + osmolalidad efectiva <320 → **otra causa** hasta demostrar lo contrario.',
      remember: 'Calcula la osmolalidad antes de atribuirle el coma.',
    },
    {
      id: 'q06',
      type: 'mcq',
      sub: 'comp',
      concepts: ['trombosis'],
      diff: 2,
      cat: 'complicaciones',
      stem: '¿Qué medida preventiva está indicada en la mayoría de los pacientes ingresados por EHH, salvo contraindicación?',
      options: [
        { t: 'Tromboprofilaxis con heparina de bajo peso molecular', why: 'Correcto: el EHH es un estado protrombótico (hiperviscosidad, deshidratación, inmovilidad).' },
        { t: 'Anticoagulación a dosis plenas en todos', why: 'Solo si hay trombosis confirmada u otra indicación.' },
        { t: 'Antibióticos profilácticos', why: 'Se tratan las infecciones confirmadas o sospechadas, no de forma profiláctica.' },
        { t: 'Bicarbonato profiláctico', why: 'Sin indicación.' },
      ],
      answer: 0,
      explain: ['Hiperosmolalidad + deshidratación → hiperviscosidad.', 'Pacientes mayores e inmovilizados.', 'JBDS recomienda profilaxis con HBPM.'],
      pearl: 'No olvides proteger los **talones**: las úlceras por presión son otra complicación prevenible.',
      remember: 'EHH → HBPM profiláctica.',
    },
    {
      id: 'q07',
      type: 'mcq',
      sub: 'fisio',
      concepts: ['fisiopato'],
      diff: 2,
      cat: 'fisiopatologia',
      stem: '¿Por qué en el EHH no se produce cetoacidosis significativa?',
      options: [
        { t: 'Persiste suficiente insulina para inhibir la lipólisis y la cetogénesis, pero no para controlar la glucosa', why: 'Correcto: la supresión de la lipólisis necesita menos insulina que la captación de glucosa.' },
        { t: 'El glucagón está suprimido', why: 'Las hormonas contrarreguladoras están elevadas.' },
        { t: 'El hígado no puede producir cuerpos cetónicos en los ancianos', why: 'Falso: la CAD también ocurre en ancianos.' },
        { t: 'La deshidratación elimina las cetonas por la orina', why: 'No explica la ausencia de cetogénesis.' },
      ],
      answer: 0,
      explain: ['Dosis-respuesta: la antilipólisis se consigue con concentraciones bajas de insulina.', 'En el EHH hay déficit relativo, no absoluto.', 'Además, la hiperosmolalidad puede inhibir la lipólisis.'],
      pearl: 'CAD = déficit **absoluto**; EHH = déficit **relativo**.',
      remember: 'Poca insulina frena las cetonas; hace falta mucha más para controlar la glucosa.',
      compare: ['cad-ehh'],
    },
    {
      id: 'q08',
      type: 'mcq',
      sub: 'dx',
      concepts: ['mixto', 'criterios'],
      diff: 3,
      cat: 'diagnostico',
      stem: 'Glucosa 880 mg/dL, osmolalidad efectiva 338, β-OHB 4,1 mmol/L, pH 7,22, HCO₃⁻ 14. ¿Cómo lo clasificas y tratas?',
      options: [
        { t: 'Cuadro mixto CAD-EHH: insulina y potasio según el algoritmo de la CAD, con las metas osmolares del EHH', why: 'Correcto: cumple criterios de ambos.' },
        { t: 'EHH puro: no se necesita insulina hasta que la glucosa se estabilice', why: 'Hay cetoacidosis: necesita insulina para frenar la cetogénesis.', err: 'diferencial' },
        { t: 'CAD pura: corregir la osmolalidad lo más rápido posible', why: 'La hiperosmolalidad debe corregirse gradualmente.', err: 'complicaciones' },
        { t: 'Acidosis láctica', why: 'El β-OHB alto explica la acidosis.' },
      ],
      answer: 0,
      explain: ['CAD: glucosa ≥200, β-OHB ≥3,0, pH <7,3.', 'EHH: glucosa ≥600 y efectiva >300.', 'Cumple ambos → mixto.', 'Tratamiento: el de la CAD vigilando el descenso osmolar.'],
      pearl: 'Hasta un tercio de las crisis son **mixtas**.',
      remember: 'Si cumple ambos, trátalo como ambos.',
      compare: ['cad-ehh'],
    },
    {
      id: 'q09',
      type: 'mcq',
      sub: 'tx',
      concepts: ['resolucion'],
      diff: 2,
      cat: 'tratamiento',
      stem: '¿Qué conjunto indica resolución del EHH según el consenso de 2024?',
      options: [
        { t: 'Osmolalidad <300, glucosa <250 mg/dL, diuresis >0,5 mL/kg/h y mejora cognitiva', why: 'Correcto.' },
        { t: 'Glucosa <200 mg/dL, sin más', why: 'La glucosa sola no basta: la osmolalidad y la conciencia son claves.' },
        { t: 'β-OHB <0,6 y pH ≥7,3', why: 'Son los criterios de resolución de la CAD.', err: 'diferencial' },
        { t: 'Sodio medido normal', why: 'El sodio medido puede ser engañoso.' },
      ],
      answer: 0,
      explain: ['Osmolalidad <300.', 'Glucosa <250.', 'Diuresis >0,5 mL/kg/h.', 'Estado cognitivo mejorado.'],
      pearl: 'La mejora cognitiva puede ir **retrasada** respecto a la bioquímica.',
      remember: 'Resolución del EHH: Osm <300, glucosa <250, diuresis y conciencia.',
    },
    {
      id: 'q10',
      type: 'mcq',
      sub: 'dx',
      concepts: ['clinica', 'precipitantes'],
      diff: 1,
      cat: 'concepto',
      stem: '¿Cuál es la presentación más típica del EHH?',
      options: [
        { t: 'Anciana con DM2, días a semanas de poliuria y menor ingesta de líquidos, confusión y deshidratación marcada', why: 'Correcto: evolución insidiosa y alteración neurológica.' },
        { t: 'Joven con DM1, 12 h de vómitos, dolor abdominal y Kussmaul', why: 'Es la presentación típica de la CAD.', err: 'diferencial' },
        { t: 'Adulto con hipoglucemia recurrente', why: 'No corresponde.' },
        { t: 'Embarazada con glucosa de 180 y cetonuria', why: 'Sugiere cetosis o CAD euglucémica, no EHH.' },
      ],
      answer: 0,
      explain: ['EHH: mayores, DM2, evolución lenta.', 'Alteración de conciencia frecuente.', 'Sin Kussmaul.'],
      pearl: 'La **sed alterada** del anciano y la dependencia para beber son factores de riesgo clave.',
      remember: 'EHH: lento, anciano, deshidratado, confuso.',
      compare: ['cad-ehh'],
    },

    // ---------- Caso clínico ----------
    {
      id: 'c01',
      type: 'case',
      sub: 'dx',
      concepts: ['criterios', 'clinica', 'sodio', 'osmolalidad'],
      diff: 2,
      cat: 'integracion',
      title: 'La hemiparesia que no era un ictus',
      patient: { age: 79, sex: 'F' },
      vignette: [
        'Mujer de 79 años con DM2 en tratamiento con metformina y deterioro cognitivo leve; vive sola. Su hija la encuentra somnolienta y con debilidad del brazo derecho. Lleva una semana «bebiendo poco y orinando mucho». Toma hidroclorotiazida y la semana pasada empezó prednisona por una exacerbación de EPOC.',
      ],
      vitals: { PA: '96/54 mmHg', FC: '112 lpm', FR: '20 rpm', T: '37,8 °C', SatO2: '92 %' },
      exam: 'Obnubilada (GCS 11), mucosas muy secas, pliegue cutáneo positivo. Hemiparesia derecha leve. Crepitantes en la base derecha.',
      labs: [
        { p: 'glucosa', v: 1040 },
        { p: 'na', v: 139 },
        { p: 'k', v: 4.8 },
        { p: 'cl', v: 102 },
        { p: 'hco3', v: 21 },
        { p: 'ph', v: 7.36 },
        { p: 'bohb', v: 0.8 },
        { p: 'bun', v: 68 },
        { p: 'creat', v: 2.1 },
        { p: 'lactato', v: 2.6 },
      ],
      imaging: 'Radiografía de tórax: consolidación en el lóbulo inferior derecho. TC craneal sin contraste: sin hemorragia ni lesiones agudas.',
      questions: [
        {
          stem: 'Calcula mentalmente la osmolalidad efectiva y el sodio corregido. ¿Qué conclusión es correcta?',
          cat: 'laboratorio',
          concepts: ['osmolalidad', 'sodio', 'criterios'],
          options: [
            { t: 'Osm efectiva ≈336 y Na corregido ≈154: EHH con hipernatremia oculta', why: 'Correcto: 2 × 139 + 1040/18 ≈ 278 + 58 = 336; Na corr = 139 + 1,6 × 9,4 ≈ 154.' },
            { t: 'Osm efectiva ≈300 y Na corregido 139: no cumple criterios de EHH', why: 'Error de cálculo.', err: 'calculo' },
            { t: 'Osm efectiva ≈360 porque se suma el BUN', why: 'El BUN no entra en la osmolalidad **efectiva**.', err: 'calculo' },
            { t: 'CAD por el lactato elevado', why: 'Lactato 2,6 y β-OHB 0,8: no es cetoacidosis.', err: 'diferencial' },
          ],
          answer: 0,
          explain: ['Osm efectiva = 2 × Na + glucosa/18.', 'Na corregido = Na + 1,6 × (glucosa − 100)/100.', 'Cumple: glucosa ≥600, efectiva >300, β-OHB <3, pH ≥7,3, HCO₃⁻ ≥15.'],
          key: ['Glucosa 1040', 'Osm efectiva ≈336', 'β-OHB 0,8'],
          altered: ['Glucosa ↑↑', 'BUN 68 ↑ y creatinina 2,1 ↑ (prerrenal)', 'Lactato 2,6 ↑ (hipoperfusión o infección)'],
          pearl: 'La focalidad neurológica **puede revertir** al corregir la hiperosmolalidad; aun así, la TC inicial era obligada.',
        },
        {
          stem: '¿Qué factores precipitantes identificas?',
          cat: 'concepto',
          concepts: ['precipitantes'],
          options: [
            { t: 'Neumonía, glucocorticoides, tiazida y menor ingesta de agua (vive sola, deterioro cognitivo)', why: 'Correcto: hay varios precipitantes a la vez.' },
            { t: 'Solo la metformina', why: 'La metformina no precipita el EHH.' },
            { t: 'Solo la edad', why: 'La edad es un factor de riesgo; los precipitantes son otros.' },
            { t: 'Un ictus isquémico', why: 'La TC no muestra lesión y la focalidad se explica por la hiperosmolalidad; se reevaluará.', err: 'diferencial' },
          ],
          answer: 0,
          explain: ['Infección: el precipitante más frecuente.', 'Prednisona y tiazida: hiperglucemiantes.', 'Acceso limitado al agua.'],
          pearl: 'Revisa **siempre** la lista de fármacos: los glucocorticoides y las tiazidas son precipitantes clásicos.',
        },
        {
          stem: 'Tras 3 L en 4 h, la glucosa ha bajado de 1040 a 690 mg/dL y ahora se mantiene estable; la osmolalidad baja 5 mOsm/kg/h. ¿Qué haces con la insulina?',
          cat: 'tratamiento',
          concepts: ['insulina', 'metas'],
          options: [
            { t: 'Iniciar insulina IV a dosis baja (≈0,05 U/kg/h) ahora que la glucosa dejó de bajar con líquidos', why: 'Correcto (JBDS): iniciar la insulina cuando se estanca el descenso con líquidos.' },
            { t: 'Insulina 0,1 U/kg/h con bolo para acelerar el descenso', why: 'No hace falta acelerar; el ritmo actual es seguro.', err: 'tratamiento' },
            { t: 'No dar insulina nunca en el EHH', why: 'La mayoría la necesita cuando el descenso se estanca.' },
            { t: 'Pasar a salino al 0,45 % a 1 L/h', why: 'La osmolalidad ya baja a buen ritmo; un cambio brusco aumentaría el riesgo.' },
          ],
          answer: 0,
          explain: ['Los líquidos bajan la glucosa por dilución y por la mejora del filtrado.', 'Cuando se estanca, insulina a dosis baja.', 'Dextrosa si la glucosa baja de 300 mg/dL.'],
          pearl: 'En el EHH se busca **velocidad controlada**, no normalización rápida.',
        },
      ],
    },

    // ---------- Progresivo ----------
    {
      id: 'p01',
      type: 'progressive',
      sub: 'tx',
      concepts: ['liquidos', 'metas', 'neuro_comp', 'sodio'],
      diff: 3,
      cat: 'secuencia',
      title: 'Corregir sin romper',
      stages: [
        {
          id: 's1',
          title: 'Hora 0',
          text: ['Varón de 74 años con EHH: glucosa 900 mg/dL, Na⁺ 146 mEq/L, osmolalidad efectiva 342, PA 90/60, K⁺ 4,2. Pesa 70 kg.'],
          q: {
            stem: '¿Qué líquido inicial eliges?',
            options: [
              { t: 'Cristaloide isotónico 500–1000 mL/h', why: 'Correcto: primero hay que restaurar el volumen intravascular.' },
              { t: 'Salino al 0,45 % a 1 L/h desde el inicio para bajar el sodio', why: 'Con hipotensión, el isotónico repone mejor el intravascular; el hipotónico, más tarde.', err: 'tratamiento', next: 's2b' },
              { t: 'Suero glucosado al 5 %', why: 'Agua libre sin sodio con glucosa de 900: inadecuado.', err: 'tratamiento', next: 's2b' },
              { t: 'Restringir líquidos por su edad', why: 'La deshidratación es el problema central.', err: 'tratamiento' },
            ],
            answer: 0,
            explain: ['Hipovolemia con hipotensión → cristaloide isotónico.', 'Reevaluar a menudo por la edad y el riesgo cardíaco.'],
            pearl: 'Primero el **volumen**; la tonicidad se ajusta después.',
          },
          goto: 's2',
        },
        {
          id: 's2',
          title: 'Hora 6',
          text: ['Balance positivo de 4 L. Glucosa 520. Na⁺ medido 151 (corregido ≈158). La osmolalidad efectiva baja solo 1 mOsm/kg/h. PA 124/70.'],
          q: {
            stem: '¿Qué ajuste corresponde?',
            options: [
              { t: 'Pasar a salino al 0,45 % vigilando que la osmolalidad baje 3–8 mOsm/kg/h y el Na ≤10 mEq/L en 24 h', why: 'Correcto: la osmolalidad no baja a pesar de un balance positivo, y el sodio corregido es alto con el paciente estable.' },
              { t: 'Aumentar la insulina a 0,2 U/kg/h', why: 'La insulina baja la glucosa, pero el problema es el agua libre; el riesgo osmótico aumentaría.', err: 'tratamiento' },
              { t: 'Suero glucosado al 5 % a 500 mL/h', why: 'Bajaría el sodio demasiado rápido.', err: 'complicaciones', next: 's3b' },
              { t: 'No cambiar nada', why: 'La osmolalidad no progresa.' },
            ],
            answer: 0,
            explain: ['El sodio sube mientras baja la glucosa (esperable) pero la osmolalidad no baja.', 'JBDS: si la osmolalidad no baja con un balance positivo, pasar a salino al 0,45 %.'],
            pearl: 'Vigila **Na y osmolalidad juntos**: cuentan la historia completa.',
          },
          goto: 's3',
        },
        {
          id: 's2b',
          title: 'Hora 2 · Problema',
          tone: 'alert',
          text: ['La PA sigue en 86/54 y la diuresis es escasa: el líquido hipotónico no restituye bien el volumen intravascular.'],
          q: {
            stem: '¿Cómo corriges el rumbo?',
            options: [
              { t: 'Volver a cristaloide isotónico en bolos, con reevaluación hemodinámica', why: 'Correcto.' },
              { t: 'Iniciar vasopresores sin más líquido', why: 'El problema es la hipovolemia.' },
              { t: 'Insulina en bolo', why: 'Empeoraría la hipotensión.', err: 'secuencia' },
              { t: 'Diurético', why: 'Contraindicado en la hipovolemia.' },
            ],
            answer: 0,
            explain: ['El isotónico permanece más en el espacio extracelular.', 'Primero la volemia.'],
            pearl: 'El agua libre se reparte por todos los compartimentos: poco queda en el vaso.',
          },
          goto: 's2',
        },
        {
          id: 's3b',
          title: 'Hora 10 · Complicación',
          tone: 'alert',
          text: ['El sodio cae 14 mEq/L en 4 h. El paciente, que estaba mejorando, presenta cefalea, vómitos y nueva somnolencia.'],
          q: {
            stem: '¿Qué sospechas?',
            options: [
              { t: 'Edema cerebral por descenso osmolar demasiado rápido: frenar el agua libre, valorar salino hipertónico o manitol y TC', why: 'Correcto.' },
              { t: 'Hipoglucemia', why: 'Descártala siempre, pero el contexto es osmótico.' },
              { t: 'Un nuevo ictus sin relación', why: 'El contexto temporal apunta a la corrección.' },
              { t: 'Normal durante la mejoría', why: 'No: es un empeoramiento neurológico.' },
            ],
            answer: 0,
            explain: ['Descenso rápido de la osmolalidad → entra agua en las neuronas adaptadas.', 'Se detiene el agua libre y se trata el edema.'],
            pearl: 'El deterioro neurológico **durante la mejoría bioquímica** es una alarma de corrección excesiva.',
          },
          goto: 's3',
        },
        {
          id: 's3',
          title: 'Hora 24',
          text: ['Glucosa 260, osmolalidad efectiva 308, Na⁺ 149 (descenso de 8 mEq/L en 24 h), diuresis 0,7 mL/kg/h. Más despierto.'],
          q: {
            stem: '¿Qué debes asegurar además del control metabólico?',
            options: [
              { t: 'Tromboprofilaxis con HBPM, tratar el precipitante y proteger los talones', why: 'Correcto.' },
              { t: 'Suspender todos los líquidos', why: 'Aún hay déficit de agua y la osmolalidad no se ha normalizado.' },
              { t: 'Alta a domicilio', why: 'No se ha resuelto (osmolalidad >300).' },
              { t: 'Bicarbonato', why: 'Sin indicación.' },
            ],
            answer: 0,
            explain: ['El EHH es protrombótico.', 'La resolución requiere osmolalidad <300, glucosa <250 y mejoría cognitiva.'],
            pearl: 'La mortalidad del EHH depende mucho de las **complicaciones** (trombosis, infección), no solo de la glucosa.',
          },
        },
        {
          id: 's4',
          title: 'Cierre',
          end: true,
          text: ['A las 48 h cumple los criterios de resolución. Pasa a insulina SC y se planifica con la familia la supervisión de su hidratación y de su medicación.'],
        },
      ],
    },

    // ---------- Razonamiento ----------
    {
      id: 'r01',
      type: 'reasoning',
      sub: 'dx',
      concepts: ['clinica', 'diferencial', 'criterios'],
      diff: 2,
      cat: 'razonamiento',
      title: 'Confusión en la residencia',
      vignette: ['Hombre de 83 años, residente en una residencia, con DM2. Lleva 5 días más somnoliento, bebe poco y moja muchos pañales. Hoy tuvo una convulsión focal. Glucosa capilar «HI».'],
      prompts: [
        {
          q: '¿Cuál es tu diagnóstico diferencial?',
          expected: 'EHH (el más probable: anciano, DM2, días de poliuria y poca ingesta, alteración neurológica con convulsión focal); cuadro mixto CAD-EHH; ictus o hemorragia intracraneal; infección del SNC o sepsis; hiponatremia o hipernatremia; hipoglucemia previa o estado postictal.',
          points: [
            { t: 'EHH como diagnóstico principal', kw: ['ehh', 'hiperosmolar', 'estado hiperglucemico'] },
            { t: 'Cuadro mixto o CAD', kw: ['mixto', 'cad', 'cetoacidosis'] },
            { t: 'Ictus o hemorragia intracraneal', kw: ['ictus', 'acv', 'hemorragia', 'avc'] },
            { t: 'Infección o sepsis como causa o precipitante', kw: ['infecc', 'sepsis', 'neumon', 'urinari', 'meningit'] },
          ],
        },
        {
          q: '¿Qué dato de laboratorio diferencia el EHH de la CAD y qué cálculo harías?',
          expected: 'β-hidroxibutirato (<3,0 en el EHH) y el estado ácido-base (pH ≥7,3, HCO₃⁻ ≥15). Calcularía la osmolalidad efectiva (2 × Na + glucosa/18) y el sodio corregido.',
          points: [
            { t: 'β-hidroxibutirato', kw: ['hidroxibutirato', 'bohb', 'cetonemia', 'cetonas'] },
            { t: 'pH y bicarbonato', kw: ['ph', 'bicarbonato', 'hco3', 'gasometr'] },
            { t: 'Osmolalidad efectiva', kw: ['osmolalidad', 'osmolaridad', 'osm'] },
            { t: 'Sodio corregido', kw: ['sodio corregido', 'na corregido', 'corregir el sodio'] },
          ],
        },
        {
          q: '¿Qué harías primero y por qué?',
          expected: 'Asegurar la vía aérea y la glucemia; reposición de volumen con cristaloide isotónico (el déficit de agua es enorme y la hipovolemia es la amenaza principal); potasio antes de la insulina; insulina a dosis baja cuando la glucosa deje de bajar con líquidos; buscar y tratar el precipitante; TC si la focalidad no se explica o persiste; tromboprofilaxis.',
          points: [
            { t: 'Líquidos isotónicos como prioridad', kw: ['liquid', 'cristaloide', 'salino', 'volumen', 'hidrat'] },
            { t: 'Insulina diferida y a dosis baja', kw: ['insulina', '0,05', 'dosis baja', 'despues'] },
            { t: 'Buscar el precipitante', kw: ['precipitante', 'infecc', 'cultivo', 'causa'] },
            { t: 'Tromboprofilaxis', kw: ['trombo', 'heparina', 'hbpm', 'enoxaparina'] },
          ],
          pearl: 'La convulsión focal del EHH suele responder a la corrección osmolar; los antiepilépticos clásicos pueden ser poco eficaces mientras persiste la hiperosmolalidad.',
        },
      ],
    },

    // ---------- Laboratorio ----------
    {
      id: 'l01',
      type: 'lab',
      sub: 'lab',
      concepts: ['osmolalidad', 'sodio', 'criterios'],
      diff: 2,
      cat: 'laboratorio',
      title: 'Hiperglucemia en un anciano confuso',
      context: 'Varón de 77 años, confuso, sin respiración de Kussmaul. Resultados:',
      labs: [
        { p: 'glucosa', v: 870 },
        { p: 'na', v: 137 },
        { p: 'k', v: 4.9 },
        { p: 'cl', v: 100 },
        { p: 'hco3', v: 20 },
        { p: 'ph', v: 7.35 },
        { p: 'bohb', v: 1.2 },
        { p: 'bun', v: 58 },
        { p: 'creat', v: 1.9 },
        { p: 'osm', v: 344 },
      ],
      steps: [
        { kind: 'flags', cat: 'laboratorio' },
        { kind: 'calc', calc: 'osm_ef', inputs: { na: 137, glu: 870 }, ask: 'Calcula la osmolalidad efectiva.', concepts: ['osmolalidad', 'calculos.osm_ef'] },
        { kind: 'calc', calc: 'na_corregido', inputs: { na: 137, glu: 870 }, ask: 'Calcula el sodio corregido.', concepts: ['sodio', 'calculos.na_corregido'] },
        { kind: 'calc', calc: 'osm_calc', inputs: { na: 137, glu: 870, bun: 58 }, ask: 'Calcula la osmolalidad total y compárala con la medida (344).', concepts: ['osmolalidad', 'calculos.osm_calc'] },
        {
          kind: 'mcq',
          cat: 'diagnostico',
          stem: '¿Cuál es el diagnóstico?',
          options: [
            { t: 'EHH (sin cetoacidosis), con hipernatremia oculta y lesión renal prerrenal', why: 'Correcto: glucosa ≥600, efectiva ≈322, β-OHB 1,2, pH 7,35.' },
            { t: 'CAD', why: 'β-OHB <3,0 y pH ≥7,3.', err: 'diferencial' },
            { t: 'Intoxicación por alcoholes (gap osmolar alto)', why: 'Medida 344 vs calculada ≈343: no hay gap osmolar.', err: 'calculo' },
            { t: 'Hiponatremia hipotónica', why: 'La osmolalidad está alta, no baja.', err: 'laboratorio' },
          ],
          answer: 0,
          explain: ['Efectiva = 274 + 48 ≈ 322.', 'Na corregido ≈149.', 'Total ≈ 274 + 48 + 21 = 343 → gap ≈1.'],
          pearl: 'Compara la osmolalidad medida con la calculada: un gap >10 sugiere tóxicos.',
        },
        {
          kind: 'mcq',
          cat: 'secuencia',
          concepts: ['liquidos'],
          stem: '¿Qué harías ahora?',
          options: [
            { t: 'Cristaloide isotónico, reevaluación frecuente, potasio según los niveles e insulina a dosis baja cuando la glucosa deje de bajar', why: 'Correcto.' },
            { t: 'Insulina 0,1 U/kg/h en bolo antes de los líquidos', why: 'El orden es el inverso.', err: 'secuencia' },
            { t: 'Salino hipertónico', why: 'Aumentaría la hiperosmolalidad.', err: 'tratamiento' },
            { t: 'Hemodiálisis urgente', why: 'La lesión renal es prerrenal.' },
          ],
          answer: 0,
          explain: ['Volumen primero.', 'Insulina después, a dosis baja.', 'Metas de descenso gradual.'],
          pearl: 'La creatinina del EHH suele mejorar mucho con la hidratación.',
        },
      ],
    },
  ],
});
