/* Tema: Hipertiroidismo y tirotoxicosis (incluye tormenta tiroidea).
 * Revisión 2026-09-26. Base: ATA 2016. */
SolMed.registry.addTopic({
  id: 'hipertiroidismo',
  name: 'Hipertiroidismo y tirotoxicosis',
  short: 'Hipertiroidismo',
  specialty: 'medicina-interna',
  area: 'endocrinologia',
  group: 'Tiroides',
  reviewed: '2026-09-26',
  sources: ['ata2016', 'harrison22'],
  summary: 'Exceso de hormona tiroidea circulante. La clave es distinguir la hiperproducción (hipertiroidismo) de la liberación o el aporte externo, porque el tratamiento es distinto.',
  subtopics: [
    { id: 'fisio', name: 'Conceptos y causas' },
    { id: 'dx', name: 'Clínica y diagnóstico' },
    { id: 'tx', name: 'Tratamiento' },
    { id: 'esp', name: 'Situaciones especiales' },
    { id: 'tormenta', name: 'Tormenta tiroidea' },
  ],
  concepts: [
    { id: 'definicion', name: 'Tirotoxicosis frente a hipertiroidismo', sub: 'fisio' },
    { id: 'causas', name: 'Causas de tirotoxicosis', sub: 'fisio' },
    { id: 'clinica', name: 'Manifestaciones clínicas', sub: 'dx' },
    { id: 'estrategia', name: 'Estrategia diagnóstica: TSH → T4L/T3 → causa', sub: 'dx' },
    { id: 'graves', name: 'Enfermedad de Graves', sub: 'dx' },
    { id: 'tiroiditis', name: 'Tiroiditis subaguda, silente y posparto', sub: 'dx' },
    { id: 'facticia', name: 'Tirotoxicosis facticia', sub: 'dx' },
    { id: 'betabloqueo', name: 'Betabloqueo', sub: 'tx' },
    { id: 'antitiroideos', name: 'Metimazol y PTU: uso y efectos adversos', sub: 'tx' },
    { id: 'radioyodo', name: 'Radioyodo: indicaciones y contraindicaciones', sub: 'tx' },
    { id: 'cirugia', name: 'Tiroidectomía y sus complicaciones', sub: 'tx' },
    { id: 'embarazo', name: 'Hipertiroidismo en el embarazo', sub: 'esp' },
    { id: 'amiodarona', name: 'Tirotoxicosis por amiodarona', sub: 'esp' },
    { id: 'subclinico', name: 'Hipertiroidismo subclínico', sub: 'esp' },
    { id: 'orbitopatia', name: 'Orbitopatía de Graves', sub: 'esp' },
    { id: 'tormenta_dx', name: 'Tormenta tiroidea: reconocimiento', sub: 'tormenta' },
    { id: 'tormenta_tx', name: 'Tormenta tiroidea: secuencia del tratamiento', sub: 'tormenta' },
  ],
  sheet: [
    {
      title: 'Definición',
      body: [
        '**Tirotoxicosis**: estado clínico por exceso de hormona tiroidea en los tejidos, sea cual sea su origen.',
        '**Hipertiroidismo**: tirotoxicosis por **hiperproducción** de la propia tiroides. Toda hipertiroidismo es tirotoxicosis, pero no al revés.',
      ],
    },
    {
      title: 'Epidemiología relevante',
      body: [['**Graves** es la causa más frecuente de hipertiroidismo (mujeres de 20–50 años).', 'Los nódulos tóxicos (bocio multinodular, adenoma) predominan en personas mayores y en zonas con déficit de yodo.']],
    },
    {
      title: 'Causas',
      body: [
        '**Con captación de yodo alta (hiperproducción)**:',
        ['Graves (TRAb), bocio multinodular tóxico, adenoma tóxico, TSH-oma (raro), hCG (hiperémesis, mola).', 'Inducida por yodo en un tiroides con autonomía (Jod-Basedow, amiodarona tipo 1).'],
        '**Con captación baja**:',
        ['Tiroiditis: subaguda (de Quervain), silente, posparto, por amiodarona tipo 2, por inmunoterapia.', 'Exógena: exceso de levotiroxina o facticia (tiroglobulina baja).', 'Estruma ovárico (raro).'],
      ],
    },
    {
      title: 'Fisiopatología',
      body: [
        [
          'Más hormona → mayor termogénesis, consumo de O₂ y sensibilidad a las catecolaminas (más receptores β).',
          'Graves: los anticuerpos **estimulan el receptor de TSH** → hiperplasia difusa y síntesis aumentada; los fibroblastos orbitarios y pretibiales también expresan el receptor → orbitopatía y dermopatía.',
          'Tiroiditis: la inflamación destruye folículos → liberación de hormona **preformada** (transitoria), sin síntesis.',
        ],
      ],
    },
    {
      title: 'Manifestaciones clínicas',
      body: [
        [
          'Nerviosismo, temblor, insomnio, intolerancia al calor, sudoración, pérdida de peso con apetito aumentado, hiperdefecación.',
          '**Taquicardia**, fibrilación auricular (sobre todo en ancianos), hipertensión sistólica, insuficiencia cardíaca de alto gasto.',
          'Retracción palpebral (cualquier tirotoxicosis) frente a **orbitopatía** (solo Graves): proptosis, diplopía, inflamación.',
          'Debilidad muscular proximal, osteoporosis, oligomenorrea.',
          'Parálisis periódica hipopotasémica (más frecuente en varones asiáticos).',
          '**Ancianos**: forma «apática» con astenia, pérdida de peso y FA, sin hiperactividad.',
        ],
      ],
    },
    {
      title: 'Diagnóstico',
      body: [
        [
          '**TSH suprimida** → medir T4 libre y T3 total.',
          'T4L normal + T3 alta = tirotoxicosis por T3 (nódulos o Graves incipiente). TSH baja con T4L y T3 normales = subclínico.',
          '**Causa**: si la clínica de Graves es clara (orbitopatía, bocio difuso con soplo) basta; si no, **TRAb** o **captación de yodo** con gammagrafía (y Doppler tiroideo).',
          'Captación baja: tiroglobulina alta (tiroiditis) frente a baja (facticia); VSG alta y dolor (subaguda).',
          'Embarazo o lactancia: captación **contraindicada** → TRAb y Doppler.',
        ],
      ],
    },
    {
      title: 'Diagnóstico diferencial',
      body: [
        [
          'TSH baja sin tirotoxicosis: enfermedad no tiroidea, glucocorticoides, dopamina, primer trimestre del embarazo (hCG), hipotiroidismo central.',
          'Ansiedad, feocromocitoma, abstinencia alcohólica, simpaticomiméticos.',
          'Interferencia de la **biotina** en los inmunoensayos (puede simular un Graves).',
        ],
      ],
    },
    {
      title: 'Tratamiento',
      body: [
        '**Síntomas (cualquier causa)**: **betabloqueante** (propranolol, atenolol); si están contraindicados, un antagonista del calcio no dihidropiridínico.',
        '**Hipertiroidismo** (Graves, nódulos): tres opciones definitivas o de control:',
        [
          '**Metimazol** (de elección): Graves 12–18 meses con posibilidad de remisión. Efectos adversos: exantema, **agranulocitosis** (fiebre u odinofagia → suspender y hemograma), hepatotoxicidad colestásica, **teratógeno en el 1.er trimestre**.',
          '**PTU**: solo en el 1.er trimestre del embarazo, la tormenta tiroidea o la intolerancia menor al metimazol. Riesgo de **hepatotoxicidad grave**.',
          '**Radioyodo (¹³¹I)**: definitivo; causa hipotiroidismo. **Contraindicado** en el embarazo y la lactancia; evitar en la orbitopatía activa moderada-grave (con profilaxis esteroidea si es leve y activa). Se suspende el metimazol días antes.',
          '**Tiroidectomía**: bocio grande o compresivo, sospecha de malignidad, orbitopatía grave, embarazo que no responde (2.º trimestre), preferencia. Llegar eutiroideo (metimazol ± yoduro preoperatorio en Graves). Complicaciones: **hipocalcemia** por hipoparatiroidismo y lesión del nervio laríngeo recurrente.',
        ],
        '**Tiroiditis**: betabloqueo; AINE o prednisona en la subaguda. **No** antitiroideos ni radioyodo. Vigilar la fase hipotiroidea.',
      ],
    },
    {
      title: 'Situaciones especiales',
      body: [
        [
          '**Embarazo**: PTU en el 1.er trimestre y metimazol después (o mantener PTU según el caso); objetivo T4L en el límite alto de la normalidad con la mínima dosis; TRAb para valorar el riesgo fetal. Distinguir la tirotoxicosis gestacional transitoria (hCG, hiperémesis) de Graves.',
          '**Amiodarona**: tipo 1 (exceso de yodo en una glándula con autonomía o Graves latente; Doppler con flujo aumentado → antitiroideos, ± perclorato) frente a tipo 2 (tiroiditis destructiva; flujo ausente → glucocorticoides). Las formas mixtas son frecuentes.',
          '**Subclínico**: tratar sobre todo si la TSH es <0,1 en mayores de 65 años, cardiopatía u osteoporosis.',
          '**Orbitopatía**: dejar de fumar; selenio en formas leves; glucocorticoides IV o terapias biológicas en las moderadas-graves activas.',
        ],
      ],
    },
    {
      title: 'Tormenta tiroidea',
      body: [
        'Tirotoxicosis descompensada con disfunción de órganos: fiebre, taquicardia o FA, insuficiencia cardíaca, agitación o delirio, vómitos, diarrea, ictericia. Precipitantes: infección, cirugía, parto, radioyodo, suspensión de antitiroideos, contraste yodado. **Burch-Wartofsky ≥45** apoya el diagnóstico (25–44: inminente). Diagnóstico **clínico**.',
        '**Secuencia (ATA 2016)**:',
        [
          '**Betabloqueante** (propranolol, que además reduce la conversión de T4 a T3; esmolol en la UCI); cuidado en la insuficiencia cardíaca con FE baja.',
          '**Tionamida**: PTU 500–1000 mg de carga y luego 250 mg cada 4 h (o metimazol a dosis alta).',
          '**Yodo inorgánico** (SSKI o Lugol) **al menos 1 h después** de la tionamida, para no aportar sustrato a la síntesis.',
          '**Glucocorticoides**: hidrocortisona 300 mg IV de carga y luego 100 mg cada 8 h (bloquea la conversión de T4 a T3 y cubre la reserva suprarrenal).',
          'Soporte: enfriamiento, **paracetamol** (no aspirina), líquidos, tratar la FA y la insuficiencia cardíaca, tratar el precipitante. Si es refractaria: plasmaféresis o tiroidectomía.',
        ],
      ],
    },
    {
      title: 'Monitorización y metas',
      body: [['Con antitiroideos: T4L y T3 cada 4–6 semanas al principio (la TSH puede tardar meses en recuperarse).', 'Hemograma basal y ante fiebre u odinofagia; pruebas hepáticas si hay síntomas.', 'Tras el radioyodo: TSH y T4L a las 4–8 semanas; la mayoría acaba con hipotiroidismo que se trata con levotiroxina.']],
    },
    {
      title: 'Errores frecuentes',
      body: [
        [
          'Usar la TSH para ajustar los antitiroideos al principio (sigue suprimida semanas o meses).',
          'Tratar una tiroiditis con metimazol.',
          'Dar yodo antes de la tionamida en la tormenta tiroidea.',
          'Usar aspirina como antitérmico en la tormenta.',
          'Radioyodo en el embarazo.',
          'No advertir de la agranulocitosis al iniciar el metimazol.',
        ],
      ],
    },
    {
      title: 'Pronóstico',
      body: ['Graves: remisión con antitiroideos en una minoría de pacientes; recaídas frecuentes. La tormenta tiroidea tiene una mortalidad elevada incluso con tratamiento.'],
    },
    {
      title: 'Perlas de alto rendimiento',
      body: [
        [
          '**Orbitopatía = Graves.** La retracción palpebral no.',
          'Captación baja: tiroglobulina alta → tiroiditis; baja → facticia.',
          'PTU: 1.er trimestre y tormenta. Metimazol: el resto.',
          'Tormenta: **β → tionamida → (≥1 h) yodo → corticoide**.',
          'Fiebre u odinofagia con metimazol → suspender y hemograma urgente.',
        ],
      ],
    },
  ],
  items: [
    {
      id: 'q01',
      type: 'mcq',
      sub: 'dx',
      concepts: ['estrategia', 'tiroiditis', 'definicion'],
      diff: 2,
      cat: 'diferencial',
      stem: 'Mujer de 34 años con palpitaciones, temblor y dolor en la parte anterior del cuello irradiado a la mandíbula tras un cuadro gripal. Tiroides dolorosa. TSH <0,01, T4L 3,2 ng/dL, VSG 78 mm/h. Captación de yodo a las 24 h: 2 %. ¿Diagnóstico y tratamiento?',
      options: [
        { t: 'Tiroiditis subaguda (de Quervain): betabloqueo y AINE (o prednisona si no mejora)', why: 'Correcto: dolor, VSG alta, captación baja.' },
        { t: 'Graves: metimazol', why: 'La captación baja y el dolor no son de Graves; el metimazol no sirve sin síntesis activa.', err: 'diferencial' },
        { t: 'Adenoma tóxico hemorrágico: radioyodo', why: 'La captación baja no permitiría el radioyodo y no hay nódulo.', err: 'diferencial' },
        { t: 'Tirotoxicosis facticia: suspender la levotiroxina', why: 'El dolor y la VSG alta sugieren inflamación, no hormona exógena.', err: 'diferencial' },
      ],
      answer: 0,
      explain: ['Tirotoxicosis + captación baja → tiroiditis o exógena.', 'Dolor + VSG alta + antecedente viral → subaguda.', 'Tratamiento sintomático y antiinflamatorio.', 'Anticipar la fase hipotiroidea.'],
      key: ['Dolor tiroideo', 'VSG 78', 'Captación 2 %'],
      pearl: 'Los antitiroideos no sirven en las tiroiditis: **no hay síntesis que bloquear**.',
      remember: 'Tiroides dolorosa + VSG alta + captación baja = de Quervain.',
      compare: ['tiroiditis-graves', 'hiper-tirotox'],
    },
    {
      id: 'q02',
      type: 'mcq',
      sub: 'tx',
      concepts: ['antitiroideos'],
      diff: 2,
      cat: 'complicaciones',
      stem: 'Paciente con Graves en tratamiento con metimazol desde hace 6 semanas. Presenta fiebre de 39 °C y odinofagia. ¿Qué haces?',
      options: [
        { t: 'Suspender el metimazol y pedir un hemograma urgente', why: 'Correcto: sospecha de agranulocitosis; si se confirma, antibióticos de amplio espectro y no volver a usar tionamidas.' },
        { t: 'Continuar el metimazol y dar amoxicilina', why: 'Si hay agranulocitosis, el riesgo de sepsis es muy alto.', err: 'complicaciones' },
        { t: 'Cambiar a PTU de inmediato', why: 'Hay reactividad cruzada: está contraindicado en la agranulocitosis.', err: 'tratamiento' },
        { t: 'Aumentar la dosis por posible tormenta tiroidea', why: 'La fiebre y la odinofagia apuntan primero a agranulocitosis.' },
      ],
      answer: 0,
      explain: ['La agranulocitosis suele aparecer en los primeros 3 meses.', 'Se advierte al paciente al iniciar el fármaco.', 'Opciones definitivas después: radioyodo o cirugía.'],
      pearl: 'Da la instrucción **por escrito** al iniciar un antitiroideo: fiebre o dolor de garganta → suspender y hemograma.',
      remember: 'Fiebre + odinofagia con tionamida = hemograma urgente.',
    },
    {
      id: 'q03',
      type: 'mcq',
      sub: 'esp',
      concepts: ['embarazo', 'antitiroideos'],
      diff: 2,
      cat: 'tratamiento',
      stem: 'Mujer de 29 años con Graves activo y embarazo de 7 semanas. ¿Qué tratamiento antitiroideo es el adecuado?',
      options: [
        { t: 'PTU durante el primer trimestre, a la mínima dosis que mantenga la T4L en el límite alto de la normalidad', why: 'Correcto: el metimazol es teratógeno en el primer trimestre.' },
        { t: 'Metimazol a dosis alta', why: 'Embriopatía por metimazol (aplasia cutis, atresia de coanas o esofágica).', err: 'tratamiento' },
        { t: 'Radioyodo', why: 'Contraindicado en el embarazo.', err: 'tratamiento' },
        { t: 'Solo propranolol durante todo el embarazo', why: 'Insuficiente en el Graves activo; el uso prolongado se asocia a retraso del crecimiento.' },
      ],
      answer: 0,
      explain: ['1.er trimestre: PTU.', 'Después: metimazol (menor hepatotoxicidad) o mantener PTU según el caso.', 'Objetivo: T4L en el límite alto de la normalidad para evitar el hipotiroidismo fetal.', 'TRAb para valorar el riesgo fetal y neonatal.'],
      pearl: 'Los antitiroideos **atraviesan la placenta**: sobretratar causa hipotiroidismo y bocio fetal.',
      remember: 'Embarazo: PTU en el 1.er trimestre.',
    },
    {
      id: 'q04',
      type: 'mcq',
      sub: 'tormenta',
      concepts: ['tormenta_tx'],
      diff: 3,
      cat: 'secuencia',
      stem: 'En la tormenta tiroidea, ¿por qué el yodo inorgánico (SSKI o Lugol) se administra al menos una hora después de la tionamida?',
      options: [
        { t: 'Porque si se da antes, la glándula lo usa como sustrato para sintetizar más hormona', why: 'Correcto: la tionamida bloquea primero la organificación.' },
        { t: 'Porque el yodo inactiva la tionamida', why: 'No es el mecanismo.' },
        { t: 'Porque el yodo causa hipotensión si se da junto al betabloqueante', why: 'Falso.' },
        { t: 'Porque el yodo tarda una hora en absorberse', why: 'No es la razón.' },
      ],
      answer: 0,
      explain: ['Tionamida → bloquea la síntesis.', 'El yodo, después → bloquea la **liberación** (efecto Wolff-Chaikoff).', 'Si el orden se invierte → más sustrato y más hormona.'],
      pearl: 'Orden: **betabloqueante → tionamida → (≥1 h) yodo → glucocorticoide**, más soporte.',
      remember: 'Primero bloquear la síntesis, después la liberación.',
    },
    {
      id: 'q05',
      type: 'mcq',
      sub: 'tormenta',
      concepts: ['tormenta_dx'],
      diff: 2,
      cat: 'diagnostico',
      stem: 'Varón de 38 años con Graves que abandonó el metimazol. Tras una neumonía: T 40,1 °C, FC 162 (FA), delirio, vómitos, bilirrubina 3,1 mg/dL, crepitantes y edemas. T4L 4,1 ng/dL. ¿Cómo lo interpretas?',
      options: [
        { t: 'Tormenta tiroidea: tratar de inmediato sin esperar más pruebas', why: 'Correcto: disfunción del SNC, termorregulación, cardiovascular y hepática; Burch-Wartofsky muy por encima de 45.' },
        { t: 'Tirotoxicosis no complicada: ajustar el metimazol en consulta', why: 'Hay disfunción de múltiples órganos.', err: 'diferencial' },
        { t: 'Solo sepsis: la T4L no es suficientemente alta para una tormenta', why: 'La tormenta no se define por la cifra de T4.', err: 'laboratorio' },
        { t: 'Esperar a la T3 para confirmar', why: 'El diagnóstico es clínico.', err: 'razonamiento' },
      ],
      answer: 0,
      explain: ['Fiebre alta + taquicardia/FA + IC + delirio + síntomas digestivos + ictericia.', 'Precipitantes: infección + abandono del tratamiento.', 'La cifra hormonal no distingue la tormenta de la tirotoxicosis simple.'],
      pearl: 'La tormenta se define por la **disfunción de órganos**, no por la T4.',
      remember: 'Burch-Wartofsky ≥45 = tormenta probable.',
      compare: ['tormenta-tirotox', 'coma-tormenta'],
    },
    {
      id: 'q06',
      type: 'mcq',
      sub: 'dx',
      concepts: ['facticia', 'estrategia'],
      diff: 3,
      cat: 'diferencial',
      stem: 'Enfermera de 31 años con palpitaciones y pérdida de peso. Tiroides no palpable ni dolorosa. TSH suprimida, T4L alta, captación de yodo 1 %, **tiroglobulina indetectable** (anticuerpos antitiroglobulina negativos). ¿Diagnóstico?',
      options: [
        { t: 'Tirotoxicosis facticia (ingesta de levotiroxina)', why: 'Correcto: captación baja con tiroglobulina baja indica hormona exógena.' },
        { t: 'Tiroiditis silente', why: 'En la tiroiditis la tiroglobulina está **alta** (destrucción folicular).', err: 'diferencial' },
        { t: 'Graves', why: 'La captación sería alta.', err: 'diferencial' },
        { t: 'Estruma ovárico', why: 'Raro; la tiroglobulina podría estar elevada.' },
      ],
      answer: 0,
      explain: ['Captación baja → no hay síntesis tiroidea.', 'Tiroglobulina baja → la hormona no procede de la tiroides.', 'Comprobar que los anticuerpos antitiroglobulina son negativos (si no, falsean la medición).'],
      pearl: 'Pregunta con tacto por el acceso a medicamentos y los productos para adelgazar.',
      remember: 'Captación baja + tiroglobulina baja = exógena.',
      compare: ['hiper-tirotox'],
    },
    {
      id: 'q07',
      type: 'mcq',
      sub: 'tx',
      concepts: ['radioyodo', 'orbitopatia'],
      diff: 2,
      cat: 'tratamiento',
      stem: 'Mujer fumadora de 45 años con Graves y orbitopatía activa moderada-grave (proptosis, diplopía intermitente). ¿Qué opción definitiva debería evitarse?',
      options: [
        { t: 'Radioyodo', why: 'Correcto: puede empeorar la orbitopatía activa moderada-grave (más aún en fumadoras).' },
        { t: 'Tiroidectomía total', why: 'Es una opción adecuada en este contexto.' },
        { t: 'Metimazol a largo plazo', why: 'Es aceptable.' },
        { t: 'Dejar de fumar', why: 'Es imprescindible, no algo que evitar.' },
      ],
      answer: 0,
      explain: ['El radioyodo aumenta transitoriamente los TRAb y puede agravar la orbitopatía.', 'En la orbitopatía leve y activa se puede usar con profilaxis esteroidea.', 'El tabaco empeora la orbitopatía.'],
      pearl: 'Abandonar el tabaco es la intervención más eficaz y más olvidada en la orbitopatía.',
      remember: 'Orbitopatía activa moderada-grave → no radioyodo.',
      compare: ['graves-otras'],
    },
    {
      id: 'q08',
      type: 'mcq',
      sub: 'esp',
      concepts: ['amiodarona'],
      diff: 3,
      cat: 'diferencial',
      stem: 'Varón de 70 años con amiodarona desde hace 2 años, sin bocio ni nódulos previos. Tirotoxicosis nueva. Doppler tiroideo: vascularización **ausente**. ¿Qué tipo y qué tratamiento?',
      options: [
        { t: 'Tipo 2 (tiroiditis destructiva): glucocorticoides (prednisona)', why: 'Correcto: glándula previamente normal y ausencia de flujo en el Doppler.' },
        { t: 'Tipo 1: metimazol a dosis alta', why: 'El tipo 1 suele darse con bocio o autonomía previa y flujo aumentado.', err: 'diferencial' },
        { t: 'Radioyodo', why: 'La captación es baja por la carga de yodo: no es eficaz.', err: 'tratamiento' },
        { t: 'Solo suspender la amiodarona y esperar', why: 'La suspensión no siempre es posible ni suficiente (la amiodarona tiene una vida media muy larga).' },
      ],
      answer: 0,
      explain: ['Tipo 1: exceso de síntesis inducido por yodo (bocio o autonomía previos, flujo ↑) → tionamidas ± perclorato.', 'Tipo 2: destructiva (flujo ↓) → glucocorticoides.', 'Mixta: combinación de ambos.'],
      pearl: 'La decisión sobre suspender la amiodarona se toma **con cardiología**.',
      remember: 'Amiodarona: flujo ↑ = tipo 1 (tionamida); flujo ↓ = tipo 2 (corticoide).',
    },
    {
      id: 'q09',
      type: 'mcq',
      sub: 'tx',
      concepts: ['cirugia'],
      diff: 2,
      cat: 'complicaciones',
      stem: 'A las 24 h de una tiroidectomía total, la paciente refiere hormigueo peribucal y en los dedos. Signo de Chvostek positivo. ¿Qué complicación sospechas?',
      options: [
        { t: 'Hipocalcemia por hipoparatiroidismo', why: 'Correcto: lesión o extirpación de las paratiroides.' },
        { t: 'Lesión del nervio laríngeo recurrente', why: 'Produce disfonía, no parestesias.' },
        { t: 'Tormenta tiroidea posoperatoria', why: 'No explica los signos de tetania.' },
        { t: 'Hipotiroidismo agudo', why: 'La T4 tiene una vida media de ~7 días: no produce síntomas en 24 h.' },
      ],
      answer: 0,
      explain: ['Medir calcio (corregido o iónico) y PTH.', 'Si hay síntomas: calcio IV o calcio oral más calcitriol según la gravedad.'],
      pearl: 'La **disfonía** tras la tiroidectomía sugiere lesión del laríngeo recurrente; el estridor bilateral es una urgencia.',
      remember: 'Parestesias tras la tiroidectomía → calcio.',
    },
    {
      id: 'q10',
      type: 'mcq',
      sub: 'dx',
      concepts: ['graves', 'clinica'],
      diff: 1,
      cat: 'concepto',
      stem: '¿Cuál de estos hallazgos es **específico** de la enfermedad de Graves frente a otras causas de tirotoxicosis?',
      options: [
        { t: 'Orbitopatía con proptosis', why: 'Correcto: se debe a la autoinmunidad frente al receptor de TSH de los fibroblastos orbitarios.' },
        { t: 'Retracción palpebral', why: 'Puede darse en cualquier tirotoxicosis (hiperactividad simpática).', err: 'diferencial' },
        { t: 'Taquicardia', why: 'Es inespecífica.' },
        { t: 'Temblor fino', why: 'Es inespecífico.' },
      ],
      answer: 0,
      explain: ['Orbitopatía, dermopatía pretibial y acropaquia tiroidea → solo Graves.', 'La retracción palpebral y la mirada fija: cualquier tirotoxicosis.'],
      pearl: 'Con orbitopatía y tirotoxicosis, la causa ya está clara: no hace falta gammagrafía.',
      remember: 'Proptosis = Graves.',
      compare: ['graves-otras'],
    },
    {
      id: 'q11',
      type: 'mcq',
      sub: 'tx',
      concepts: ['betabloqueo', 'antitiroideos'],
      diff: 2,
      cat: 'laboratorio',
      stem: 'Graves en tratamiento con metimazol desde hace 6 semanas: clínicamente mejor. TSH 0,01 (sigue suprimida), T4L 1,2 ng/dL (normal), T3 normal. ¿Qué haces?',
      options: [
        { t: 'Reducir la dosis de metimazol; la TSH puede tardar meses en recuperarse, guíate por T4L y T3', why: 'Correcto: la supresión de los tirotropos persiste tras normalizarse las hormonas.' },
        { t: 'Aumentar el metimazol porque la TSH sigue suprimida', why: 'Provocaría hipotiroidismo.', err: 'laboratorio' },
        { t: 'Añadir radioyodo', why: 'No hay fracaso terapéutico.' },
        { t: 'Suspender el metimazol', why: 'Graves requiere 12–18 meses de tratamiento.' },
      ],
      answer: 0,
      explain: ['Al principio del tratamiento, la TSH no es fiable.', 'Se ajusta con T4L y T3.', 'Pauta de dosis decreciente hasta la dosis de mantenimiento.'],
      pearl: 'Durante los primeros meses, **la TSH va rezagada**: no persigas la TSH.',
      remember: 'Ajuste inicial con T4L y T3.',
    },

    // ---------- Casos ----------
    {
      id: 'c01',
      type: 'case',
      sub: 'dx',
      concepts: ['graves', 'estrategia', 'antitiroideos', 'betabloqueo'],
      diff: 2,
      cat: 'integracion',
      title: 'Palpitaciones y ojos saltones',
      patient: { age: 28, sex: 'F' },
      vignette: ['Mujer de 28 años con 3 meses de palpitaciones, pérdida de 6 kg con buen apetito, sudoración, insomnio e irritabilidad. Su pareja nota que «tiene los ojos más grandes». No toma fármacos. No planea un embarazo a corto plazo; usa anticonceptivos orales.'],
      vitals: { PA: '142/68 mmHg', FC: '118 lpm, rítmico', T: '37,2 °C', peso: '54 kg' },
      exam: 'Temblor fino. Bocio difuso con soplo. Proptosis bilateral leve sin diplopía, retracción palpebral. Piel caliente y húmeda.',
      labs: [
        { p: 'tsh', v: 0.01 },
        { p: 't4l', v: 3.9 },
        { p: 't3', v: 420 },
        { p: 'trab', text: 'Positivos (12 UI/L)', flag: 'H' },
        { p: 'k', v: 4.1 },
        { p: 'ca', v: 10.2 },
      ],
      questions: [
        {
          stem: '¿Necesitas una gammagrafía para confirmar la causa?',
          cat: 'diagnostico',
          options: [
            { t: 'No: orbitopatía + bocio difuso con soplo + TRAb positivos confirman Graves', why: 'Correcto.' },
            { t: 'Sí: siempre se necesita la captación', why: 'Solo cuando la causa no está clara.', err: 'razonamiento' },
            { t: 'Sí: para descartar un cáncer', why: 'No hay nódulos.' },
            { t: 'No: es una tiroiditis', why: 'La orbitopatía y los TRAb indican Graves.', err: 'diferencial' },
          ],
          answer: 0,
          explain: ['Graves con clínica típica: no hace falta imagen funcional.', 'El cociente T3/T4 alto también apoya la hiperproducción.'],
          key: ['Proptosis', 'Bocio con soplo', 'TRAb positivos'],
          altered: ['TSH suprimida', 'T4L y T3 altas'],
          pearl: 'Las pruebas **no deben retrasar** el betabloqueo sintomático.',
        },
        {
          stem: '¿Cuál es el tratamiento inicial más adecuado?',
          cat: 'tratamiento',
          concepts: ['antitiroideos', 'betabloqueo'],
          options: [
            { t: 'Propranolol + metimazol, con advertencia escrita sobre la agranulocitosis y hemograma y pruebas hepáticas basales', why: 'Correcto.' },
            { t: 'Radioyodo inmediato', why: 'Es una opción definitiva, pero la orbitopatía activa y la preferencia de la paciente pesan; no es lo más adecuado como único paso inicial.', err: 'tratamiento' },
            { t: 'PTU como primera elección', why: 'El PTU se reserva para el 1.er trimestre y la tormenta.', err: 'tratamiento' },
            { t: 'Levotiroxina para frenar la TSH', why: 'Absurdo.' },
          ],
          answer: 0,
          explain: ['Betabloqueo para los síntomas.', 'Metimazol: controla la hiperproducción y permite una posible remisión.', 'Seguimiento con T4L y T3.'],
          pearl: 'Si más adelante busca embarazo, planifica: considera un tratamiento definitivo antes o el cambio a PTU en el primer trimestre.',
        },
      ],
    },
    {
      id: 'c02',
      type: 'case',
      sub: 'esp',
      concepts: ['tiroiditis', 'embarazo', 'definicion'],
      diff: 3,
      cat: 'integracion',
      title: 'Cuatro meses después del parto',
      patient: { age: 32, sex: 'F' },
      vignette: ['Mujer de 32 años, 4 meses tras el parto, lactancia materna. Palpitaciones, ansiedad y pérdida de peso. Tiroides pequeña e indolora. Sin oftalmopatía.'],
      vitals: { FC: '108 lpm', PA: '124/72 mmHg' },
      labs: [
        { p: 'tsh', v: 0.02 },
        { p: 't4l', v: 2.4 },
        { p: 't3', v: 190 },
        { p: 'trab', text: 'Negativos', flag: 'N' },
        { p: 'antitpo', text: 'Positivos', flag: 'H' },
        { p: 'vsg', v: 12 },
      ],
      questions: [
        {
          stem: '¿Cuál es el diagnóstico más probable?',
          options: [
            { t: 'Tiroiditis posparto (fase tirotóxica)', why: 'Correcto: posparto, indolora, TRAb negativos, anti-TPO positivos, predominio de T4.' },
            { t: 'Graves posparto', why: 'Los TRAb negativos y la ausencia de soplo, bocio u orbitopatía lo hacen improbable.', err: 'diferencial' },
            { t: 'Tiroiditis subaguda', why: 'No hay dolor y la VSG es normal.', err: 'diferencial' },
            { t: 'Tirotoxicosis gestacional', why: 'Ocurre en el primer trimestre del embarazo, no después del parto.', err: 'diferencial' },
          ],
          answer: 0,
          explain: ['1–6 meses después del parto.', 'Indolora; anti-TPO positivos.', 'Tirotoxicosis → posible fase hipotiroidea → recuperación (algunas pacientes quedan hipotiroideas).'],
          pearl: 'Durante la lactancia la gammagrafía con I-131 está contraindicada; con Tc-99m obliga a suspender temporalmente la lactancia. Los **TRAb** suelen bastar.',
        },
        {
          stem: '¿Qué tratamiento?',
          cat: 'tratamiento',
          concepts: ['tiroiditis', 'betabloqueo'],
          options: [
            { t: 'Betabloqueante compatible con la lactancia (por ejemplo, propranolol a la menor dosis eficaz) y control de TSH/T4L cada 4–8 semanas', why: 'Correcto: tratamiento sintomático y vigilancia de la fase hipotiroidea.' },
            { t: 'Metimazol', why: 'Sin síntesis aumentada, no es útil.', err: 'tratamiento' },
            { t: 'Radioyodo', why: 'Contraindicado en la lactancia e inútil sin captación.', err: 'tratamiento' },
            { t: 'Tiroidectomía', why: 'Es un cuadro transitorio.' },
          ],
          answer: 0,
          explain: ['Tiroiditis: betabloqueo si hay síntomas.', 'Controles periódicos para detectar el hipotiroidismo posterior.', 'Riesgo de recurrencia en embarazos futuros y de hipotiroidismo permanente.'],
          pearl: 'Mujeres con anti-TPO positivos: vigila la TSH después de cada parto.',
        },
      ],
    },

    // ---------- Progresivo: tormenta tiroidea ----------
    {
      id: 'p01',
      type: 'progressive',
      sub: 'tormenta',
      concepts: ['tormenta_dx', 'tormenta_tx'],
      diff: 3,
      cat: 'secuencia',
      title: 'La tormenta',
      stages: [
        {
          id: 's1',
          title: 'Urgencias',
          text: ['Mujer de 40 años con Graves diagnosticado hace 1 año; dejó el metimazol hace 2 meses. Tras una infección urinaria: agitación, T 39,8 °C, FC 150 (FA rápida), diarrea, disnea con crepitantes bibasales. Ictericia leve.'],
          vitals: { T: '39,8 °C', FC: '150 lpm (FA)', PA: '146/60 mmHg', FR: '28 rpm', SatO2: '93 %' },
          q: {
            stem: '¿Cuál es la conducta inicial?',
            options: [
              { t: 'Tratar ya como tormenta tiroidea (UCI), con muestras para TSH, T4L y T3 sin esperar los resultados', why: 'Correcto: el diagnóstico es clínico.' },
              { t: 'Pedir TSH y T4L y esperar antes de tratar', why: 'Retrasar el tratamiento aumenta la mortalidad.', err: 'razonamiento', next: 's1b' },
              { t: 'Cardioversión eléctrica inmediata como tratamiento principal', why: 'La FA tirotóxica recidiva mientras persiste la tirotoxicosis; la cardioversión está indicada solo si hay inestabilidad grave.' },
              { t: 'Aspirina para la fiebre', why: 'La aspirina desplaza la T4 de la TBG: usa paracetamol.', err: 'tratamiento' },
            ],
            answer: 0,
            explain: ['Burch-Wartofsky: temperatura, SNC, digestivo o hepático, FC, IC, FA y precipitante → puntuación muy >45.', 'UCI y tratamiento multimodal.'],
            pearl: 'Diagnóstico **clínico**; la analítica confirma después.',
          },
          goto: 's2',
        },
        {
          id: 's1b',
          title: '2 horas después',
          tone: 'alert',
          text: ['Aumenta la agitación, la FC es de 170 y aparece hipotensión (88/50). Se trasladan a la UCI.'],
          q: {
            stem: '¿Qué aprendizaje?',
            options: [
              { t: 'La sospecha clínica debe desencadenar tratamiento inmediato', why: 'Correcto.' },
              { t: 'Había que pedir gammagrafía', why: 'No tiene papel en la emergencia.' },
              { t: 'La hipotensión contraindica cualquier tratamiento', why: 'Hay que ajustar el betabloqueo (esmolol, dosis prudentes) y tratar todo lo demás.' },
              { t: 'Nada: es la evolución natural', why: 'El retraso contribuyó.' },
            ],
            answer: 0,
            explain: ['La tormenta tiene una mortalidad elevada; cada hora cuenta.'],
            pearl: 'En la hipotensión o la IC con FE baja, usa **esmolol** titulable o dosis bajas.',
          },
          goto: 's2',
        },
        {
          id: 's2',
          title: 'Orden del tratamiento',
          text: ['Ingresada en la UCI. Tiene vía oral o sonda nasogástrica disponible.'],
          q: {
            stem: '¿Cuál es la secuencia correcta?',
            options: [
              { t: 'Betabloqueante → PTU 500–1000 mg de carga → yodo (SSKI/Lugol) al menos 1 h después → hidrocortisona 300 mg IV → soporte y tratamiento de la infección', why: 'Correcto.' },
              { t: 'Lugol primero para frenar la liberación, después PTU', why: 'El yodo antes de la tionamida aporta sustrato para más síntesis.', err: 'secuencia', next: 's3b' },
              { t: 'Radioyodo urgente', why: 'Tarda semanas en actuar y puede empeorar la tormenta.', err: 'tratamiento' },
              { t: 'Solo betabloqueante y antibiótico', why: 'Insuficiente.', err: 'tratamiento' },
            ],
            answer: 0,
            explain: ['β: controla los efectos adrenérgicos (propranolol además frena la conversión de T4 a T3).', 'Tionamida: bloquea la síntesis (PTU también la conversión periférica).', 'Yodo: bloquea la liberación.', 'Corticoide: frena la conversión y cubre la reserva suprarrenal.'],
            pearl: 'Recuerda la regla: **β → tionamida → (≥1 h) yodo → corticoide**.',
          },
          goto: 's3',
        },
        {
          id: 's3b',
          title: 'Complicación',
          tone: 'alert',
          text: ['Tras el yodo sin tionamida previa, a las 12 h la clínica no mejora e incluso empeora la taquicardia.'],
          q: {
            stem: '¿Qué explicación y corrección?',
            options: [
              { t: 'El yodo sin bloqueo previo de la síntesis puede aumentar la producción hormonal: iniciar tionamida ya y mantener el yodo después', why: 'Correcto.' },
              { t: 'Suspender todo', why: 'No.' },
              { t: 'Aumentar solo el Lugol', why: 'Empeora el problema.' },
              { t: 'Añadir levotiroxina', why: 'Absurdo.' },
            ],
            answer: 0,
            explain: ['La tionamida debe preceder al yodo.'],
            pearl: 'El orden de los fármacos en la tormenta **no es un detalle**.',
          },
          goto: 's3',
        },
        {
          id: 's3',
          title: 'Evolución',
          text: ['A las 48 h: T 37,6 °C, FC 98 (FA con respuesta controlada), orientada. Se busca un tratamiento definitivo.'],
          q: {
            stem: '¿Qué tratamiento definitivo es razonable tras estabilizarla?',
            options: [
              { t: 'Tiroidectomía (tras alcanzar el eutiroidismo) o radioyodo cuando esté estable, dado que la adherencia al metimazol fue mala', why: 'Correcto: tratamiento definitivo tras una tormenta.' },
              { t: 'Suspender todo tratamiento al alta', why: 'Recaída segura.', err: 'tratamiento' },
              { t: 'Solo propranolol a largo plazo', why: 'No trata la hiperproducción.', err: 'tratamiento' },
              { t: 'Levotiroxina', why: 'No.' },
            ],
            answer: 0,
            explain: ['Tras una tormenta suele preferirse el tratamiento definitivo.', 'Preparación: eutiroidismo antes de la cirugía.'],
            pearl: 'Tras la tormenta, **evita el riesgo de repetición**: tratamiento definitivo y educación.',
          },
        },
        {
          id: 's4',
          title: 'Cierre',
          end: true,
          text: ['Alta con metimazol, betabloqueante, anticoagulación valorada según el CHA₂DS₂-VASc y tiroidectomía programada.'],
        },
      ],
    },

    // ---------- Razonamiento ----------
    {
      id: 'r01',
      type: 'reasoning',
      sub: 'dx',
      concepts: ['estrategia', 'definicion', 'causas'],
      diff: 2,
      cat: 'razonamiento',
      title: 'TSH suprimida: ¿y ahora qué?',
      vignette: ['Varón de 67 años con fibrilación auricular de reciente comienzo y pérdida de peso. TSH <0,01 mUI/L. Sin oftalmopatía. Se palpan varios nódulos tiroideos.'],
      prompts: [
        {
          q: '¿Qué pruebas pedirías a continuación y qué patrón esperas?',
          expected: 'T4 libre y T3 total (esperables altas; en los nódulos tóxicos es frecuente el predominio de T3). Para la causa: captación con gammagrafía (patrón parcheado en el bocio multinodular tóxico) y ecografía; TRAb si hay dudas de Graves.',
          points: [
            { t: 'T4 libre y T3', kw: ['t4', 't3', 'libre'] },
            { t: 'Gammagrafía o captación de yodo', kw: ['gammagraf', 'captacion', 'centellogra', 'yodo radiactivo'] },
            { t: 'Ecografía tiroidea', kw: ['ecograf', 'eco'] },
            { t: 'TRAb si hay dudas de Graves', kw: ['trab', 'tsi', 'anticuerpos contra el receptor'] },
          ],
        },
        {
          q: '¿Cuál es la causa más probable y qué tratamiento definitivo propondrías?',
          expected: 'Bocio multinodular tóxico (edad, nódulos, sin oftalmopatía). No remite con antitiroideos: tratamiento definitivo con radioyodo o cirugía (si hay bocio compresivo o sospecha de malignidad); metimazol para controlar antes o como alternativa a largo plazo en pacientes seleccionados. Betabloqueo y anticoagulación según el riesgo embólico.',
          points: [
            { t: 'Bocio multinodular tóxico', kw: ['multinodular', 'bmnt', 'plummer', 'nodular toxico'] },
            { t: 'Radioyodo o cirugía como definitivos', kw: ['radioyodo', 'i131', 'yodo', 'cirug', 'tiroidectom'] },
            { t: 'Betabloqueo', kw: ['betabloq', 'propranolol', 'atenolol', 'bisoprolol'] },
            { t: 'Anticoagulación según el riesgo (FA)', kw: ['anticoag', 'cha2ds2', 'chads'] },
          ],
          pearl: 'En la FA con tirotoxicosis, la anticoagulación se decide con las mismas escalas de riesgo que en cualquier FA.',
        },
      ],
    },

    // ---------- Laboratorio ----------
    {
      id: 'l01',
      type: 'lab',
      sub: 'dx',
      concepts: ['estrategia', 'definicion', 'tiroiditis'],
      diff: 2,
      cat: 'laboratorio',
      title: 'Tirotoxicosis: ¿síntesis o liberación?',
      context: 'Mujer de 38 años con palpitaciones de 3 semanas y tiroides indolora. Resultados:',
      labs: [
        { p: 'tsh', v: 0.02 },
        { p: 't4l', v: 2.6 },
        { p: 't3', v: 175 },
        { p: 'raiu', v: 3 },
        { p: 'tg', text: 'Elevada', flag: 'H' },
        { p: 'vsg', v: 14 },
      ],
      steps: [
        { kind: 'flags', cat: 'laboratorio' },
        {
          kind: 'mcq',
          cat: 'laboratorio',
          stem: '¿Qué indica la captación del 3 %?',
          options: [
            { t: 'Tirotoxicosis sin hiperproducción: destrucción o fuente exógena', why: 'Correcto.' },
            { t: 'Hipertiroidismo por Graves', why: 'Graves tendría una captación alta y difusa.', err: 'laboratorio' },
            { t: 'Bocio multinodular tóxico', why: 'Tendría una captación parcheada.', err: 'laboratorio' },
            { t: 'Hipotiroidismo', why: 'La T4L está alta.' },
          ],
          answer: 0,
          explain: ['La captación mide la síntesis activa.', 'Baja → tiroiditis, exógena o exceso de yodo.'],
          pearl: 'La captación responde a la pregunta «¿la glándula está fabricando?».',
        },
        {
          kind: 'mcq',
          cat: 'diagnostico',
          concepts: ['tiroiditis', 'facticia'],
          stem: 'Con una tiroglobulina elevada y una VSG normal, ¿cuál es el diagnóstico?',
          options: [
            { t: 'Tiroiditis silente (indolora)', why: 'Correcto: destrucción folicular (tiroglobulina alta) sin inflamación sistémica.' },
            { t: 'Tirotoxicosis facticia', why: 'Tendría la tiroglobulina baja.', err: 'diferencial' },
            { t: 'Tiroiditis subaguda', why: 'Tendría dolor y VSG alta.', err: 'diferencial' },
            { t: 'Graves', why: 'Captación baja.', err: 'diferencial' },
          ],
          answer: 0,
          explain: ['Captación baja + Tg alta → destrucción.', 'Sin dolor y con VSG normal → silente.'],
          pearl: 'Tiroiditis silente y posparto: la misma entidad en contextos distintos.',
        },
        {
          kind: 'mcq',
          cat: 'tratamiento',
          concepts: ['betabloqueo'],
          stem: '¿Qué dato modifica la conducta respecto a un Graves?',
          options: [
            { t: 'La captación baja: no se usan antitiroideos ni radioyodo; solo betabloqueo y vigilancia', why: 'Correcto.' },
            { t: 'La T3 normal: indica metimazol a dosis baja', why: 'No aplica.', err: 'tratamiento' },
            { t: 'La VSG normal: indica prednisona', why: 'La prednisona es para la subaguda con dolor.' },
            { t: 'La TSH suprimida: indica radioyodo', why: 'Sin captación, el radioyodo no funciona.' },
          ],
          answer: 0,
          explain: ['El tratamiento depende del mecanismo, no de la cifra de hormonas.'],
          pearl: 'Tratamiento según el **mecanismo**: síntesis → antitiroideos; liberación → sintomático.',
        },
      ],
    },
  ],
});
