/* Tema: Hipotiroidismo (incluye coma mixedematoso). Revisión 2026-09-26. */
SolMed.registry.addTopic({
  id: 'hipotiroidismo',
  name: 'Hipotiroidismo',
  short: 'Hipotiroidismo',
  specialty: 'medicina-interna',
  area: 'endocrinologia',
  group: 'Tiroides',
  reviewed: '2026-09-26',
  sources: ['ata2014', 'harrison22'],
  summary: 'Déficit de hormona tiroidea, casi siempre por fallo de la glándula (primario). La TSH es la prueba clave, salvo en el hipotiroidismo central.',
  subtopics: [
    { id: 'fisio', name: 'Etiología y fisiopatología' },
    { id: 'dx', name: 'Clínica y diagnóstico' },
    { id: 'lab', name: 'Laboratorio' },
    { id: 'tx', name: 'Tratamiento' },
    { id: 'coma', name: 'Coma mixedematoso' },
  ],
  concepts: [
    { id: 'etiologia', name: 'Causas: Hashimoto, iatrogenia, fármacos, déficit de yodo', sub: 'fisio' },
    { id: 'fisiopato', name: 'Fisiopatología y mixedema', sub: 'fisio' },
    { id: 'clinica', name: 'Manifestaciones clínicas', sub: 'dx' },
    { id: 'diagnostico', name: 'Estrategia diagnóstica (TSH → T4L)', sub: 'dx' },
    { id: 'subclinico', name: 'Hipotiroidismo subclínico', sub: 'dx' },
    { id: 'central', name: 'Hipotiroidismo central', sub: 'dx' },
    { id: 'eutiroideo', name: 'Síndrome del eutiroideo enfermo', sub: 'lab' },
    { id: 'lab_asociado', name: 'Alteraciones analíticas asociadas', sub: 'lab' },
    { id: 'levotiroxina', name: 'Levotiroxina: dosis, toma y control', sub: 'tx' },
    { id: 'poblaciones', name: 'Ancianos, cardiopatía y embarazo', sub: 'tx' },
    { id: 'suprarrenal', name: 'Insuficiencia suprarrenal antes de la levotiroxina', sub: 'tx' },
    { id: 'coma_dx', name: 'Coma mixedematoso: reconocimiento', sub: 'coma' },
    { id: 'coma_tx', name: 'Coma mixedematoso: tratamiento', sub: 'coma' },
  ],
  sheet: [
    {
      title: 'Definición',
      body: [
        'Producción insuficiente de hormona tiroidea. **Primario** (fallo de la glándula, >95 %) o **central** (hipófisis o hipotálamo).',
        '**Subclínico**: TSH alta con T4 libre normal. **Manifiesto**: TSH alta con T4 libre baja.',
      ],
    },
    {
      title: 'Epidemiología relevante',
      body: [['Más frecuente en mujeres y con la edad.', 'En regiones con suficiente yodo, la causa principal es la **tiroiditis de Hashimoto**; en el mundo, el déficit de yodo.']],
    },
    {
      title: 'Etiología y factores de riesgo',
      body: [
        [
          '**Autoinmune (Hashimoto)**: anti-TPO positivos; se asocia a otras enfermedades autoinmunes.',
          '**Iatrogénico**: tras radioyodo, tiroidectomía o radioterapia cervical.',
          '**Fármacos**: amiodarona, litio, inhibidores de puntos de control inmunitario, interferón-α, inhibidores de tirosina cinasa.',
          'Déficit o exceso de yodo.',
          'Fase hipotiroidea transitoria de las tiroiditis (subaguda, silente, posparto).',
          '**Central**: tumores hipofisarios, cirugía o radiación, síndrome de Sheehan, hipofisitis.',
        ],
      ],
    },
    {
      title: 'Fisiopatología',
      body: [
        [
          'Menor tasa metabólica y menor consumo de oxígeno → intolerancia al frío, cansancio, aumento de peso moderado.',
          'Acumulación de glucosaminoglucanos en la dermis y otros tejidos → **mixedema** (edema sin fóvea), macroglosia, voz ronca.',
          'Menor aclaramiento de LDL → hipercolesterolemia; aumento de CK por miopatía.',
          'Aumento de ADH y menor filtrado → **hiponatremia**.',
          'Menor respuesta ventilatoria a la hipoxia y la hipercapnia (clave en el coma mixedematoso).',
        ],
      ],
    },
    {
      title: 'Manifestaciones clínicas',
      body: [
        [
          'Astenia, intolerancia al frío, estreñimiento, piel seca, caída del cabello, aumento de peso, depresión, bradipsiquia.',
          '**Bradicardia**, hipertensión diastólica, derrame pericárdico.',
          '**Relajación lenta de los reflejos osteotendinosos**, síndrome del túnel carpiano.',
          'Alteraciones menstruales (menorragia), infertilidad, galactorrea (TRH alta → prolactina alta).',
          'Bocio (Hashimoto) o glándula atrófica.',
        ],
      ],
    },
    {
      title: 'Presentaciones atípicas',
      body: [
        [
          'Ancianos: síntomas sutiles, atribuidos a la edad; deterioro cognitivo.',
          'Hiponatremia, CK alta o dislipidemia como único hallazgo.',
          '**Coma mixedematoso**: emergencia, a menudo desencadenada por infección, frío o sedantes.',
        ],
      ],
    },
    {
      title: 'Diagnóstico',
      body: [
        [
          '**TSH** es la prueba inicial.',
          'Si la TSH es alta → **T4 libre**: baja = manifiesto; normal = subclínico.',
          'Anti-TPO: confirman la etiología autoinmune y predicen la progresión del subclínico.',
          '**Sospecha de causa central** (enfermedad hipofisaria, otros déficits): medir **T4 libre**, porque la TSH puede ser normal.',
          'Subclínico: repetir la TSH en 6–12 semanas antes de etiquetar (puede ser transitorio).',
        ],
      ],
    },
    {
      title: 'Diagnóstico diferencial',
      body: [
        [
          '**Síndrome del eutiroideo enfermo**: enfermedad grave → T3 baja, TSH normal o baja (y elevación transitoria en la recuperación). No se trata.',
          'Recuperación de una tiroiditis (TSH alta transitoria).',
          'Hipotiroidismo central frente a primario.',
          'Interferencia de la **biotina** en los inmunoensayos.',
          'Depresión, insuficiencia suprarrenal, anemia, síndrome nefrótico (edema).',
        ],
      ],
    },
    {
      title: 'Laboratorio y otras alteraciones',
      body: [
        [
          'Hipercolesterolemia (LDL alto), **CK elevada**, **hiponatremia**, anemia (normocítica o macrocítica), hiperprolactinemia leve.',
          'En el coma: hipoglucemia, hipercapnia, hipoxemia.',
          'ECG: bajo voltaje y bradicardia (derrame pericárdico).',
        ],
      ],
    },
    {
      title: 'Tratamiento',
      body: [
        [
          '**Levotiroxina** oral en ayunas, 30–60 min antes del desayuno (o al acostarse, lejos de la cena), siempre igual.',
          'Dosis de reemplazo completa ≈**1,6 µg/kg/día** en adultos jóvenes sin cardiopatía.',
          '**Ancianos o cardiopatía isquémica**: empezar con 12,5–25 µg/día y subir poco a poco.',
          'Control de la **TSH a las 6–8 semanas** de cada cambio (la vida media de la T4 es de ~7 días). Objetivo: TSH en el rango normal.',
          'Interacciones que reducen la absorción: hierro, calcio, IBP, colestiramina, soja; separar al menos 4 h.',
          'Subclínico: tratar si la TSH es ≥10 mUI/L, en el embarazo o si se busca embarazo; individualizar entre el límite superior y 10 (síntomas, anti-TPO, edad).',
        ],
      ],
    },
    {
      title: 'Situaciones especiales',
      body: [
        [
          '**Embarazo**: aumentar la dosis ≈25–30 % al confirmarlo (por ejemplo, 2 dosis extra a la semana) y controlar la TSH cada 4 semanas en la primera mitad.',
          '**Hipotiroidismo central**: ajustar por T4 libre (mitad superior del rango); **tratar primero la insuficiencia suprarrenal** si existe.',
          '**Insuficiencia suprarrenal coexistente** (autoinmune, hipofisaria): la levotiroxina aumenta el metabolismo del cortisol y puede precipitar una crisis suprarrenal → glucocorticoide antes.',
        ],
      ],
    },
    {
      title: 'Coma mixedematoso',
      body: [
        '**Reconocimiento**: hipotiroidismo grave + alteración de conciencia + **hipotermia**, a menudo con bradicardia, hipotensión, **hipoventilación con hipercapnia**, **hiponatremia** e hipoglucemia. Precipitantes: infección, frío, sedantes u opioides, ictus, cirugía. Es un diagnóstico **clínico**: no esperes a la analítica.',
        '**Tratamiento (ATA 2014)**:',
        [
          'UCI; soporte ventilatorio si hay hipercapnia.',
          '**Hidrocortisona a dosis de estrés** (por ejemplo, 100 mg IV cada 8 h) hasta descartar insuficiencia suprarrenal.',
          '**Levotiroxina IV**: carga de 200–400 µg, después 1,6 µg/kg/día × 0,75 por vía IV hasta poder dar la vía oral. Dosis más bajas si hay edad avanzada o riesgo coronario. Algunos añaden liotironina (T3).',
          '**Calentamiento pasivo** (mantas); el calentamiento activo externo puede causar vasodilatación y colapso.',
          'Corregir la hiponatremia (con prudencia) y la hipoglucemia; evitar los sedantes; tratar el precipitante (cultivos y antibióticos si se sospecha infección).',
        ],
      ],
    },
    {
      title: 'Monitorización y metas',
      body: [['TSH en rango (primario); T4 libre en la mitad superior (central).', 'Vigilar la aparición de angina o arritmia al subir la dosis en cardiópatas.', 'Evitar el sobretratamiento (fibrilación auricular, osteoporosis).']],
    },
    {
      title: 'Errores frecuentes',
      body: [
        [
          'Ajustar la dosis por TSH en el hipotiroidismo central.',
          'Iniciar dosis plenas en ancianos o coronarios.',
          'Controlar la TSH antes de 6 semanas.',
          'Tratar un síndrome del eutiroideo enfermo.',
          'Dar levotiroxina sin cubrir una posible insuficiencia suprarrenal (en el coma mixedematoso o en la enfermedad hipofisaria).',
          'Recalentar activamente el coma mixedematoso.',
        ],
      ],
    },
    {
      title: 'Pronóstico',
      body: ['Excelente con tratamiento. El coma mixedematoso tiene una mortalidad alta, sobre todo en ancianos con hipotermia, bradicardia o sepsis.'],
    },
    {
      title: 'Perlas de alto rendimiento',
      body: [
        [
          'TSH alta + T4L normal = subclínico → repite antes de tratar.',
          'TSH baja o normal + T4L baja = piensa en la hipófisis.',
          'Hiponatremia + CK alta + dislipidemia → pide TSH.',
          'Coma mixedematoso: **hidrocortisona + levotiroxina IV + calentamiento pasivo + ventilación**.',
        ],
      ],
    },
  ],
  items: [
    {
      id: 'q01',
      type: 'mcq',
      sub: 'dx',
      concepts: ['diagnostico', 'subclinico'],
      diff: 1,
      cat: 'diagnostico',
      stem: 'Mujer de 42 años asintomática: TSH 7,2 mUI/L y T4 libre 1,1 ng/dL (normal). ¿Qué haces?',
      options: [
        { t: 'Repetir TSH y T4 libre en 6–12 semanas (y anti-TPO) antes de decidir', why: 'Correcto: probable hipotiroidismo subclínico; hay que confirmar la persistencia porque puede ser transitorio.' },
        { t: 'Levotiroxina a dosis plena (1,6 µg/kg)', why: 'No está indicada con un valor aislado, TSH <10 y sin síntomas ni embarazo.', err: 'tratamiento' },
        { t: 'Gammagrafía tiroidea', why: 'No aporta en el hipotiroidismo.' },
        { t: 'RM hipofisaria', why: 'La TSH alta indica un origen primario.', err: 'diferencial' },
      ],
      answer: 0,
      explain: ['TSH alta con T4L normal = subclínico.', 'Confirmar en 6–12 semanas.', 'Tratar si TSH ≥10, embarazo o deseo de embarazo; individualizar en los demás.'],
      pearl: 'Los anti-TPO positivos predicen mayor progresión a hipotiroidismo manifiesto.',
      remember: 'Subclínico: confirma antes de tratar.',
    },
    {
      id: 'q02',
      type: 'mcq',
      sub: 'dx',
      concepts: ['central'],
      diff: 2,
      cat: 'diferencial',
      stem: 'Varón de 55 años con un macroadenoma hipofisario operado: astenia e intolerancia al frío. TSH 1,2 mUI/L, T4 libre 0,5 ng/dL. ¿Qué indica y qué debes evaluar antes de tratar?',
      options: [
        { t: 'Hipotiroidismo central; evaluar el eje corticotropo (cortisol) antes de iniciar la levotiroxina', why: 'Correcto: la T4L baja con TSH no elevada indica una causa central; puede coexistir un déficit de ACTH.' },
        { t: 'Eutiroidismo, porque la TSH es normal', why: 'En el central la TSH no es fiable: la T4L baja confirma el hipotiroidismo.', err: 'laboratorio' },
        { t: 'Hipotiroidismo primario leve', why: 'En el primario la TSH estaría alta.', err: 'diferencial' },
        { t: 'Síndrome del eutiroideo enfermo', why: 'No hay enfermedad aguda grave y hay causa hipofisaria.', err: 'diferencial' },
      ],
      answer: 0,
      explain: ['T4L baja + TSH inapropiadamente normal → central.', 'Buscar otros déficits hipofisarios.', 'Si hay déficit de cortisol, glucocorticoide primero.', 'Ajustar la dosis por T4L.'],
      pearl: 'La levotiroxina puede **precipitar una crisis suprarrenal** si no se trata antes el déficit de cortisol.',
      remember: 'Central: T4L para diagnosticar y ajustar; cortisol antes.',
      compare: ['hipo-primario-central'],
    },
    {
      id: 'q03',
      type: 'mcq',
      sub: 'tx',
      concepts: ['poblaciones', 'levotiroxina'],
      diff: 2,
      cat: 'tratamiento',
      stem: 'Varón de 78 años con cardiopatía isquémica y angina estable. TSH 38 mUI/L, T4L 0,4 ng/dL. ¿Cómo inicias la levotiroxina?',
      options: [
        { t: 'Dosis baja (12,5–25 µg/día) con aumentos lentos y control de la angina', why: 'Correcto: la dosis plena puede precipitar isquemia o arritmia.' },
        { t: '1,6 µg/kg/día desde el primer día', why: 'Adecuado para jóvenes sanos, no para ancianos coronarios.', err: 'tratamiento' },
        { t: 'Liotironina (T3) en dosis altas', why: 'Aumenta el riesgo cardíaco.', err: 'tratamiento' },
        { t: 'No tratar por el riesgo cardíaco', why: 'El hipotiroidismo manifiesto debe tratarse.' },
      ],
      answer: 0,
      explain: ['La hormona tiroidea aumenta la frecuencia cardíaca y el consumo de O₂ miocárdico.', 'Empieza bajo y sube despacio (cada 4–6 semanas).'],
      pearl: '«Start low, go slow»: en ancianos y cardiópatas.',
      remember: 'Ancianos o coronarios: 12,5–25 µg/día.',
    },
    {
      id: 'q04',
      type: 'mcq',
      sub: 'tx',
      concepts: ['levotiroxina'],
      diff: 1,
      cat: 'tratamiento',
      stem: 'Tras iniciar o cambiar la dosis de levotiroxina, ¿cuándo se debe medir la TSH?',
      options: [
        { t: 'A las 6–8 semanas', why: 'Correcto: se necesitan ~5 vidas medias de T4 (~7 días cada una) para el equilibrio.' },
        { t: 'A la semana', why: 'Aún no se alcanzó el estado de equilibrio.', err: 'conocimiento' },
        { t: 'A los 6 meses', why: 'Demora innecesaria del ajuste.' },
        { t: 'Solo si hay síntomas', why: 'El ajuste se basa en la TSH.' },
      ],
      answer: 0,
      explain: ['Vida media de la T4 ≈7 días.', 'Equilibrio en ~5–6 semanas.', 'Ajustar en pasos de 12,5–25 µg.'],
      pearl: 'Mismo horario, en ayunas y lejos del hierro y el calcio: la mala absorción es la causa más frecuente de TSH «resistente».',
      remember: 'TSH a las 6–8 semanas.',
    },
    {
      id: 'q05',
      type: 'mcq',
      sub: 'tx',
      concepts: ['poblaciones'],
      diff: 2,
      cat: 'tratamiento',
      stem: 'Mujer con hipotiroidismo bien controlado con levotiroxina que acaba de confirmar un embarazo de 5 semanas. ¿Qué haces?',
      options: [
        { t: 'Aumentar la dosis ≈25–30 % (por ejemplo, 2 dosis extra a la semana) y controlar la TSH cada 4 semanas', why: 'Correcto: las necesidades aumentan pronto en el embarazo.' },
        { t: 'Mantener la dosis y controlar en el tercer trimestre', why: 'El feto depende de la T4 materna en el primer trimestre.', err: 'tratamiento' },
        { t: 'Suspender la levotiroxina por seguridad fetal', why: 'Es segura y necesaria.', err: 'tratamiento' },
        { t: 'Cambiar a liotironina', why: 'La T3 no cruza bien la placenta y no es el tratamiento adecuado.' },
      ],
      answer: 0,
      explain: ['Aumento de TBG y del volumen de distribución; paso transplacentario.', 'Ajuste inmediato al confirmar el embarazo.', 'Objetivos de TSH específicos del trimestre.'],
      pearl: 'El desarrollo neurológico fetal del primer trimestre depende de la **T4 materna**.',
      remember: 'Embarazo: +25–30 % al confirmarlo.',
    },
    {
      id: 'q06',
      type: 'mcq',
      sub: 'lab',
      concepts: ['eutiroideo'],
      diff: 3,
      cat: 'laboratorio',
      stem: 'Paciente en UCI por shock séptico: TSH 0,3 mUI/L, T4L 0,9 ng/dL, T3 total 45 ng/dL. Sin antecedentes tiroideos. ¿Qué haces?',
      options: [
        { t: 'No tratar: síndrome del eutiroideo enfermo; repetir tras la recuperación', why: 'Correcto: patrón típico de la enfermedad grave (T3 baja, TSH normal-baja).' },
        { t: 'Levotiroxina IV por hipotiroidismo central', why: 'El patrón es el de la enfermedad no tiroidea; la T4L es normal.', err: 'diferencial' },
        { t: 'Liotironina IV', why: 'No mejora el pronóstico en el eutiroideo enfermo.', err: 'tratamiento' },
        { t: 'Metimazol por la TSH baja', why: 'No hay tirotoxicosis (T4L y T3 no están altas).', err: 'laboratorio' },
      ],
      answer: 0,
      explain: ['Enfermedad grave: menor desyodación periférica de T4 a T3 → T3 baja.', 'La dopamina y los glucocorticoides bajan la TSH.', 'Reevaluar a las semanas; en la recuperación la TSH puede subir transitoriamente.'],
      pearl: 'No pidas pruebas tiroideas en la UCI salvo sospecha clínica real.',
      remember: 'Enfermedad grave + T3 baja = no tratar.',
    },
    {
      id: 'q07',
      type: 'mcq',
      sub: 'coma',
      concepts: ['coma_tx', 'suprarrenal'],
      diff: 2,
      cat: 'secuencia',
      stem: 'En el coma mixedematoso, ¿qué fármaco debe administrarse junto con (o antes de) la levotiroxina IV?',
      options: [
        { t: 'Hidrocortisona IV a dosis de estrés', why: 'Correcto: puede coexistir insuficiencia suprarrenal y la levotiroxina acelera el metabolismo del cortisol.' },
        { t: 'Propranolol', why: 'Contraindicado: empeoraría la bradicardia y la hipotensión.', err: 'tratamiento' },
        { t: 'Metimazol', why: 'Es un antitiroideo: absurdo en el hipotiroidismo.', err: 'tratamiento' },
        { t: 'Furosemida', why: 'No tiene papel y agravaría la hipotensión.' },
      ],
      answer: 0,
      explain: ['Riesgo de insuficiencia suprarrenal (autoinmune o hipofisaria).', 'Hidrocortisona hasta descartarla.', 'Después, levotiroxina IV (carga de 200–400 µg).'],
      pearl: 'Toma una muestra de cortisol **antes** de la hidrocortisona, pero no esperes el resultado.',
      remember: 'Coma mixedematoso: hidrocortisona + levotiroxina IV.',
      compare: ['coma-tormenta'],
    },
    {
      id: 'q08',
      type: 'mcq',
      sub: 'coma',
      concepts: ['coma_dx'],
      diff: 2,
      cat: 'diagnostico',
      stem: 'Mujer de 80 años encontrada en su casa en invierno: estupor, T 33,8 °C, FC 44, PA 84/50, Na⁺ 124, glucosa 58, PaCO₂ 62 mmHg. Cicatriz de tiroidectomía; no toma medicación desde hace meses. ¿Qué hallazgo es **menos** esperable en un coma mixedematoso?',
      options: [
        { t: 'Taquicardia con hiperpirexia', why: 'Correcto: son rasgos de la tormenta tiroidea, no del coma mixedematoso.' },
        { t: 'Hiponatremia', why: 'Es típica (aumento de ADH, menor filtrado).' },
        { t: 'Hipercapnia', why: 'Es típica (hipoventilación).' },
        { t: 'Hipotermia', why: 'Es un rasgo cardinal.' },
      ],
      answer: 0,
      explain: ['Coma mixedematoso: hipotermia, bradicardia, hipotensión, hipoventilación, hiponatremia, hipoglucemia.', 'La tormenta tiroidea es la imagen especular.'],
      pearl: 'Busca la **cicatriz** cervical y los antecedentes de radioyodo en el paciente en coma con hipotermia.',
      remember: 'Mixedema: todo «hipo».',
      compare: ['coma-tormenta'],
    },
    {
      id: 'q09',
      type: 'mcq',
      sub: 'fisio',
      concepts: ['etiologia'],
      diff: 1,
      cat: 'concepto',
      stem: '¿Cuál es la causa más frecuente de hipotiroidismo en regiones con aporte suficiente de yodo?',
      options: [
        { t: 'Tiroiditis autoinmune (Hashimoto)', why: 'Correcto.' },
        { t: 'Déficit de yodo', why: 'Es la primera causa mundial, pero no en regiones con yodo suficiente.' },
        { t: 'Hipotiroidismo central', why: 'Es raro.' },
        { t: 'Carcinoma tiroideo', why: 'No suele causar hipotiroidismo.' },
      ],
      answer: 0,
      explain: ['Hashimoto: anti-TPO positivos, infiltrado linfocítico.', 'Asociación con otras enfermedades autoinmunes.'],
      pearl: 'Hashimoto con bocio que crece rápido → descartar un linfoma tiroideo (raro).',
      remember: 'Hashimoto: la causa número 1 con yodo suficiente.',
    },
    {
      id: 'q10',
      type: 'mcq',
      sub: 'lab',
      concepts: ['lab_asociado', 'clinica'],
      diff: 2,
      cat: 'laboratorio',
      stem: 'Mujer de 50 años con mialgias, estreñimiento y hipercolesterolemia reciente. CK 1200 U/L y Na⁺ 131. ¿Qué prueba solicitas antes de iniciar una estatina?',
      options: [
        { t: 'TSH', why: 'Correcto: el hipotiroidismo explica la dislipidemia, la CK alta y la hiponatremia, y la estatina aumentaría el riesgo de miopatía.' },
        { t: 'Biopsia muscular', why: 'Es prematura sin descartar causas comunes.' },
        { t: 'Anticuerpos antinucleares', why: 'Son menos probables que el hipotiroidismo.' },
        { t: 'Ninguna: iniciar la estatina', why: 'Riesgo de miopatía con un hipotiroidismo no tratado.', err: 'razonamiento' },
      ],
      answer: 0,
      explain: ['El hipotiroidismo causa hipercolesterolemia secundaria.', 'La miopatía hipotiroidea eleva la CK.', 'La hiponatremia también encaja.'],
      pearl: 'Pide TSH **antes** de iniciar una estatina si hay dislipidemia con miopatía o CK alta.',
      remember: 'Dislipidemia + CK alta + Na bajo → TSH.',
    },

    // ---------- Caso ----------
    {
      id: 'c01',
      type: 'case',
      sub: 'dx',
      concepts: ['clinica', 'diagnostico', 'levotiroxina'],
      diff: 2,
      cat: 'integracion',
      title: 'Cansancio y frío',
      patient: { age: 46, sex: 'F' },
      vignette: [
        'Mujer de 46 años con 8 meses de cansancio, somnolencia, intolerancia al frío, estreñimiento, aumento de 5 kg y reglas abundantes. Tiene vitíligo. Su madre tiene «algo de tiroides». Toma sulfato ferroso por anemia.',
      ],
      vitals: { PA: '138/92 mmHg', FC: '56 lpm', T: '36,1 °C', peso: '68 kg' },
      exam: 'Piel seca y fría, edema palpebral sin fóvea, bocio difuso firme e indoloro, fase de relajación de los reflejos aquíleos lenta.',
      labs: [
        { p: 'tsh', v: 42 },
        { p: 't4l', v: 0.4 },
        { p: 'antitpo', text: 'Positivos (480 UI/mL)', flag: 'H' },
        { p: 'na', v: 133 },
        { name: 'Colesterol LDL', v: 196, unit: 'mg/dL', ref: '<130', flag: 'H' },
        { name: 'CK', v: 410, unit: 'U/L', ref: '<170', flag: 'H' },
      ],
      questions: [
        {
          stem: '¿Cuál es el diagnóstico?',
          options: [
            { t: 'Hipotiroidismo primario manifiesto por tiroiditis de Hashimoto', why: 'Correcto: TSH alta, T4L baja, anti-TPO positivos, bocio y autoinmunidad asociada (vitíligo).' },
            { t: 'Hipotiroidismo subclínico', why: 'La T4L está baja: es manifiesto.', err: 'laboratorio' },
            { t: 'Hipotiroidismo central', why: 'La TSH alta indica origen primario.', err: 'diferencial' },
            { t: 'Tiroiditis subaguda', why: 'Sin dolor ni fase tirotóxica.', err: 'diferencial' },
          ],
          answer: 0,
          explain: ['TSH 42 + T4L 0,4 → primario manifiesto.', 'Anti-TPO positivos → autoinmune.', 'Vitíligo: otra autoinmunidad.'],
          key: ['TSH 42', 'T4L 0,4', 'Anti-TPO positivos'],
          altered: ['Hiponatremia leve', 'LDL alto', 'CK alta'],
          pearl: 'El **vitíligo** y otras autoinmunidades aumentan la sospecha de Hashimoto.',
        },
        {
          stem: 'Pesa 68 kg y no tiene cardiopatía. ¿Qué pauta es la más adecuada?',
          cat: 'tratamiento',
          concepts: ['levotiroxina'],
          options: [
            { t: 'Levotiroxina ≈100–112 µg/día en ayunas, separada 4 h del hierro, con TSH en 6–8 semanas', why: 'Correcto: ≈1,6 µg/kg/día; el hierro reduce la absorción.' },
            { t: 'Levotiroxina 25 µg/día y subir cada 6 meses', why: 'Innecesariamente lento en una joven sana.', err: 'tratamiento' },
            { t: 'Tomarla con el hierro en el desayuno para facilitar la adherencia', why: 'El hierro reduce la absorción.', err: 'tratamiento' },
            { t: 'Esperar a normalizar el colesterol con estatina', why: 'El hipotiroidismo es la causa; se trata primero.' },
          ],
          answer: 0,
          explain: ['1,6 × 68 ≈ 109 µg/día.', 'En ayunas; separar 4 h del hierro y el calcio.', 'TSH a las 6–8 semanas.'],
          pearl: 'Reevalúa los lípidos **después** de normalizar la TSH antes de decidir una estatina.',
        },
      ],
    },

    // ---------- Progresivo: coma mixedematoso ----------
    {
      id: 'p01',
      type: 'progressive',
      sub: 'coma',
      concepts: ['coma_dx', 'coma_tx', 'suprarrenal'],
      diff: 3,
      cat: 'secuencia',
      title: 'Hipotermia en invierno',
      stages: [
        {
          id: 's1',
          title: 'Urgencias',
          text: ['Mujer de 82 años, estuporosa. Tiroidectomía hace 20 años; dejó la levotiroxina «porque se sentía bien». Tiene tos y fiebre desde hace 3 días, según la vecina. Hoy tomó un comprimido de lorazepam para dormir.'],
          vitals: { T: '33,6 °C', FC: '46 lpm', PA: '82/48 mmHg', FR: '8 rpm', SatO2: '88 %' },
          labs: [
            { p: 'na', v: 122 },
            { p: 'glucosa', v: 61 },
            { p: 'paco2', v: 68 },
            { p: 'ph', v: 7.26 },
          ],
          q: {
            stem: '¿Qué haces en primer lugar?',
            options: [
              { t: 'Asegurar la vía aérea y la ventilación, glucosa IV y extraer TSH, T4L y cortisol sin esperar los resultados', why: 'Correcto: la hipoventilación y la hipoglucemia son las amenazas inmediatas.' },
              { t: 'Esperar la TSH para confirmar el diagnóstico', why: 'El diagnóstico es clínico; la demora aumenta la mortalidad.', err: 'razonamiento', next: 's1b' },
              { t: 'Flumazenilo y observación', why: 'No explica la hipotermia, la bradicardia ni la hiponatremia; retrasa el tratamiento.', err: 'diferencial' },
              { t: 'Calentamiento activo con aire caliente a 40 °C', why: 'El calentamiento activo externo puede causar vasodilatación y colapso.', err: 'tratamiento' },
            ],
            answer: 0,
            explain: ['Hipercapnia con FR 8 → soporte ventilatorio.', 'Hipoglucemia → glucosa.', 'Extraer muestras y tratar empíricamente.'],
            pearl: 'Coma mixedematoso: **trata sin esperar la TSH**.',
          },
          goto: 's2',
        },
        {
          id: 's1b',
          title: '3 horas después',
          tone: 'alert',
          text: ['Mientras se espera la analítica, la PaCO₂ sube a 84 mmHg y la FC baja a 38 lpm.'],
          q: {
            stem: '¿Qué lección te deja?',
            options: [
              { t: 'La sospecha clínica basta para iniciar el tratamiento', why: 'Correcto.' },
              { t: 'Hay que pedir más pruebas antes de actuar', why: 'No.' },
              { t: 'La bradicardia debe tratarse con betabloqueante', why: 'Absurdo: empeoraría.' },
              { t: 'Nada: evolución esperable', why: 'Es un deterioro evitable.' },
            ],
            answer: 0,
            explain: ['La mortalidad aumenta con el retraso terapéutico.'],
            pearl: 'Diagnóstico clínico, tratamiento inmediato.',
          },
          goto: 's2',
        },
        {
          id: 's2',
          title: 'Tratamiento específico',
          text: ['Intubada. Glucosa 110 tras dextrosa. Se extrajeron muestras.'],
          q: {
            stem: '¿Qué tratamiento específico inicias?',
            options: [
              { t: 'Hidrocortisona IV a dosis de estrés + levotiroxina IV (carga de 200–400 µg, más cerca de 200 por su edad), calentamiento pasivo, cultivos y antibióticos', why: 'Correcto.' },
              { t: 'Levotiroxina oral 50 µg/día', why: 'La absorción intestinal es impredecible (íleo, edema): se prefiere la vía IV.', err: 'tratamiento' },
              { t: 'Levotiroxina IV sin glucocorticoides', why: 'Riesgo de precipitar una crisis suprarrenal.', err: 'secuencia', next: 's3b' },
              { t: 'Salino hipertónico para normalizar el sodio en 6 h', why: 'Corrección demasiado rápida; la hiponatremia mejora con el tratamiento.', err: 'complicaciones' },
            ],
            answer: 0,
            explain: ['Glucocorticoide + hormona IV.', 'Dosis menor en ancianos o coronarios.', 'Tratar el precipitante (neumonía).'],
            pearl: 'Los sedantes (el lorazepam) son precipitantes clásicos: evítalos.',
          },
          goto: 's3',
        },
        {
          id: 's3b',
          title: 'Complicación',
          tone: 'alert',
          text: ['Tras la levotiroxina sin glucocorticoide, la PA cae a 70/40 a pesar del volumen. El cortisol basal extraído llega en 118 nmol/L (bajo).'],
          q: {
            stem: '¿Qué haces?',
            options: [
              { t: 'Hidrocortisona IV inmediata (insuficiencia suprarrenal coexistente)', why: 'Correcto.' },
              { t: 'Suspender la levotiroxina', why: 'La hormona sigue siendo necesaria; lo que falta es el cortisol.' },
              { t: 'Vasopresor sin más', why: 'No corrige la causa.' },
              { t: 'Metimazol', why: 'No tiene sentido.' },
            ],
            answer: 0,
            explain: ['La hormona tiroidea aumenta el aclaramiento del cortisol.', 'Puede coexistir una insuficiencia suprarrenal (síndrome poliglandular o hipopituitarismo).'],
            pearl: 'Glucocorticoide **antes o junto** con la levotiroxina.',
          },
          goto: 's3',
        },
        {
          id: 's3',
          title: 'Evolución',
          end: true,
          text: ['A las 72 h: T 36,4 °C, FC 64, extubada, Na⁺ 131. Pasa a levotiroxina oral cuando tolera. Se retira la hidrocortisona tras confirmar un cortisol normal. Educación sobre la necesidad del tratamiento de por vida.'],
        },
      ],
    },

    // ---------- Razonamiento ----------
    {
      id: 'r01',
      type: 'reasoning',
      sub: 'dx',
      concepts: ['diagnostico', 'central', 'eutiroideo'],
      diff: 3,
      cat: 'razonamiento',
      title: 'Una TSH que engaña',
      vignette: ['Varón de 60 años con cefalea y alteración visual (hemianopsia bitemporal). Refiere astenia y frío. TSH 0,9 mUI/L (normal). El médico anterior descartó el hipotiroidismo «porque la TSH es normal».'],
      prompts: [
        {
          q: '¿Estás de acuerdo con descartar el hipotiroidismo? ¿Por qué?',
          expected: 'No. La hemianopsia bitemporal sugiere una masa hipofisaria o selar (por ejemplo, un macroadenoma) que puede causar hipotiroidismo central, en el que la TSH puede ser normal, baja o levemente alta (inactiva). Hay que medir la T4 libre.',
          points: [
            { t: 'Sospecha de masa hipofisaria o quiasmática', kw: ['hipofis', 'adenoma', 'quiasma', 'selar', 'silla'] },
            { t: 'En el central la TSH puede ser normal', kw: ['central', 'tsh normal', 'tsh no sirve', 'inapropiad'] },
            { t: 'Medir la T4 libre', kw: ['t4', 'tiroxina', 't4l', 'libre'] },
          ],
        },
        {
          q: '¿Qué otros ejes evaluarías y por qué importa el orden del tratamiento?',
          expected: 'Eje corticotropo (cortisol, ACTH), gonadal (LH, FSH, testosterona), prolactina, GH/IGF-1; balance hídrico (diabetes insípida). Si hay insuficiencia suprarrenal, hay que tratarla con glucocorticoide antes de la levotiroxina para no precipitar una crisis suprarrenal.',
          points: [
            { t: 'Cortisol / eje corticotropo', kw: ['cortisol', 'acth', 'suprarrenal', 'corticotrop'] },
            { t: 'Otros ejes (gonadal, prolactina, GH)', kw: ['prolactina', 'lh', 'fsh', 'testosterona', 'gonad', 'igf', 'gh'] },
            { t: 'Glucocorticoide antes de la levotiroxina', kw: ['antes', 'primero', 'crisis suprarrenal', 'hidrocortisona'] },
          ],
        },
        {
          q: 'Si se confirma, ¿cómo ajustarías la levotiroxina?',
          expected: 'Por T4 libre (objetivo: mitad superior del rango de referencia), no por TSH, que no refleja el estado tiroideo en el hipotiroidismo central.',
          points: [
            { t: 'Ajustar por T4 libre', kw: ['t4', 'libre', 't4l'] },
            { t: 'No usar la TSH para ajustar', kw: ['no tsh', 'tsh no', 'sin tsh', 'no por tsh', 'no se usa la tsh'] },
          ],
          pearl: 'En el hipotiroidismo central, una TSH «suprimida» durante el tratamiento es **esperable**, no un signo de sobredosis.',
        },
      ],
    },

    // ---------- Laboratorio ----------
    {
      id: 'l01',
      type: 'lab',
      sub: 'lab',
      concepts: ['diagnostico', 'lab_asociado'],
      diff: 1,
      cat: 'laboratorio',
      title: 'Perfil tiroideo y bioquímica',
      context: 'Mujer de 58 años con astenia. Resultados:',
      labs: [
        { p: 'tsh', v: 18.5 },
        { p: 't4l', v: 0.6 },
        { p: 'na', v: 134 },
        { p: 'glucosa', v: 92 },
        { p: 'creat', v: 0.9 },
      ],
      steps: [
        { kind: 'flags', cat: 'laboratorio' },
        {
          kind: 'mcq',
          cat: 'diagnostico',
          stem: '¿Qué patrón es?',
          options: [
            { t: 'Hipotiroidismo primario manifiesto', why: 'Correcto: TSH alta y T4L baja.' },
            { t: 'Hipotiroidismo subclínico', why: 'La T4L está baja.', err: 'laboratorio' },
            { t: 'Hipotiroidismo central', why: 'La TSH está alta.', err: 'laboratorio' },
            { t: 'Tirotoxicosis', why: 'T4L baja.', err: 'laboratorio' },
          ],
          answer: 0,
          explain: ['Lee la TSH primero: alta → problema en la glándula.', 'Después la T4L: baja → manifiesto.'],
          pearl: 'Primero la TSH, después la T4L: así clasificas en 10 segundos.',
        },
        {
          kind: 'mcq',
          cat: 'laboratorio',
          concepts: ['lab_asociado'],
          stem: '¿Qué dato asociado encaja con el hipotiroidismo?',
          options: [
            { t: 'La hiponatremia leve (Na⁺ 134)', why: 'Correcto: por aumento de ADH y menor filtrado.' },
            { t: 'La glucosa normal', why: 'No es una alteración.' },
            { t: 'La creatinina normal', why: 'No es una alteración.' },
            { t: 'Ninguno', why: 'La hiponatremia sí encaja.' },
          ],
          answer: 0,
          explain: ['Hipotiroidismo: menor aclaramiento de agua libre.'],
          pearl: 'En toda hiponatremia euvolémica, descarta hipotiroidismo e insuficiencia suprarrenal antes de etiquetar un SIADH.',
        },
        {
          kind: 'mcq',
          cat: 'tratamiento',
          concepts: ['levotiroxina'],
          stem: '¿Qué harías ahora?',
          options: [
            { t: 'Iniciar levotiroxina y controlar la TSH a las 6–8 semanas; pedir anti-TPO', why: 'Correcto.' },
            { t: 'Repetir en 3 meses sin tratar', why: 'El manifiesto se trata.', err: 'tratamiento' },
            { t: 'RM hipofisaria', why: 'Origen primario.', err: 'diferencial' },
            { t: 'Gammagrafía', why: 'No aporta.' },
          ],
          answer: 0,
          explain: ['El hipotiroidismo manifiesto requiere tratamiento.', 'Los anti-TPO orientan la etiología.'],
          pearl: 'Ajusta la dosis inicial a la edad y el riesgo cardíaco.',
        },
      ],
    },
  ],
});
