/* Tema: Hemorragia subaracnoidea (HSA). Revisión 2026-09-26.
 * Base: guía AHA/ASA 2023 de HSA aneurismática; Perry et al. para la TC
 * precoz y la regla de Ottawa. */
SolMed.registry.addTopic({
  id: 'hsa',
  name: 'Hemorragia subaracnoidea',
  short: 'HSA',
  specialty: 'medicina-interna',
  area: 'neurologia',
  group: 'Enfermedad cerebrovascular',
  reviewed: '2026-09-26',
  sources: ['aha2023', 'perry', 'harrison22'],
  summary: 'Sangrado en el espacio subaracnoideo, en su mayoría por rotura de un aneurisma sacular. Cefalea en trueno, diagnóstico urgente y complicaciones con ventanas temporales características.',
  subtopics: [
    { id: 'fisio', name: 'Etiología y fisiopatología' },
    { id: 'dx', name: 'Clínica y diagnóstico' },
    { id: 'tx', name: 'Tratamiento' },
    { id: 'comp', name: 'Complicaciones' },
  ],
  concepts: [
    { id: 'etiologia', name: 'Causas y factores de riesgo', sub: 'fisio' },
    { id: 'fisiopato', name: 'Fisiopatología', sub: 'fisio' },
    { id: 'clinica', name: 'Cefalea en trueno y clínica', sub: 'dx' },
    { id: 'ottawa', name: 'Regla de Ottawa', sub: 'dx' },
    { id: 'tc', name: 'TC sin contraste y tiempo desde el inicio', sub: 'dx' },
    { id: 'pl', name: 'Punción lumbar: xantocromía y hematíes', sub: 'dx' },
    { id: 'angio', name: 'Angio-TC y arteriografía', sub: 'dx' },
    { id: 'escalas', name: 'Escalas: Hunt y Hess, WFNS, Fisher modificada', sub: 'dx' },
    { id: 'diferencial', name: 'Diagnóstico diferencial de la cefalea en trueno', sub: 'dx' },
    { id: 'manejo_inicial', name: 'Manejo inicial: PA, anticoagulación, soporte', sub: 'tx' },
    { id: 'aneurisma_tx', name: 'Tratamiento del aneurisma (endovascular o quirúrgico)', sub: 'tx' },
    { id: 'nimodipino', name: 'Nimodipino', sub: 'tx' },
    { id: 'resangrado', name: 'Resangrado', sub: 'comp' },
    { id: 'hidrocefalia', name: 'Hidrocefalia', sub: 'comp' },
    { id: 'dci', name: 'Vasoespasmo e isquemia cerebral tardía', sub: 'comp' },
    { id: 'hiponatremia', name: 'Hiponatremia: pierde sal cerebral frente a SIADH', sub: 'comp' },
    { id: 'convulsiones', name: 'Convulsiones y profilaxis', sub: 'comp' },
    { id: 'cardiopulmonar', name: 'Complicaciones cardíacas y pulmonares', sub: 'comp' },
  ],
  sheet: [
    {
      title: 'Definición',
      body: ['Sangre en el espacio subaracnoideo. La **no traumática** se debe sobre todo a la **rotura de un aneurisma sacular** (≈85 %); el traumatismo es, en conjunto, la causa más frecuente de sangre subaracnoidea.'],
    },
    {
      title: 'Epidemiología relevante',
      body: [
        [
          'Pico de incidencia entre los 40 y los 60 años; algo más frecuente en mujeres.',
          'Mortalidad elevada: una parte de los pacientes fallece antes de llegar al hospital; muchos supervivientes quedan con secuelas cognitivas.',
          'Es una causa relevante de ictus en personas jóvenes.',
        ],
      ],
    },
    {
      title: 'Etiología y factores de riesgo',
      body: [
        [
          '**Aneurisma sacular** en el polígono de Willis (comunicante anterior, comunicante posterior, bifurcación de la cerebral media).',
          '**HSA perimesencefálica no aneurismática** (≈10 %): sangrado venoso con buen pronóstico.',
          'Otras: malformación arteriovenosa, disección, vasculitis, vasoconstricción cerebral reversible (HSA de convexidad), angiopatía amiloide, coagulopatía, cocaína.',
          '**Factores de riesgo**: hipertensión, **tabaco**, consumo intenso de alcohol, simpaticomiméticos (cocaína), antecedentes familiares (≥2 familiares de primer grado), **poliquistosis renal autosómica dominante**, enfermedades del tejido conectivo (Ehlers-Danlos tipo IV).',
        ],
      ],
    },
    {
      title: 'Fisiopatología',
      body: [
        [
          'La rotura aumenta de golpe la presión intracraneal → cefalea súbita, y a veces pérdida de conciencia por caída transitoria de la perfusión cerebral.',
          'La sangre irrita las meninges (rigidez de nuca, que puede tardar horas) y obstruye la reabsorción del LCR (hidrocefalia).',
          'Los productos de degradación de la hemoglobina favorecen el vasoespasmo y la isquemia cerebral tardía entre los días 3 y 14.',
          'La descarga catecolaminérgica puede producir miocardiopatía de estrés, arritmias y edema pulmonar neurogénico.',
        ],
      ],
    },
    {
      title: 'Manifestaciones clínicas',
      body: [
        [
          '**Cefalea en trueno**: máxima intensidad en menos de 1 minuto, «la peor de mi vida».',
          'Náuseas y vómitos, fotofobia, rigidez de nuca, pérdida transitoria de conciencia, convulsiones.',
          '**Parálisis del III par con midriasis**: aneurisma de la comunicante posterior.',
          'Hemorragias subhialoideas en el fondo de ojo (síndrome de Terson).',
          '**Cefalea centinela**: episodio previo de cefalea brusca por una pequeña fuga, días o semanas antes.',
        ],
      ],
    },
    {
      title: 'Presentaciones atípicas',
      body: [
        [
          'Cefalea que mejora con analgésicos (no excluye la HSA).',
          'Dolor cervical predominante o síncope.',
          'Confusión o convulsión sin cefalea referida (paciente en coma).',
          'Ausencia de rigidez de nuca en las primeras horas.',
        ],
      ],
    },
    {
      title: 'Estrategia diagnóstica',
      body: [
        [
          '**Regla de Ottawa** (pacientes alertas ≥15 años, cefalea no traumática que alcanza el máximo en 1 h): investigar si hay edad ≥40, dolor o rigidez cervical, pérdida de conciencia presenciada, inicio durante el esfuerzo, cefalea en trueno (máximo instantáneo) o limitación de la flexión cervical. Alta sensibilidad, baja especificidad.',
          '**TC sin contraste**: prueba inicial. En las primeras **6 h**, con equipo moderno e interpretación experta, su sensibilidad es cercana al 100 %; después va disminuyendo.',
          '**TC negativa con sospecha y >6 h** → **punción lumbar** (xantocromía, hematíes que no disminuyen entre tubos) o **angio-TC**.',
          '**Localizar el aneurisma**: angio-TC; la **arteriografía** es el patrón de referencia, sobre todo si la angio-TC es negativa y persiste la sospecha.',
        ],
      ],
    },
    {
      title: 'Escalas de gravedad',
      body: [
        '**Hunt y Hess** (clínica):',
        ['I: asintomático o cefalea leve.', 'II: cefalea moderada-grave, rigidez de nuca, sin déficit (salvo pares craneales).', 'III: somnolencia, confusión o déficit focal leve.', 'IV: estupor, hemiparesia moderada-grave.', 'V: coma profundo, descerebración.'],
        '**WFNS** (GCS y déficit motor): I GCS 15; II GCS 13–14 sin déficit; III GCS 13–14 con déficit; IV GCS 7–12; V GCS 3–6.',
        '**Fisher modificada** (TC; riesgo de vasoespasmo): 0 sin sangre; 1 fina sin hemorragia intraventricular; 2 fina con intraventricular; 3 gruesa sin intraventricular; 4 gruesa con intraventricular.',
      ],
    },
    {
      title: 'Diagnóstico diferencial',
      body: [
        [
          '**Vasoconstricción cerebral reversible**: truenos recurrentes, desencadenantes (esfuerzo, sexo, posparto, fármacos serotoninérgicos o vasoactivos).',
          '**Disección carotídea o vertebral**: dolor cervical, Horner, ictus.',
          '**Apoplejía hipofisaria**: alteración visual, oftalmoplejía, hipotensión.',
          '**Trombosis venosa cerebral**: estado protrombótico, papiledema.',
          'Hemorragia intracerebral, hipotensión intracraneal espontánea (cefalea ortostática), quiste coloide, meningitis, cefalea primaria en trueno (diagnóstico de exclusión).',
        ],
      ],
    },
    {
      title: 'Tratamiento inicial',
      body: [
        [
          'Vía aérea si GCS ≤8 o deterioro; monitorización en una unidad con experiencia neurocrítica y neurovascular (idealmente, un centro con volumen alto).',
          '**Presión arterial**: evitar tanto la hipertensión extrema como la hipotensión; minimizar su variabilidad. La guía de 2023 no fija una cifra basada en evidencia sólida (muchos centros usan PAS <160 mmHg antes de asegurar el aneurisma, objetivo de guías previas).',
          '**Revertir la anticoagulación** y corregir la coagulopatía.',
          'Analgesia, antieméticos, control de la glucemia y de la fiebre; tromboprofilaxis mecánica.',
          '**Nimodipino** 60 mg VO o por sonda cada 4 h durante 21 días, lo antes posible.',
          '**Euvolemia**: evitar la hipovolemia y la hipervolemia.',
          'Derivación urgente de LCR si hay hidrocefalia sintomática.',
        ],
      ],
    },
    {
      title: 'Tratamiento definitivo',
      body: [
        [
          '**Asegurar el aneurisma lo antes posible**: la guía de 2023 sugiere que hacerlo en menos de 24 h es probablemente superior al tratamiento diferido, sobre todo si se retrasa más de 3 días.',
          '**Endovascular** (espirales) o **quirúrgico** (clip), según la anatomía, la localización, la edad y la presencia de hematoma; decisión multidisciplinaria. Cuando ambos son factibles, el tratamiento endovascular se asoció a mejor pronóstico funcional en el ensayo ISAT.',
          'El uso rutinario de antifibrinolíticos no mejora el pronóstico funcional.',
        ],
      ],
    },
    {
      title: 'Complicaciones y su secuencia temporal',
      body: [
        [
          '**Resangrado**: riesgo máximo en las **primeras 24 h** (sobre todo en las primeras horas). Alta mortalidad. Se previene asegurando el aneurisma pronto.',
          '**Hidrocefalia aguda**: deterioro de conciencia; drenaje ventricular externo.',
          '**Isquemia cerebral tardía / vasoespasmo**: **días 3–14**; déficit nuevo o descenso del nivel de conciencia no explicado por otra causa. Vigilancia clínica y con Doppler transcraneal. Tratamiento: euvolemia, **elevación de la PA** en la isquemia sintomática y terapia endovascular (angioplastia o vasodilatadores intraarteriales). **No** se recomienda la hipervolemia profiláctica (el antiguo «triple H»).',
          '**Hiponatremia**: síndrome pierde sal cerebral (hipovolemia) o SIADH; **no restringir líquidos**; salino isotónico o hipertónico, fludrocortisona.',
          '**Convulsiones**: si aparecen, tratar (≈7 días); la profilaxis no es rutinaria; **evitar la fenitoína** en profilaxis.',
          '**Cardiopulmonares**: troponina alta, cambios en el ECG, miocardiopatía de estrés, edema pulmonar neurogénico.',
        ],
      ],
    },
    {
      title: 'Monitorización y metas',
      body: [['Exploración neurológica seriada (GCS, focalidad).', 'Sodio diario o más frecuente; balance hídrico (euvolemia).', 'Doppler transcraneal en los días de riesgo.', 'PA sin extremos; normotermia; normoglucemia.']],
    },
    {
      title: 'Situaciones especiales',
      body: [['**Anticoagulados**: revertir de inmediato.', '**Embarazo**: manejo multidisciplinario; el tratamiento del aneurisma sigue siendo prioritario.', 'Cribado de aneurismas en familiares: con ≥2 familiares de primer grado afectados o poliquistosis renal.']],
    },
    {
      title: 'Errores frecuentes',
      body: [
        [
          'Tranquilizarse porque la cefalea mejora con analgésicos.',
          'Dar el alta con TC negativa después de 6 h sin PL ni angio-TC.',
          'Interpretar como punción traumática un LCR con xantocromía.',
          'Restringir líquidos en la hiponatremia de la HSA.',
          'Hipervolemia «profiláctica».',
          'Profilaxis anticonvulsiva rutinaria con fenitoína.',
          'Bajar la PA agresivamente cuando hay isquemia tardía.',
        ],
      ],
    },
    {
      title: 'Pronóstico',
      body: ['Depende del grado clínico inicial (WFNS o Hunt y Hess), la edad, la cantidad de sangre, el resangrado y la isquemia tardía. La HSA perimesencefálica no aneurismática tiene buen pronóstico.'],
    },
    {
      title: 'Perlas de alto rendimiento',
      body: [
        [
          'Máximo en <1 min = HSA hasta demostrar lo contrario.',
          '**Primeras 24 h → resangrado; días 3–14 → isquemia tardía.**',
          'Nimodipino: mejora el pronóstico, aunque no evita el vasoespasmo angiográfico.',
          'III par con midriasis + cefalea = aneurisma de la comunicante posterior.',
          'Hiponatremia en la HSA: no restrinjas líquidos.',
        ],
      ],
    },
  ],
  items: [
    {
      id: 'q01',
      type: 'mcq',
      sub: 'dx',
      concepts: ['tc', 'pl'],
      diff: 2,
      cat: 'diagnostico',
      stem: 'Mujer de 44 años con cefalea súbita durante el ejercicio, máxima al instante, hace 10 horas. Exploración normal. TC sin contraste normal. ¿Siguiente paso?',
      options: [
        { t: 'Punción lumbar (xantocromía y recuento de hematíes) o angio-TC', why: 'Correcto: han pasado más de 6 h y la sospecha es alta; una TC negativa no basta.' },
        { t: 'Alta con analgésicos: la TC normal descarta la HSA', why: 'Tras 6 h la sensibilidad de la TC disminuye.', err: 'diferencial' },
        { t: 'RM cerebral ambulatoria en unas semanas', why: 'Demora inaceptable.' },
        { t: 'Repetir la TC en 48 h', why: 'Con el tiempo la sensibilidad baja aún más.' },
      ],
      answer: 0,
      explain: ['TC <6 h de alta calidad: prácticamente excluye la HSA.', '>6 h: completar con PL (mejor ≥12 h para la xantocromía) o angio-TC.', 'Cualquier positivo → estudio vascular.'],
      key: ['Inicio durante el esfuerzo', 'Máximo instantáneo', 'Edad ≥40', '>6 h desde el inicio'],
      pearl: 'La regla de las 6 horas depende de **tres condiciones**: TC moderna, radiólogo experto y tiempo exacto desde el inicio.',
      remember: 'TC negativa >6 h + sospecha → PL o angio-TC.',
      compare: ['hsa-cefaleas'],
    },
    {
      id: 'q02',
      type: 'mcq',
      sub: 'tx',
      concepts: ['nimodipino'],
      diff: 1,
      cat: 'tratamiento',
      stem: '¿Cuál es el papel del nimodipino en la HSA aneurismática?',
      options: [
        { t: '60 mg por vía enteral cada 4 h durante 21 días: mejora el pronóstico funcional', why: 'Correcto.' },
        { t: 'Controlar la PA de forma agresiva', why: 'No es su indicación; la hipotensión es un efecto adverso que debe evitarse.', err: 'tratamiento' },
        { t: 'Prevenir el resangrado', why: 'No previene el resangrado.' },
        { t: 'Tratar el vasoespasmo angiográfico ya establecido', why: 'Mejora el pronóstico, pero no revierte el vasoespasmo angiográfico.' },
      ],
      answer: 0,
      explain: ['Beneficio en el pronóstico, probablemente por neuroprotección.', 'Si produce hipotensión: fraccionar la dosis (30 mg cada 2 h).', 'Vía enteral; la IV no está recomendada de rutina.'],
      pearl: 'Nimodipino: 60 mg / 4 h / 21 días.',
      remember: 'Mejora el pronóstico, no el vasoespasmo angiográfico.',
    },
    {
      id: 'q03',
      type: 'mcq',
      sub: 'comp',
      concepts: ['dci'],
      diff: 2,
      cat: 'complicaciones',
      stem: 'Día 6 tras una HSA con aneurisma embolizado. Aparecen afasia y debilidad del brazo derecho. Na⁺ 139, glucosa normal, sin fiebre. ¿Sospecha y conducta?',
      options: [
        { t: 'Isquemia cerebral tardía: angio-TC o TC de perfusión, euvolemia, elevar la PA y valorar tratamiento endovascular', why: 'Correcto: déficit nuevo en la ventana de los días 3–14.' },
        { t: 'Resangrado: nueva embolización', why: 'El aneurisma está asegurado y el momento es típico de isquemia tardía.', err: 'complicaciones' },
        { t: 'Restricción hídrica y bajar la PA', why: 'Empeoraría la perfusión.', err: 'tratamiento' },
        { t: 'Aumentar el nimodipino a 120 mg', why: 'No tiene papel y aumenta la hipotensión.' },
      ],
      answer: 0,
      explain: ['Ventana de los días 3–14.', 'Descartar hidrocefalia, crisis, alteraciones metabólicas.', 'Tratamiento: perfusión (PA, volumen) y endovascular si es refractaria.'],
      pearl: 'En la isquemia tardía, **subir la PA** (no bajarla) con el aneurisma ya asegurado.',
      remember: 'Déficit nuevo entre los días 3 y 14 = isquemia tardía.',
      compare: ['hsa-complicaciones'],
    },
    {
      id: 'q04',
      type: 'mcq',
      sub: 'comp',
      concepts: ['hiponatremia'],
      diff: 2,
      cat: 'complicaciones',
      stem: 'Día 5 de una HSA: Na⁺ 128 mEq/L, diuresis abundante, balance negativo, taquicardia. ¿Mecanismo probable y conducta?',
      options: [
        { t: 'Síndrome pierde sal cerebral: reponer volumen y sodio (salino isotónico o hipertónico, fludrocortisona)', why: 'Correcto: hiponatremia con hipovolemia y natriuresis.' },
        { t: 'SIADH: restricción de líquidos', why: 'En la HSA, la restricción aumenta el riesgo de isquemia tardía; además hay hipovolemia.', err: 'tratamiento' },
        { t: 'Hiponatremia dilucional: furosemida', why: 'Empeora la hipovolemia.', err: 'tratamiento' },
        { t: 'Seudohiponatremia: no hacer nada', why: 'No hay datos que la sugieran.' },
      ],
      answer: 0,
      explain: ['Pierde sal cerebral: natriuresis + hipovolemia.', 'SIADH: euvolemia.', 'En ambos casos, en la HSA **no** se restringen líquidos.'],
      pearl: 'La hipovolemia en la HSA favorece la isquemia tardía.',
      remember: 'HSA + hiponatremia → sodio y volumen, nunca restricción.',
    },
    {
      id: 'q05',
      type: 'mcq',
      sub: 'comp',
      concepts: ['resangrado', 'aneurisma_tx'],
      diff: 2,
      cat: 'complicaciones',
      stem: '¿Cuándo es máximo el riesgo de resangrado de un aneurisma roto y cómo se reduce?',
      options: [
        { t: 'En las primeras 24 h: tratar el aneurisma lo antes posible', why: 'Correcto.' },
        { t: 'Entre los días 3 y 14: nimodipino', why: 'Esa es la ventana de la isquemia tardía; el nimodipino no previene el resangrado.', err: 'complicaciones' },
        { t: 'Al mes: antifibrinolíticos prolongados', why: 'El riesgo es máximo al inicio; los antifibrinolíticos no mejoran el pronóstico.', err: 'tratamiento' },
        { t: 'Es constante: reposo absoluto 3 semanas', why: 'El reposo no sustituye al tratamiento del aneurisma.' },
      ],
      answer: 0,
      explain: ['Resangrado: precoz y con mortalidad alta.', 'Aneurisma asegurado idealmente en <24 h.', 'Control de la PA y reversión de la anticoagulación mientras tanto.'],
      pearl: 'Primeras horas = resangrado; primeras dos semanas = isquemia tardía.',
      remember: 'Asegurar el aneurisma pronto.',
      compare: ['hsa-complicaciones'],
    },
    {
      id: 'q06',
      type: 'mcq',
      sub: 'dx',
      concepts: ['diferencial'],
      diff: 3,
      cat: 'diferencial',
      stem: 'Mujer de 36 años, 2 semanas después del parto, con 4 episodios de cefalea en trueno en 8 días, uno tras una ducha caliente. TC: pequeña HSA en la convexidad. Angio-TC: estenosis multifocales en varias arterias, sin aneurismas. ¿Diagnóstico más probable?',
      options: [
        { t: 'Síndrome de vasoconstricción cerebral reversible', why: 'Correcto: truenos recurrentes, posparto, desencadenantes, estenosis multifocales y HSA de convexidad.' },
        { t: 'HSA aneurismática', why: 'No hay aneurisma y el patrón de sangre (convexidad) y la recurrencia sugieren otra causa.', err: 'diferencial' },
        { t: 'Vasculitis primaria del SNC', why: 'La vasculitis suele tener una evolución subaguda sin truenos recurrentes.', err: 'diferencial' },
        { t: 'Migraña', why: 'La migraña no produce truenos recurrentes con HSA.', err: 'diferencial' },
      ],
      answer: 0,
      explain: ['Truenos **recurrentes** → vasoconstricción cerebral reversible.', 'Desencadenantes: posparto, fármacos vasoactivos, esfuerzo, sexo, ducha.', 'Las estenosis se revierten en unas 12 semanas.', 'Tratamiento: suspender los desencadenantes; se suele usar nimodipino o verapamilo; evitar los glucocorticoides.'],
      pearl: 'Un solo trueno → HSA; **varios truenos en días** → vasoconstricción cerebral reversible.',
      remember: 'Recurrencia + posparto + estenosis que se revierten.',
      compare: ['hsa-cefaleas'],
    },
    {
      id: 'q07',
      type: 'mcq',
      sub: 'dx',
      concepts: ['clinica', 'etiologia'],
      diff: 2,
      cat: 'diagnostico',
      stem: 'Varón de 52 años con cefalea súbita y ptosis derecha con midriasis. ¿Qué localización del aneurisma es más probable?',
      options: [
        { t: 'Arteria comunicante posterior', why: 'Correcto: comprime el III par (las fibras pupilares son superficiales).' },
        { t: 'Arteria comunicante anterior', why: 'Suele producir alteraciones frontales o de conducta, no parálisis del III par.' },
        { t: 'Arteria cerebral media', why: 'Puede producir hemiparesia o afasia por hematoma.' },
        { t: 'Arteria basilar', why: 'Menos típica para una parálisis aislada del III par con midriasis.' },
      ],
      answer: 0,
      explain: ['III par «quirúrgico» (con midriasis): compresión.', 'III par «médico» (pupila respetada): isquemia microvascular (diabetes).'],
      pearl: 'Una parálisis del III par **con midriasis** es un aneurisma hasta demostrar lo contrario.',
      remember: 'III par + midriasis → comunicante posterior.',
    },
    {
      id: 'q08',
      type: 'mcq',
      sub: 'comp',
      concepts: ['convulsiones'],
      diff: 2,
      cat: 'tratamiento',
      stem: 'Sobre las convulsiones en la HSA, según la guía AHA/ASA 2023, ¿qué es correcto?',
      options: [
        { t: 'La profilaxis no es rutinaria; si hay crisis se tratan (≈7 días) y se evita la fenitoína', why: 'Correcto.' },
        { t: 'Todos deben recibir fenitoína profiláctica 3 meses', why: 'La fenitoína se asocia a peor pronóstico.', err: 'tratamiento' },
        { t: 'Las convulsiones no ocurren en la HSA', why: 'Pueden aparecer al inicio o después.' },
        { t: 'La profilaxis con benzodiacepinas en perfusión está indicada', why: 'No.' },
      ],
      answer: 0,
      explain: ['Profilaxis no rutinaria; puede considerarse en pacientes de alto riesgo.', 'Tratar las crisis clínicas.', 'EEG si el coma no se explica (estado no convulsivo).'],
      pearl: 'Coma que no mejora tras la HSA → piensa en un **estado epiléptico no convulsivo**.',
      remember: 'No a la fenitoína profiláctica.',
    },
    {
      id: 'q09',
      type: 'mcq',
      sub: 'dx',
      concepts: ['ottawa'],
      diff: 2,
      cat: 'diagnostico',
      stem: 'Según la regla de Ottawa para la HSA, ¿cuál de estos pacientes con cefalea aguda puede no requerir estudios adicionales?',
      options: [
        { t: 'Mujer de 28 años, cefalea que llegó al máximo en 40 minutos, sin dolor cervical, sin pérdida de conciencia, en reposo, con flexión cervical normal', why: 'Correcto: no cumple ningún criterio de alto riesgo.' },
        { t: 'Varón de 45 años con cefalea brusca', why: 'La edad ≥40 obliga a investigar.', err: 'conocimiento' },
        { t: 'Joven con cefalea brusca y síncope presenciado', why: 'La pérdida de conciencia presenciada obliga a investigar.' },
        { t: 'Joven con cefalea al levantar pesas', why: 'El inicio durante el esfuerzo obliga a investigar.' },
      ],
      answer: 0,
      explain: ['Criterios: edad ≥40, dolor o rigidez cervical, pérdida de conciencia presenciada, inicio con esfuerzo, trueno (máximo instantáneo), limitación de la flexión cervical.', 'Aplica solo a pacientes alertas sin déficit ni antecedentes de aneurisma.'],
      pearl: 'La regla es **sensible**, no específica: sirve para descartar, no para diagnosticar.',
      remember: 'Ottawa: 40, cuello, síncope, esfuerzo, trueno, flexión.',
    },
    {
      id: 'q10',
      type: 'mcq',
      sub: 'comp',
      concepts: ['hidrocefalia'],
      diff: 2,
      cat: 'complicaciones',
      stem: 'Horas después de una HSA (Hunt y Hess II), el paciente se vuelve somnoliento con mirada desviada hacia abajo. La TC muestra ventrículos dilatados sin nuevo sangrado. ¿Conducta?',
      options: [
        { t: 'Drenaje ventricular externo urgente', why: 'Correcto: hidrocefalia aguda sintomática.' },
        { t: 'Manitol y observación', why: 'No resuelve la obstrucción del LCR.', err: 'tratamiento' },
        { t: 'Punción lumbar evacuadora', why: 'En la hidrocefalia obstructiva puede ser peligrosa; la guía acepta el drenaje lumbar en casos seleccionados, pero el estándar es el ventricular.' },
        { t: 'Esperar al día 3', why: 'Demora peligrosa.' },
      ],
      answer: 0,
      explain: ['La sangre obstruye la circulación o la reabsorción del LCR.', 'Derivación urgente de LCR (DVE), con un protocolo que reduzca las infecciones.'],
      pearl: 'La mirada desviada hacia abajo («sol poniente») es un signo de hidrocefalia.',
      remember: 'Hidrocefalia sintomática → DVE.',
      compare: ['hsa-complicaciones'],
    },

    // ---------- Casos ----------
    {
      id: 'c01',
      type: 'case',
      sub: 'dx',
      concepts: ['clinica', 'tc', 'escalas', 'manejo_inicial'],
      diff: 2,
      cat: 'integracion',
      title: 'La peor cefalea de su vida',
      patient: { age: 49, sex: 'F' },
      vignette: ['Mujer de 49 años, fumadora e hipertensa mal controlada, con cefalea súbita occipital mientras cargaba cajas, «como un golpe», máxima en segundos. Vomitó dos veces y se desmayó brevemente. Hace 10 días tuvo otra cefalea brusca, menos intensa, que cedió con paracetamol. Toma apixabán por una FA.'],
      vitals: { PA: '188/102 mmHg', FC: '64 lpm', T: '36,8 °C', GCS: '14 (confusa)' },
      exam: 'Rigidez de nuca. Sin focalidad motora. Pupilas simétricas y reactivas.',
      imaging: 'TC craneal sin contraste (1 h desde el inicio): sangre en las cisternas basales y las cisuras de Silvio, capa gruesa, sin hemorragia intraventricular. Ventrículos normales.',
      questions: [
        {
          stem: '¿Qué dato de la historia es una **cefalea centinela**?',
          cat: 'concepto',
          concepts: ['clinica'],
          options: [
            { t: 'La cefalea brusca de hace 10 días que cedió con paracetamol', why: 'Correcto: pequeña fuga previa a la rotura mayor.' },
            { t: 'Los vómitos', why: 'Son parte del cuadro actual.' },
            { t: 'El síncope', why: 'Pérdida de conciencia del episodio actual.' },
            { t: 'La HTA', why: 'Es un factor de riesgo, no una cefalea.' },
          ],
          answer: 0,
          explain: ['La cefalea centinela aparece días o semanas antes.', 'Mejorar con analgésicos no la descarta.'],
          pearl: 'Pregunta siempre por **cefaleas bruscas previas**.',
        },
        {
          stem: '¿Qué grado WFNS y qué Fisher modificado tiene?',
          cat: 'diagnostico',
          concepts: ['escalas'],
          options: [
            { t: 'WFNS II (GCS 14 sin déficit) y Fisher modificado 3 (sangre gruesa sin intraventricular)', why: 'Correcto.' },
            { t: 'WFNS I y Fisher 1', why: 'GCS 14 no es 15 y la capa es gruesa.', err: 'conocimiento' },
            { t: 'WFNS IV y Fisher 4', why: 'GCS 14 no es 7–12 y no hay sangre intraventricular.', err: 'conocimiento' },
            { t: 'WFNS III y Fisher 2', why: 'No hay déficit motor ni hemorragia intraventricular.', err: 'conocimiento' },
          ],
          answer: 0,
          explain: ['WFNS: GCS 13–14 sin déficit = II.', 'Fisher modificado: gruesa sin intraventricular = 3 → riesgo de vasoespasmo elevado.'],
          pearl: 'Un Fisher alto predice **vasoespasmo**; el WFNS o el Hunt y Hess, el **pronóstico**.',
        },
        {
          stem: '¿Cuál es el conjunto de medidas inmediatas más adecuado?',
          cat: 'secuencia',
          concepts: ['manejo_inicial', 'nimodipino', 'aneurisma_tx'],
          options: [
            { t: 'Revertir el apixabán (andexanet alfa o complejo protrombínico), control de la PA evitando extremos, analgesia, nimodipino, angio-TC y tratamiento del aneurisma idealmente en <24 h', why: 'Correcto.' },
            { t: 'Bajar la PA a 100/60 de inmediato', why: 'La hipotensión compromete la perfusión cerebral.', err: 'tratamiento' },
            { t: 'Mantener el apixabán para prevenir un ictus embólico', why: 'La hemorragia activa exige revertir la anticoagulación.', err: 'tratamiento' },
            { t: 'Esperar a la arteriografía programada a la semana', why: 'Retrasar el tratamiento aumenta el riesgo de resangrado.', err: 'secuencia' },
          ],
          answer: 0,
          explain: ['Revertir la anticoagulación.', 'PA sin extremos (muchos centros: PAS <160 antes de asegurar el aneurisma).', 'Nimodipino precoz.', 'Localizar y asegurar el aneurisma pronto.'],
          pearl: 'Las primeras horas deciden el riesgo de **resangrado**.',
        },
      ],
    },
    {
      id: 'c02',
      type: 'case',
      sub: 'dx',
      concepts: ['pl', 'tc', 'angio'],
      diff: 3,
      cat: 'integracion',
      title: 'TC normal a las 14 horas',
      patient: { age: 41, sex: 'M' },
      vignette: ['Varón de 41 años con cefalea súbita durante una relación sexual hace 14 horas, «la peor de su vida», con vómitos. Ahora le duele menos. Exploración neurológica normal. TC sin contraste: normal. Se realiza una punción lumbar.'],
      labs: [
        { p: 'lcrpres', v: 24 },
        { p: 'lcrhem', v: 3200, name: 'Hematíes LCR (tubo 1)' },
        { name: 'Hematíes LCR (tubo 4)', v: 2900, unit: '/µL', ref: '0–5', flag: 'H' },
        { p: 'xanto', text: 'Presente', flag: 'H' },
        { name: 'Leucocitos LCR', v: 4, unit: '/µL', ref: '0–5', flag: 'N' },
      ],
      questions: [
        {
          stem: '¿Cómo interpretas el LCR?',
          cat: 'laboratorio',
          concepts: ['pl'],
          options: [
            { t: 'Compatible con HSA: xantocromía presente y hematíes que no disminuyen entre los tubos 1 y 4', why: 'Correcto.' },
            { t: 'Punción traumática', why: 'En la traumática los hematíes disminuyen y no hay xantocromía.', err: 'laboratorio' },
            { t: 'Meningitis', why: 'Sin pleocitosis.', err: 'diferencial' },
            { t: 'Normal', why: 'Hay sangre y xantocromía.', err: 'laboratorio' },
          ],
          answer: 0,
          explain: ['La xantocromía indica sangre degradada desde hace horas.', 'Recuento estable entre tubos.', 'Presión de apertura algo elevada.'],
          key: ['Xantocromía', 'Hematíes 3200 → 2900'],
          pearl: 'La xantocromía es más fiable que la caída del recuento entre tubos.',
        },
        {
          stem: '¿Cuál es el siguiente paso?',
          cat: 'secuencia',
          concepts: ['angio'],
          options: [
            { t: 'Angio-TC y, si es negativa con sospecha alta, arteriografía', why: 'Correcto: localizar el aneurisma.' },
            { t: 'Alta con analgesia', why: 'Hay HSA confirmada.', err: 'razonamiento' },
            { t: 'Repetir la PL en 24 h', why: 'No aporta nada.' },
            { t: 'RM funcional', why: 'No es el estudio indicado.' },
          ],
          answer: 0,
          explain: ['Después de confirmar la HSA: estudio vascular.', 'La arteriografía es el patrón de referencia.'],
          pearl: 'TC negativa + PL positiva = HSA real con poca sangre: el aneurisma **sigue** siendo peligroso.',
        },
      ],
    },

    // ---------- Progresivo ----------
    {
      id: 'p01',
      type: 'progressive',
      sub: 'comp',
      concepts: ['resangrado', 'hidrocefalia', 'dci', 'hiponatremia', 'nimodipino'],
      diff: 3,
      cat: 'complicaciones',
      title: 'Dos semanas en la UCI',
      stages: [
        {
          id: 's1',
          title: 'Día 0',
          text: ['Varón de 55 años con HSA (Hunt y Hess III, Fisher modificado 4) por un aneurisma de la comunicante anterior. PA 176/98. GCS 13.'],
          q: {
            stem: '¿Qué prioridad tiene el primer día?',
            options: [
              { t: 'Asegurar el aneurisma lo antes posible (ideal <24 h), nimodipino, PA sin extremos y vigilancia de la hidrocefalia', why: 'Correcto.' },
              { t: 'Esperar al día 10 para operar cuando pase el vasoespasmo', why: 'El resangrado precoz es la amenaza principal.', err: 'secuencia', next: 's1b' },
              { t: 'Hipervolemia profiláctica', why: 'No se recomienda.', err: 'tratamiento' },
              { t: 'Fenitoína profiláctica', why: 'No se recomienda.', err: 'tratamiento' },
            ],
            answer: 0,
            explain: ['Resangrado: riesgo máximo en las primeras 24 h.', 'Tratamiento precoz del aneurisma.'],
            pearl: 'El tiempo hasta asegurar el aneurisma es una medida de calidad.',
          },
          goto: 's2',
        },
        {
          id: 's1b',
          title: 'Día 1 · Complicación',
          tone: 'alert',
          text: ['A las 20 h, cefalea brusca nueva y el GCS cae a 6. La TC muestra más sangre e inundación ventricular.'],
          q: {
            stem: '¿Qué ha ocurrido?',
            options: [
              { t: 'Resangrado del aneurisma no tratado', why: 'Correcto.' },
              { t: 'Vasoespasmo', why: 'Demasiado precoz; y hay sangre nueva.', err: 'complicaciones' },
              { t: 'Hiponatremia', why: 'No explica la sangre nueva.' },
              { t: 'Crisis de migraña', why: 'No.' },
            ],
            answer: 0,
            explain: ['El resangrado tiene una mortalidad muy alta.', 'Se previene con el tratamiento precoz del aneurisma.'],
            pearl: 'Deterioro brusco + sangre nueva en las primeras 24 h = resangrado.',
          },
          goto: 's2',
        },
        {
          id: 's2',
          title: 'Día 1 · Tras la embolización',
          text: ['Aneurisma embolizado con éxito. Por la tarde, GCS 10, mirada desviada hacia abajo. TC: ventrículos dilatados.'],
          q: {
            stem: '¿Conducta?',
            options: [
              { t: 'Drenaje ventricular externo urgente', why: 'Correcto: hidrocefalia aguda sintomática.' },
              { t: 'Observar 48 h', why: 'Riesgo de herniación.', err: 'complicaciones' },
              { t: 'Nimodipino IV en bolo', why: 'No trata la hidrocefalia.' },
              { t: 'Restricción hídrica', why: 'No trata la hidrocefalia y es perjudicial.' },
            ],
            answer: 0,
            explain: ['Hidrocefalia: derivación de LCR.', 'Protocolo de cuidado del drenaje para reducir infecciones.'],
            pearl: 'Tras un deterioro, pregunta siempre: ¿**sangre nueva**, **ventrículos** o **isquemia**?',
          },
        },
        {
          id: 's3',
          title: 'Día 5',
          text: ['GCS 14 con el drenaje funcionando. Na⁺ 127 mEq/L, diuresis de 4 L/día, balance negativo, taquicardia.'],
          labs: [{ p: 'na', v: 127 }],
          q: {
            stem: '¿Qué haces con la hiponatremia?',
            options: [
              { t: 'Reponer volumen y sodio (salino isotónico o hipertónico, fludrocortisona), sin restricción hídrica', why: 'Correcto: probable síndrome pierde sal cerebral.' },
              { t: 'Restricción hídrica a 800 mL/día', why: 'Hipovolemia → riesgo de isquemia tardía.', err: 'tratamiento', next: 's4b' },
              { t: 'Vaptanes', why: 'Favorecen la pérdida de volumen: no son adecuados aquí.', err: 'tratamiento' },
              { t: 'Ignorarla', why: 'Empeoraría.' },
            ],
            answer: 0,
            explain: ['Pierde sal cerebral: natriuresis + hipovolemia.', 'Euvolemia y sodio.'],
            pearl: 'En la HSA, la hipovolemia y la hiponatremia **predisponen a la isquemia tardía**.',
          },
          goto: 's4',
        },
        {
          id: 's4b',
          title: 'Día 7 · Complicación',
          tone: 'alert',
          text: ['Tras 2 días de restricción hídrica, aparecen hemiparesia izquierda y abulia. Doppler: velocidades en la ACA de 190 cm/s.'],
          labs: [{ p: 'dtc', v: 190, name: 'Velocidad media en la ACA derecha (DTC)' }],
          q: {
            stem: '¿Qué ha pasado y qué haces?',
            options: [
              { t: 'Isquemia tardía favorecida por la hipovolemia: restaurar la euvolemia, elevar la PA y valorar terapia endovascular', why: 'Correcto.' },
              { t: 'Resangrado', why: 'El aneurisma está embolizado; el momento y el Doppler sugieren vasoespasmo.', err: 'complicaciones' },
              { t: 'Mantener la restricción', why: 'No.' },
              { t: 'Bajar la PA', why: 'Empeoraría la isquemia.', err: 'tratamiento' },
            ],
            answer: 0,
            explain: ['La hipovolemia agrava la isquemia tardía.', 'Tratamiento: perfusión y endovascular.'],
            pearl: 'Un error en el manejo del sodio puede traducirse en un déficit neurológico.',
          },
          goto: 's5',
        },
        {
          id: 's4',
          title: 'Día 8',
          text: ['Súbitamente aparecen abulia y debilidad de la pierna izquierda. Na⁺ 136. Sin fiebre. El drenaje funciona. Doppler: velocidades elevadas en la ACA derecha.'],
          labs: [{ p: 'dtc', v: 165, name: 'Velocidad media en la ACA derecha (DTC)' }],
          q: {
            stem: '¿Diagnóstico y tratamiento?',
            options: [
              { t: 'Isquemia cerebral tardía en el territorio de la ACA: elevar la PA (aneurisma asegurado), euvolemia, angio-TC o perfusión y terapia endovascular si no responde', why: 'Correcto.' },
              { t: 'Crisis parcial: fenitoína', why: 'El déficit y el Doppler apuntan a isquemia.', err: 'diferencial' },
              { t: 'Hipervolemia agresiva', why: 'No se recomienda.', err: 'tratamiento' },
              { t: 'Suspender el nimodipino', why: 'Se mantiene los 21 días.' },
            ],
            answer: 0,
            explain: ['Ventana de los días 3–14.', 'ACA: debilidad de la pierna y abulia.'],
            pearl: 'Comunicante anterior → la isquemia tardía suele afectar al territorio de la **ACA**.',
          },
        },
        {
          id: 's5',
          title: 'Cierre',
          end: true,
          text: ['Tras angioplastia química, el déficit mejora. Completa 21 días de nimodipino. Alta a rehabilitación con valoración neuropsicológica.'],
        },
      ],
    },

    // ---------- Razonamiento ----------
    {
      id: 'r01',
      type: 'reasoning',
      sub: 'dx',
      concepts: ['clinica', 'ottawa', 'tc', 'diferencial'],
      diff: 2,
      cat: 'razonamiento',
      title: 'Cefalea en trueno en urgencias',
      vignette: ['Mujer de 47 años con cefalea súbita al hacer ejercicio, máxima en segundos, hace 3 horas. Vomitó una vez. Está alerta, sin focalidad. Refiere dolor cervical.'],
      prompts: [
        {
          q: '¿Qué datos te llaman la atención y qué significan?',
          expected: 'Inicio súbito con máximo en segundos (cefalea en trueno), durante el esfuerzo, edad ≥40, dolor cervical y vómitos: criterios de alto riesgo de HSA (regla de Ottawa) que obligan a descartarla.',
          points: [
            { t: 'Máximo en segundos (trueno)', kw: ['trueno', 'subit', 'segundos', 'brusc'] },
            { t: 'Inicio con el esfuerzo', kw: ['esfuerzo', 'ejercicio'] },
            { t: 'Edad ≥40', kw: ['40', 'edad'] },
            { t: 'Dolor cervical (meningismo)', kw: ['cervical', 'cuello', 'nuca', 'mening'] },
          ],
        },
        {
          q: '¿Cuál es tu diagnóstico diferencial?',
          expected: 'HSA aneurismática (principal), vasoconstricción cerebral reversible, disección cervical, apoplejía hipofisaria, trombosis venosa cerebral, hemorragia intracerebral, cefalea primaria en trueno o de esfuerzo (de exclusión).',
          points: [
            { t: 'HSA', kw: ['hsa', 'subaracnoid', 'aneurism'] },
            { t: 'Vasoconstricción cerebral reversible', kw: ['vasoconstric', 'svcr', 'rcvs'] },
            { t: 'Disección arterial cervical', kw: ['diseccion'] },
            { t: 'Otras: apoplejía hipofisaria, trombosis venosa', kw: ['apoplejia', 'hipofis', 'trombosis venosa', 'tvc', 'senos venosos'] },
          ],
        },
        {
          q: '¿Qué estudio pedirías primero y cómo interpretarías un resultado negativo?',
          expected: 'TC craneal sin contraste de inmediato. Como han pasado <6 h, una TC de buena calidad negativa, interpretada por un experto, prácticamente excluye la HSA; si hubieran pasado >6 h o hubiera dudas técnicas, completaría con PL (xantocromía) o angio-TC.',
          points: [
            { t: 'TC sin contraste inmediata', kw: ['tc', 'tac', 'tomografia'] },
            { t: 'Regla de las 6 horas', kw: ['6 h', '6h', 'seis horas', '6 horas'] },
            { t: 'PL o angio-TC si procede', kw: ['puncion', 'pl', 'xantocrom', 'angio'] },
          ],
          pearl: 'La hora exacta de inicio es un **dato diagnóstico**: pregúntala con precisión.',
        },
      ],
    },

    // ---------- Laboratorio ----------
    {
      id: 'l01',
      type: 'lab',
      sub: 'dx',
      concepts: ['pl'],
      diff: 2,
      cat: 'laboratorio',
      title: 'LCR: ¿traumática o HSA?',
      context: 'Varón de 38 años con cefalea brusca hace 16 horas y TC normal. Punción lumbar, primer intento con dificultad:',
      labs: [
        { p: 'lcrhem', v: 8400, name: 'Hematíes LCR (tubo 1)' },
        { name: 'Hematíes LCR (tubo 4)', v: 120, unit: '/µL', ref: '0–5', flag: 'H' },
        { p: 'xanto', text: 'Ausente', flag: 'N' },
        { p: 'lcrpres', v: 16 },
        { name: 'Leucocitos LCR', v: 9, unit: '/µL', ref: '0–5', flag: 'H' },
        { name: 'Proteínas LCR', v: 42, unit: 'mg/dL', ref: '15–45', flag: 'N' },
      ],
      steps: [
        { kind: 'flags', cat: 'laboratorio' },
        {
          kind: 'mcq',
          cat: 'laboratorio',
          stem: '¿Qué patrón es más probable?',
          options: [
            { t: 'Punción traumática: los hematíes caen mucho del tubo 1 al 4 y no hay xantocromía a las 16 h', why: 'Correcto.' },
            { t: 'HSA confirmada', why: 'A las 16 h debería haber xantocromía y el recuento no caería tanto.', err: 'laboratorio' },
            { t: 'Meningitis bacteriana', why: 'Pleocitosis mínima proporcional a la sangre; proteínas normales.', err: 'diferencial' },
            { t: 'Hipertensión intracraneal idiopática', why: 'Presión normal.', err: 'diferencial' },
          ],
          answer: 0,
          explain: ['Descenso marcado del recuento entre tubos → traumática.', 'Xantocromía ausente a las 16 h → en contra de HSA.', 'Leucocitos leves: sangre periférica (≈1 leucocito por cada 500–1000 hematíes).'],
          pearl: 'Si hay dudas (por ejemplo, recuento persistente), la **angio-TC** ayuda a resolverlas.',
        },
        {
          kind: 'mcq',
          cat: 'secuencia',
          stem: '¿Qué haces ahora?',
          options: [
            { t: 'Si la sospecha clínica sigue siendo alta o hay dudas técnicas, angio-TC; si no, buscar otras causas de la cefalea', why: 'Correcto: la integración clínica decide.' },
            { t: 'Arteriografía urgente en todos los casos', why: 'No está indicada de rutina con PL negativa y TC normal.' },
            { t: 'Tratar como HSA con nimodipino', why: 'No hay HSA demostrada.' },
            { t: 'Repetir la PL en el mismo espacio', why: 'No aporta nada.' },
          ],
          answer: 0,
          explain: ['Una PL traumática sin xantocromía hace muy improbable la HSA.', 'Si persiste la sospecha, la angio-TC es la alternativa.'],
          pearl: 'La xantocromía se busca **espectrofotométricamente** o por inspección del sobrenadante centrifugado.',
        },
      ],
    },
  ],
});
