/* Comparaciones de alto rendimiento: el dato que inclina el diagnóstico.
 * Los ítems de los temas se vinculan con compare: ['id'] y aparecen en
 * «Practicar esta comparación». */
SolMed.registry.addComparisons([
  {
    id: 'cad-ehh',
    title: 'CAD vs EHH',
    subtitle: 'Dos extremos de un mismo espectro: cetoacidosis frente a hiperosmolalidad.',
    topics: ['cad', 'ehh'],
    columns: ['CAD', 'EHH'],
    rows: [
      ['Mecanismo', 'Déficit **absoluto** (o grave) de insulina → lipólisis y cetogénesis', 'Déficit **relativo**: queda insulina suficiente para frenar la cetogénesis, no la hiperglucemia'],
      ['Paciente típico', 'DM1, joven; también DM2 con estrés o iSGLT2', 'DM2, anciano, con acceso limitado al agua'],
      ['Evolución', 'Horas a 1–2 días', 'Días a semanas'],
      ['Glucosa', '≥200 mg/dL (o DM conocida; puede ser casi normal con iSGLT2)', '≥600 mg/dL (a menudo >1000)'],
      ['β-OHB', '**≥3,0 mmol/L**', '<3,0 mmol/L'],
      ['pH / HCO₃⁻', 'pH <7,3 y/o HCO₃⁻ <18', 'pH ≥7,3 y HCO₃⁻ ≥15'],
      ['Osmolalidad efectiva', 'Variable, a menudo <320', '**>300** (total >320)'],
      ['Clínica llamativa', 'Kussmaul, aliento cetósico, dolor abdominal, vómitos', 'Deshidratación extrema, alteración neurológica (focalidad, convulsiones, coma)'],
      ['Déficit de agua', '≈6 L', '≈9 L o más'],
      ['Insulina', '0,1 U/kg/h (o SC en casos leves-moderados); añadir dextrosa con glucosa <250', 'Tras la reposición inicial y cuando la glucosa deje de bajar con líquidos; dosis menor (≈0,05 U/kg/h); dextrosa con glucosa <300'],
      ['Mortalidad', '<1–2 % en adultos', 'Mayor (5–20 %): edad, comorbilidad'],
    ],
    decisive:
      'El **β-hidroxibutirato** y el **estado ácido-base** deciden: cetonemia ≥3,0 con acidosis = CAD; glucosa ≥600 y osmolalidad efectiva >300 sin cetoacidosis = EHH. Hasta un tercio de los pacientes tienen un cuadro **mixto**: si cumple ambos, trátalo como ambos.',
    pitfalls: [
      'Descartar una CAD porque la glucosa «solo» es 240 mg/dL en un paciente con iSGLT2 (CAD euglucémica).',
      'Atribuir el coma a la hiperglucemia con osmolalidad efectiva <320: busca otra causa.',
      'Bajar la glucosa o el sodio demasiado rápido en el EHH (riesgo de edema cerebral y mielinólisis).',
    ],
    sources: ['ada2024', 'jbds'],
  },
  {
    id: 'hiper-tirotox',
    title: 'Hipertiroidismo vs tirotoxicosis',
    subtitle: 'No toda tirotoxicosis es hipertiroidismo.',
    topics: ['hipertiroidismo'],
    columns: ['Hipertiroidismo', 'Tirotoxicosis sin hipertiroidismo'],
    rows: [
      ['Definición', 'La tiroides **produce** hormona en exceso', 'Exceso de hormona circulante sin hiperproducción: destrucción glandular o fuente exógena'],
      ['Causas', 'Graves, bocio multinodular tóxico, adenoma tóxico, TSH-oma (raro)', 'Tiroiditis (subaguda, silente, posparto), levotiroxina en exceso o facticia, amiodarona tipo 2'],
      ['Captación de yodo', '**Alta** (difusa en Graves; focal o parcheada en nódulos)', '**Baja**'],
      ['Duración', 'Persistente sin tratamiento', 'Transitoria (semanas); puede seguirle una fase hipotiroidea'],
      ['Tratamiento', 'Antitiroideos, radioyodo o cirugía, más betabloqueo', 'Betabloqueo; AINE o glucocorticoides en la subaguda; **no** antitiroideos'],
    ],
    decisive: 'La **captación de yodo radiactivo** (o TRAb + Doppler cuando la captación está contraindicada) separa la hiperproducción de la liberación o del aporte externo.',
    pitfalls: ['Dar metimazol a una tiroiditis: no hay síntesis que bloquear.', 'Pedir gammagrafía a una embarazada: está contraindicada.'],
    sources: ['ata2016'],
  },
  {
    id: 'graves-otras',
    title: 'Graves vs otras causas de hipertiroidismo',
    subtitle: 'Autoinmune difusa frente a nódulos autónomos.',
    topics: ['hipertiroidismo'],
    columns: ['Graves', 'Bocio multinodular tóxico', 'Adenoma tóxico'],
    rows: [
      ['Paciente', 'Mujer de 20–50 años', 'Mayor de 50–60, zonas con déficit de yodo', 'Cualquier edad adulta'],
      ['Exploración', 'Bocio difuso, soplo; **orbitopatía**, dermopatía pretibial', 'Bocio nodular', 'Nódulo palpable único'],
      ['TRAb', '**Positivos**', 'Negativos', 'Negativos'],
      ['Captación', 'Difusa y aumentada', 'Parcheada', 'Nódulo «caliente» con el resto suprimido'],
      ['Remisión', 'Posible con antitiroideos (≈30–50 %)', 'No remite', 'No remite'],
      ['Tratamiento definitivo', 'Metimazol 12–18 meses, radioyodo o cirugía', 'Radioyodo o cirugía', 'Radioyodo o cirugía'],
    ],
    decisive: '**Orbitopatía o dermopatía** = Graves (solo Graves las produce). Sin ellas, TRAb positivos o captación difusa.',
    pitfalls: ['Tratar con radioyodo una orbitopatía de Graves activa moderada o grave sin protección esteroidea: puede empeorarla.'],
    sources: ['ata2016'],
  },
  {
    id: 'tiroiditis-graves',
    title: 'Tiroiditis vs Graves',
    subtitle: 'Liberación de hormona preformada frente a síntesis estimulada.',
    topics: ['hipertiroidismo'],
    columns: ['Tiroiditis subaguda (de Quervain)', 'Tiroiditis silente o posparto', 'Graves'],
    rows: [
      ['Dolor tiroideo', '**Sí**, irradiado a mandíbula u oído; antecedente viral', 'No', 'No'],
      ['VSG / PCR', '**Muy elevadas**', 'Normales', 'Normales'],
      ['Captación', 'Baja', 'Baja', 'Alta y difusa'],
      ['T3/T4', 'Predominio de T4', 'Predominio de T4', 'T3 proporcionalmente alta'],
      ['Evolución', 'Tirotoxicosis → hipotiroidismo transitorio → eutiroidismo', 'Igual; la posparto aparece a los 1–6 meses del parto', 'Persistente'],
      ['Tratamiento', 'AINE o prednisona + betabloqueo', 'Betabloqueo', 'Antitiroideos, radioyodo o cirugía'],
    ],
    decisive: '**Captación baja** (o TRAb negativos) con tirotoxicosis = tiroiditis; si además hay **dolor + VSG alta** = subaguda.',
    pitfalls: ['Iniciar antitiroideos en una tiroiditis posparto.', 'No anticipar la fase hipotiroidea posterior.'],
    sources: ['ata2016'],
  },
  {
    id: 'hipo-primario-central',
    title: 'Hipotiroidismo primario vs central',
    subtitle: 'Dónde está el fallo: la glándula o la hipófisis y el hipotálamo.',
    topics: ['hipotiroidismo'],
    columns: ['Primario', 'Central (secundario o terciario)'],
    rows: [
      ['Frecuencia', '>95 % de los casos', 'Raro'],
      ['TSH', '**Alta**', 'Baja, normal o levemente alta (inactiva)'],
      ['T4 libre', 'Baja (normal en el subclínico)', 'Baja'],
      ['Causas', 'Hashimoto, radioyodo, tiroidectomía, fármacos', 'Tumores hipofisarios, cirugía o radiación, Sheehan, hipofisitis'],
      ['Otras pistas', 'Anti-TPO positivos, bocio', 'Otros déficits hipofisarios (cortisol, gonadal), cefalea, alteración visual'],
      ['Ajuste de dosis', 'Por TSH', 'Por **T4 libre** (la TSH no sirve)'],
      ['Precaución', '—', '**Descartar o tratar la insuficiencia suprarrenal antes** de la levotiroxina'],
    ],
    decisive: 'T4 libre baja con **TSH no elevada** = central. Evalúa el eje corticotropo antes de iniciar la levotiroxina.',
    pitfalls: ['Cribar solo con TSH a un paciente con enfermedad hipofisaria conocida.', 'Dar levotiroxina sin cubrir una insuficiencia suprarrenal (puede precipitar una crisis).'],
    sources: ['ata2014'],
  },
  {
    id: 'coma-tormenta',
    title: 'Coma mixedematoso vs tormenta tiroidea',
    subtitle: 'Las dos emergencias tiroideas: el diagnóstico es clínico.',
    topics: ['hipotiroidismo', 'hipertiroidismo'],
    columns: ['Coma mixedematoso', 'Tormenta tiroidea'],
    rows: [
      ['Paciente', 'Mujer anciana con hipotiroidismo no tratado, en invierno', 'Graves no tratado o mal controlado'],
      ['Precipitantes', 'Infección, frío, sedantes u opioides, ictus, cirugía', 'Infección, cirugía, parto, radioyodo, suspensión de antitiroideos, contraste yodado'],
      ['Temperatura', '**Hipotermia**', '**Hiperpirexia**'],
      ['Neurológico', 'Obnubilación, coma', 'Agitación, delirio, convulsiones, coma'],
      ['Cardiovascular', 'Bradicardia, hipotensión, derrame pericárdico', 'Taquicardia (FA), insuficiencia cardíaca de alto gasto'],
      ['Laboratorio', 'Hiponatremia, hipoglucemia, hipercapnia, CK alta', 'Hiperglucemia, alteración hepática; hormonas no mucho más altas que en una tirotoxicosis simple'],
      ['Tratamiento clave', 'Levotiroxina IV + **hidrocortisona** + soporte ventilatorio y calentamiento pasivo', '**Betabloqueo + PTU (o metimazol) → yodo ≥1 h después** + hidrocortisona + medidas de soporte'],
    ],
    decisive: 'No hay un punto de corte hormonal que defina la emergencia: la **descompensación orgánica** (conciencia, temperatura, cardiovascular) es la que la define. Burch-Wartofsky ≥45 apoya la tormenta.',
    pitfalls: ['Esperar el resultado de laboratorio para tratar.', 'Recalentar activamente el coma mixedematoso (vasodilatación e hipotensión).', 'Dar yodo antes de la tionamida en la tormenta.'],
    sources: ['ata2014', 'ata2016'],
  },
  {
    id: 'tormenta-tirotox',
    title: 'Tormenta tiroidea vs tirotoxicosis descompensada',
    subtitle: 'Cuándo una tirotoxicosis se convierte en emergencia.',
    topics: ['hipertiroidismo'],
    columns: ['Tirotoxicosis sintomática', 'Tormenta tiroidea'],
    rows: [
      ['Temperatura', 'Normal o febrícula', 'Fiebre alta (≥38,5–40 °C)'],
      ['Conciencia', 'Ansiedad, temblor', 'Agitación, delirio, psicosis, estupor o coma'],
      ['Cardiovascular', 'Taquicardia sinusal', 'Taquicardia >130, FA, insuficiencia cardíaca'],
      ['Digestivo', 'Hiperdefecación', 'Vómitos, diarrea, ictericia'],
      ['Burch-Wartofsky', '<25', '**≥45** (25–44: tormenta inminente)'],
      ['Manejo', 'Ambulatorio: betabloqueo + metimazol', 'UCI; tratamiento multimodal inmediato'],
    ],
    decisive: 'La **disfunción de órganos** (SNC, termorregulación, corazón, hígado) en un paciente tirotóxico marca la tormenta, no la cifra de T4.',
    pitfalls: ['Usar aspirina como antitérmico: desplaza la T4 de la TBG. Usa paracetamol.'],
    sources: ['ata2016'],
  },
  {
    id: 'hsa-cefaleas',
    title: 'HSA vs otras causas de cefalea aguda intensa',
    subtitle: 'Cefalea en trueno: la HSA es la que no se puede pasar por alto.',
    topics: ['hsa'],
    columns: ['HSA aneurismática', 'Vasoconstricción cerebral reversible', 'Disección cervical', 'Apoplejía hipofisaria', 'Trombosis venosa cerebral'],
    rows: [
      ['Inicio', 'Máximo en <1 min, «la peor de mi vida»', 'Truenos **recurrentes** durante días; desencadenantes (esfuerzo, sexo, fármacos vasoactivos, posparto)', 'Dolor cervical u occipital', 'Brusco, con alteración visual', 'Subagudo; a veces en trueno'],
      ['Pistas', 'Rigidez de nuca, pérdida de conciencia, vómitos; hemorragia en la TC', 'TC a menudo normal; HSA de convexidad posible', 'Horner, dolor cervical, ictus', 'Oftalmoplejía, **hemianopsia bitemporal**, hipotensión (déficit de ACTH)', 'Estado protrombótico, papiledema, convulsiones'],
      ['Prueba clave', 'TC sin contraste → (PL) → angio-TC', 'Angiografía: estenosis multifocales «en rosario» que se revierten en 12 semanas', 'Angio-TC/RM de cuello', 'RM de silla turca', 'Venografía por TC o RM'],
    ],
    decisive: '**Pico en <1 minuto** + rigidez de nuca, síncope o edad ≥40 → HSA hasta demostrar lo contrario (regla de Ottawa). TC en <6 h normal con buena técnica prácticamente la excluye; después de 6 h, la TC negativa obliga a PL o angio-TC.',
    pitfalls: ['Considerar tranquilizadora la mejora con analgésicos: una cefalea centinela también mejora.', 'Dar el alta con TC negativa tras 6 h sin PL ni angio-TC.'],
    sources: ['aha2023', 'perry'],
  },
  {
    id: 'hsa-complicaciones',
    title: 'Complicaciones de la HSA',
    subtitle: 'Cada complicación tiene su ventana temporal.',
    topics: ['hsa'],
    columns: ['Momento típico', 'Cómo se reconoce', 'Qué hacer'],
    rows: [
      ['Resangrado', '**Primeras 24 h** (sobre todo las primeras 6 h)', 'Deterioro brusco, cefalea nueva, más sangre en la TC', 'Tratar el aneurisma lo antes posible (ideal <24 h); control de PA; corregir la anticoagulación'],
      ['Hidrocefalia aguda', 'Horas a días', 'Descenso del nivel de conciencia, mirada desviada hacia abajo; ventrículos dilatados', 'Derivación de LCR urgente (drenaje ventricular externo)'],
      ['Isquemia cerebral tardía / vasoespasmo', '**Días 3–14** (pico entre los días 4 y 10)', 'Déficit focal nuevo o descenso del nivel de conciencia; DTC con velocidades altas', 'Nimodipino (profilaxis); euvolemia; elevar la PA si hay isquemia; terapia endovascular'],
      ['Hiponatremia', 'Días 3–14', 'Na⁺ bajo; síndrome pierde sal cerebral (hipovolemia) o SIADH', 'Evitar la restricción hídrica; salino isotónico o hipertónico; fludrocortisona'],
      ['Convulsiones', 'Al inicio o tardías', 'Crisis clínicas; EEG si el coma no se explica', 'Anticonvulsivante 7 días si hay crisis; no usar fenitoína de rutina'],
      ['Cardiopulmonares', 'Primeros días', 'Troponina alta, ECG anormal, miocardiopatía de estrés; edema pulmonar neurogénico', 'Soporte; ecocardiograma'],
    ],
    decisive: 'El **momento** orienta: deterioro en las primeras horas → resangrado o hidrocefalia; entre los días 3 y 14 → isquemia tardía o hiponatremia.',
    pitfalls: ['Restringir líquidos ante una hiponatremia en la HSA.', 'Hipervolemia «profiláctica» (triple H): no se recomienda.'],
    sources: ['aha2023'],
  },
]);
