/* Fuentes médicas. verify:
 *   'referencia'  obra de referencia general (no cotejada textualmente)
 *   'verificada'  recomendaciones concretas contrastadas en esta revisión
 *   'pendiente'   pendiente de cotejo
 * Para añadir una fuente: agrega un objeto con id único y cítalo por su id
 * en los temas (sources: [...]) o en los valores. */
SolMed.registry.addSources([
  {
    id: 'harrison22',
    short: 'Harrison 22.ª ed.',
    title: 'Harrison. Principios de Medicina Interna',
    authors: 'Loscalzo J, Fauci AS, Kasper DL, Hauser SL, Longo DL, Jameson JL (eds.)',
    edition: '22.ª edición',
    year: 2025,
    verify: 'pendiente',
    reviewed: '2026-09-26',
    note: 'Fuente principal del proyecto (edición más reciente). **No se consultó el texto directamente en esta versión**: el contenido se redactó con conocimiento concordante y no se atribuyen a Harrison citas ni cifras concretas. Cotejo capítulo por capítulo pendiente.',
  },
  {
    id: 'ada2024',
    short: 'Consenso ADA/EASD/JBDS/AACE/DTS 2024',
    title: 'Hyperglycemic Crises in Adults With Diabetes: A Consensus Report',
    authors: 'Umpierrez GE, Davis GM, ElSayed NA, et al.',
    edition: 'Diabetes Care 2024;47(8):1257–1275',
    year: 2024,
    verify: 'verificada',
    reviewed: '2026-09-26',
    note: 'Criterios diagnósticos de CAD y EHH (glucosa ≥200 mg/dL o diabetes conocida; β-hidroxibutirato ≥3,0 mmol/L; pH <7,3 y/o HCO₃⁻ <18), criterios de resolución, potasio <3,5 antes de insulina, bicarbonato solo si pH <7,0, dextrosa con glucosa <250 mg/dL y solapamiento de 1–2 h con insulina subcutánea.',
  },
  {
    id: 'ada2009',
    short: 'Consenso ADA 2009',
    title: 'Hyperglycemic Crises in Adult Patients With Diabetes',
    authors: 'Kitabchi AE, Umpierrez GE, Miles JM, Fisher JN',
    edition: 'Diabetes Care 2009;32(7):1335–1343',
    year: 2009,
    verify: 'referencia',
    reviewed: '2026-09-26',
    note: 'Documento previo, aún citado en muchos exámenes: clasificación de gravedad de la CAD por pH/HCO₃⁻/estado mental y criterios antiguos (anion gap >10–12, bicarbonato si pH <6,9). Sol MED indica cuándo difiere de 2024.',
  },
  {
    id: 'jbds',
    short: 'JBDS (Reino Unido)',
    title: 'Joint British Diabetes Societies: management of HHS and DKA in adults',
    authors: 'Joint British Diabetes Societies for Inpatient Care',
    edition: 'Guías JBDS-IP (HHS 2022; DKA 2023)',
    year: 2023,
    verify: 'referencia',
    reviewed: '2026-09-26',
    note: 'Metas de descenso de osmolalidad y sodio en EHH (evitar correcciones rápidas).',
  },
  {
    id: 'ata2016',
    short: 'ATA 2016 (hipertiroidismo)',
    title: 'American Thyroid Association Guidelines for Diagnosis and Management of Hyperthyroidism and Other Causes of Thyrotoxicosis',
    authors: 'Ross DS, Burch HB, Cooper DS, et al.',
    edition: 'Thyroid 2016;26(10):1343–1421',
    year: 2016,
    verify: 'verificada',
    reviewed: '2026-09-26',
    note: 'Tormenta tiroidea: PTU 500–1000 mg de carga, glucocorticoides (hidrocortisona 300 mg/día), yodo tras la tionamida, betabloqueo. Metimazol de elección salvo 1.er trimestre y tormenta.',
  },
  {
    id: 'ata2014',
    short: 'ATA 2014 (hipotiroidismo)',
    title: 'Guidelines for the Treatment of Hypothyroidism',
    authors: 'Jonklaas J, Bianco AC, Bauer AJ, et al.',
    edition: 'Thyroid 2014;24(12):1670–1751',
    year: 2014,
    verify: 'referencia',
    reviewed: '2026-09-26',
    note: 'Levotiroxina 1,6 µg/kg/día; inicio bajo en ancianos y cardiopatía; coma mixedematoso con levotiroxina IV y glucocorticoide.',
  },
  {
    id: 'aha2023',
    short: 'AHA/ASA 2023 (HSA aneurismática)',
    title: '2023 Guideline for the Management of Patients With Aneurysmal Subarachnoid Hemorrhage',
    authors: 'Hoh BL, Ko NU, Amin-Hanjani S, et al.',
    edition: 'Stroke 2023;54:e314–e370',
    year: 2023,
    verify: 'verificada',
    reviewed: '2026-09-26',
    note: 'Tratar el aneurisma idealmente en <24 h; nimodipino enteral precoz; euvolemia (no hipervolemia profiláctica); no hay meta de PA basada en evidencia firme; profilaxis anticonvulsiva no rutinaria y evitar fenitoína; antifibrinolíticos sin beneficio funcional; derivación de LCR urgente en hidrocefalia sintomática.',
  },
  {
    id: 'perry',
    short: 'Perry et al. (TC <6 h y regla de Ottawa)',
    title: 'Sensitivity of CT within 6 hours for SAH (BMJ 2011) · Ottawa SAH Rule (JAMA 2013)',
    authors: 'Perry JJ, Stiell IG, et al.',
    edition: 'BMJ 2011;343:d4277 · JAMA 2013;310:1248–1255',
    year: 2013,
    verify: 'referencia',
    reviewed: '2026-09-26',
    note: 'TC sin contraste en <6 h desde el inicio, con equipo moderno e interpretación experta, con sensibilidad cercana al 100 %. Regla de Ottawa para cefalea aguda no traumática.',
  },
  {
    id: 'acidbase',
    short: 'Fisiología ácido-base (fórmulas clásicas)',
    title: 'Fórmulas de compensación y anion gap',
    authors: 'Winter RW (1967) y textos de nefrología/medicina interna',
    edition: 'Fórmulas estándar',
    year: 1967,
    verify: 'referencia',
    reviewed: '2026-09-26',
    note: 'PaCO₂ esperada = 1,5 × HCO₃⁻ + 8 ± 2; anion gap = Na⁺ − (Cl⁻ + HCO₃⁻); corrección por albúmina 2,5 mEq/L por cada 1 g/dL; sodio corregido 1,6 mEq/L por cada 100 mg/dL (Katz) o 2,4 (Hillier).',
  },
]);
